// 100个新的交流对话单词
const conversations100New = [
    { word: 'Long time no see', phonetic: '/lɒŋ taɪm nəʊ siː/', homophone: '朗泰姆诺西', meaning: '好久不见', sentence: 'Long time no see!', translation: '好久不见！', homophoneSentence: '朗泰姆诺西!' },
    { word: 'What have you been up to', phonetic: '/wɒt hæv juː biːn ʌp tuː/', homophone: '沃特海夫油比恩阿普图', meaning: '你最近在忙什么', sentence: 'What have you been up to?', translation: '你最近在忙什么？', homophoneSentence: '沃特海夫油比恩阿普图?' },
    { word: 'I\'ve been busy', phonetic: '/aɪv biːn ˈbɪzi/', homophone: '爱夫比恩比兹', meaning: '我一直很忙', sentence: 'I\'ve been busy with work.', translation: '我一直忙于工作。', homophoneSentence: '爱夫比恩比兹威泽沃克.' },
    { word: 'Same as usual', phonetic: '/seɪm æz ˈjuːʒuəl/', homophone: '赛姆艾兹尤久尔', meaning: '老样子', sentence: 'Same as usual.', translation: '老样子。', homophoneSentence: '赛姆艾兹尤久尔.' },
    { word: 'Not too bad', phonetic: '/nɒt tuː bæd/', homophone: '诺特图拜德', meaning: '还不错', sentence: 'Not too bad, thanks.', translation: '还不错，谢谢。', homophoneSentence: '诺特图拜德，森克斯.' },
    { word: 'Could be better', phonetic: '/kʊd biː ˈbetə/', homophone: '库德比百特', meaning: '还可以更好', sentence: 'Could be better.', translation: '还可以更好。', homophoneSentence: '库德比百特.' },
    { word: 'I\'m exhausted', phonetic: '/aɪm ɪɡˈzɔːstɪd/', homophone: '爱姆伊格佐斯提德', meaning: '我累坏了', sentence: 'I\'m exhausted today.', translation: '我今天累坏了。', homophoneSentence: '爱姆伊格佐斯提德特戴.' },
    { word: 'I\'m starving', phonetic: '/aɪm ˈstɑːvɪŋ/', homophone: '爱姆斯塔文英', meaning: '我饿死了', sentence: 'I\'m starving!', translation: '我饿死了！', homophoneSentence: '爱姆斯塔文英!' },
    { word: 'I\'m freezing', phonetic: '/aɪm ˈfriːzɪŋ/', homophone: '爱姆夫瑞兹英', meaning: '我冻死了', sentence: 'I\'m freezing!', translation: '我冻死了！', homophoneSentence: '爱姆夫瑞兹英!' },
    { word: 'I\'m burning up', phonetic: '/aɪm ˈbɜːnɪŋ ʌp/', homophone: '爱姆波宁阿普', meaning: '我热死了', sentence: 'I\'m burning up!', translation: '我热死了！', homophoneSentence: '爱姆波宁阿普!' },
    { word: 'I\'m running late', phonetic: '/aɪm ˈrʌnɪŋ leɪt/', homophone: '爱姆拉宁雷特', meaning: '我要迟到了', sentence: 'I\'m running late!', translation: '我要迟到了！', homophoneSentence: '爱姆拉宁雷特!' },
    { word: 'I\'m in a hurry', phonetic: '/aɪm ɪn ə ˈhʌri/', homophone: '爱姆因啊哈瑞', meaning: '我很着急', sentence: 'I\'m in a hurry.', translation: '我很着急。', homophoneSentence: '爱姆因啊哈瑞.' },
    { word: 'Take your time', phonetic: '/teɪk jɔː taɪm/', homophone: '泰克哟泰姆', meaning: '慢慢来', sentence: 'Take your time.', translation: '慢慢来。', homophoneSentence: '泰克哟泰姆.' },
    { word: 'No rush', phonetic: '/nəʊ rʌʃ/', homophone: '诺拉什', meaning: '不着急', sentence: 'No rush.', translation: '不着急。', homophoneSentence: '诺拉什.' },
    { word: 'At your earliest convenience', phonetic: '/æt jɔː ˈɜːliɪst kənˈviːniəns/', homophone: '艾特哟厄利斯特康维尼恩斯', meaning: '在您方便时尽早', sentence: 'Please reply at your earliest convenience.', translation: '请在您方便时尽早回复。', homophoneSentence: '普利斯瑞普来艾特哟厄利斯特康维尼恩斯.' },
    { word: 'ASAP', phonetic: '/ˌeɪ es eɪ ˈpiː/', homophone: '艾艾斯艾皮', meaning: '尽快', sentence: 'Please do it ASAP.', translation: '请尽快做。', homophoneSentence: '普利斯度伊特艾艾斯艾皮.' },
    { word: 'By all means', phonetic: '/baɪ ɔːl miːnz/', homophone: '拜奥尔敏兹', meaning: '务必', sentence: 'By all means, go ahead.', translation: '务必，请继续。', homophoneSentence: '拜奥尔敏兹，勾啊海德.' },
    { word: 'Go for it', phonetic: '/ɡəʊ fɔːr ɪt/', homophone: '勾佛伊特', meaning: '去争取吧', sentence: 'Go for it!', translation: '去争取吧！', homophoneSentence: '勾佛伊特!' },
    { word: 'Give it a try', phonetic: '/ɡɪv ɪt ə traɪ/', homophone: '盖夫伊特啊踹', meaning: '试一试', sentence: 'Give it a try!', translation: '试一试！', homophoneSentence: '盖夫伊特啊踹!' },
    { word: 'Have a shot', phonetic: '/hæv ə ʃɒt/', homophone: '海夫啊肖特', meaning: '尝试一下', sentence: 'Have a shot!', translation: '尝试一下！', homophoneSentence: '海夫啊肖特!' },
    { word: 'It\'s worth a try', phonetic: '/ɪts wɜːθ ə traɪ/', homophone: '伊茨沃斯啊踹', meaning: '值得一试', sentence: 'It\'s worth a try.', translation: '值得一试。', homophoneSentence: '伊茨沃斯啊踹.' },
    { word: 'You never know', phonetic: '/juː ˈnevə nəʊ/', homophone: '优奈夫诺', meaning: '谁知道呢', sentence: 'You never know until you try.', translation: '不试怎么知道。', homophoneSentence: '优奈夫诺昂提尔优踹.' },
    { word: 'What do you think', phonetic: '/wɒt duː juː θɪŋk/', homophone: '沃特度油星克', meaning: '你觉得怎么样', sentence: 'What do you think?', translation: '你觉得怎么样？', homophoneSentence: '沃特度油星克?' },
    { word: 'What\'s your opinion', phonetic: '/wɒts jɔː əˈpɪnjən/', homophone: '沃茨哟欧皮尼恩', meaning: '你的意见是什么', sentence: 'What\'s your opinion?', translation: '你的意见是什么？', homophoneSentence: '沃茨哟欧皮尼恩?' },
    { word: 'In my opinion', phonetic: '/ɪn maɪ əˈpɪnjən/', homophone: '因麦欧皮尼恩', meaning: '在我看来', sentence: 'In my opinion, you\'re right.', translation: '在我看来，你是对的。', homophoneSentence: '因麦欧皮尼恩，优啊来特.' },
    { word: 'If you ask me', phonetic: '/ɪf juː ɑːsk miː/', homophone: '伊夫油阿斯科米', meaning: '要我说', sentence: 'If you ask me, it\'s too expensive.', translation: '要我说，这太贵了。', homophoneSentence: '伊夫油阿斯科米，伊茨图伊克斯潘西夫.' },
    { word: 'As far as I\'m concerned', phonetic: '/æz fɑːr æz aɪm kənˈsɜːnd/', homophone: '艾兹法尔艾兹爱姆康瑟恩德', meaning: '就我而言', sentence: 'As far as I\'m concerned, it\'s fine.', translation: '就我而言，这没问题。', homophoneSentence: '艾兹法尔艾兹爱姆康瑟恩德，伊茨法因.' },
    { word: 'From my perspective', phonetic: '/frɒm maɪ pəˈspektɪv/', homophone: '夫罗姆麦波斯佩克提夫', meaning: '从我的角度来看', sentence: 'From my perspective, it\'s a good idea.', translation: '从我的角度来看，这是个好主意。', homophoneSentence: '夫罗姆麦波斯佩克提夫，伊茨啊古德艾迪尔.' },
    { word: 'The way I see it', phonetic: '/ðə weɪ aɪ siː ɪt/', homophone: '泽威爱西伊特', meaning: '依我看', sentence: 'The way I see it, we should wait.', translation: '依我看，我们应该等待。', homophoneSentence: '泽威爱西伊特，威休德威特.' },
    { word: 'To be honest', phonetic: '/tuː biː ˈɒnɪst/', homophone: '图比奥尼斯特', meaning: '说实话', sentence: 'To be honest, I don\'t like it.', translation: '说实话，我不喜欢它。', homophoneSentence: '图比奥尼斯特，爱东特莱克伊特.' },
    { word: 'To tell you the truth', phonetic: '/tuː tel juː ðə truːθ/', homophone: '图泰尔油泽图斯', meaning: '说实话', sentence: 'To tell you the truth, I\'m tired.', translation: '说实话，我累了。', homophoneSentence: '图泰尔油泽图斯，爱姆泰尔德.' },
    { word: 'Frankly speaking', phonetic: '/ˈfræŋkli ˈspiːkɪŋ/', homophone: '弗兰克利斯皮克英', meaning: '坦率地说', sentence: 'Frankly speaking, I disagree.', translation: '坦率地说，我不同意。', homophoneSentence: '弗兰克利斯皮克英，爱迪斯阿格丽.' },
    { word: 'Between you and me', phonetic: '/bɪˈtwiːn juː ænd miː/', homophone: '比特温油安德米', meaning: '就你我知道', sentence: 'Between you and me, he\'s leaving.', translation: '就你我知道，他要离开了。', homophoneSentence: '比特温油安德米，希兹利夫英.' },
    { word: 'Off the record', phonetic: '/ɒf ðə ˈrekɔːd/', homophone: '奥夫泽瑞考德', meaning: '非正式的', sentence: 'Off the record, what do you think?', translation: '非正式地，你怎么看？', homophoneSentence: '奥夫泽瑞考德，沃特度油星克?' },
    { word: 'Don\'t get me wrong', phonetic: '/dəʊnt ɡet miː rɒŋ/', homophone: '东特盖特米若昂', meaning: '别误会我', sentence: 'Don\'t get me wrong, I like him.', translation: '别误会我，我喜欢他。', homophoneSentence: '东特盖特米若昂，爱莱克希姆.' },
    { word: 'No offense', phonetic: '/nəʊ əˈfens/', homophone: '诺啊芬斯', meaning: '无意冒犯', sentence: 'No offense, but you\'re wrong.', translation: '无意冒犯，但你错了。', homophoneSentence: '诺啊芬斯，巴特优若昂.' },
    { word: 'Don\'t take it personally', phonetic: '/dəʊnt teɪk ɪt ˈpɜːsənəli/', homophone: '东特泰克伊特波瑟纳利', meaning: '别往心里去', sentence: 'Don\'t take it personally.', translation: '别往心里去。', homophoneSentence: '东特泰克伊特波瑟纳利.' },
    { word: 'I\'m just saying', phonetic: '/aɪm dʒʌst ˈseɪɪŋ/', homophone: '爱姆贾斯特赛英', meaning: '我只是说说', sentence: 'I\'m just saying.', translation: '我只是说说。', homophoneSentence: '爱姆贾斯特赛英.' },
    { word: 'Just so you know', phonetic: '/dʒʌst səʊ juː nəʊ/', homophone: '贾斯特搜油诺', meaning: '只是让你知道', sentence: 'Just so you know, I\'m busy.', translation: '只是让你知道，我很忙。', homophoneSentence: '贾斯特搜油诺，爱姆比兹.' },
    { word: 'For your information', phonetic: '/fɔː jɔː ˌɪnfəˈmeɪʃn/', homophone: '佛哟因佛梅申', meaning: '供你参考', sentence: 'For your information, the meeting is cancelled.', translation: '供你参考，会议取消了。', homophoneSentence: '佛哟因佛梅申，泽米听is康斯德.' },
    { word: 'By the way', phonetic: '/baɪ ðə weɪ/', homophone: '拜泽威', meaning: '顺便说一下', sentence: 'By the way, where are you going?', translation: '顺便说一下，你要去哪里？', homophoneSentence: '拜泽威，威尔阿油勾英?' },
    { word: 'Speaking of which', phonetic: '/ˈspiːkɪŋ əv wɪtʃ/', homophone: '斯皮克英啊夫威奇', meaning: '说到这个', sentence: 'Speaking of which, have you finished?', translation: '说到这个，你完成了吗？', homophoneSentence: '斯皮克英啊夫威奇，海夫油芬尼斯特?' },
    { word: 'That reminds me', phonetic: '/ðæt rɪˈmaɪndz miː/', homophone: '泽特里迈因兹米', meaning: '这提醒了我', sentence: 'That reminds me, I need to call her.', translation: '这提醒了我，我需要给她打电话。', homophoneSentence: '泽特里迈因兹米，爱尼德图考尔赫尔.' },
    { word: 'On another note', phonetic: '/ɒn əˈnʌðə nəʊt/', homophone: '昂啊纳泽诺特', meaning: '换个话题', sentence: 'On another note, how\'s your family?', translation: '换个话题，你家人怎么样？', homophoneSentence: '昂啊纳泽诺特，好兹哟法梅里?' },
    { word: 'Anyway', phonetic: '/ˈeniweɪ/', homophone: '艾尼威', meaning: '无论如何', sentence: 'Anyway, let\'s get started.', translation: '无论如何，让我们开始吧。', homophoneSentence: '艾尼威，莱茨盖特斯达特德.' },
    { word: 'Getting back to', phonetic: '/ˈɡetɪŋ bæk tuː/', homophone: '盖特英拜克图', meaning: '回到', sentence: 'Getting back to what we were saying.', translation: '回到我们刚才说的。', homophoneSentence: '盖特英拜克图沃特威沃赛英.' },
    { word: 'Where were we', phonetic: '/weə wɜː wiː/', homophone: '威尔威威', meaning: '我们说到哪了', sentence: 'Where were we?', translation: '我们说到哪了？', homophoneSentence: '威尔威威?' },
    { word: 'Let\'s move on', phonetic: '/lets muːv ɒn/', homophone: '莱茨穆夫昂', meaning: '让我们继续', sentence: 'Let\'s move on to the next topic.', translation: '让我们继续下一个话题。', homophoneSentence: '莱茨穆夫昂图泽奈克斯特托皮克.' },
    { word: 'Shall we begin', phonetic: '/ʃæl wiː bɪˈɡɪn/', homophone: '夏尔威比金', meaning: '我们可以开始了吗', sentence: 'Shall we begin?', translation: '我们可以开始了吗？', homophoneSentence: '夏尔威比金?' },
    { word: 'Let\'s get started', phonetic: '/lets ɡet ˈstɑːtɪd/', homophone: '莱茨盖特斯达提德', meaning: '让我们开始吧', sentence: 'Let\'s get started!', translation: '让我们开始吧！', homophoneSentence: '莱茨盖特斯达提德!' },
    { word: 'Let\'s call it a day', phonetic: '/lets kɔːl ɪt ə deɪ/', homophone: '莱茨考尔伊特啊戴', meaning: '今天就到这里吧', sentence: 'Let\'s call it a day.', translation: '今天就到这里吧。', homophoneSentence: '莱茨考尔伊特啊戴.' },
    { word: 'That\'s all for today', phonetic: '/ðæts ɔːl fɔː təˈdeɪ/', homophone: '泽茨奥尔佛特戴', meaning: '今天就这些', sentence: 'That\'s all for today.', translation: '今天就这些。', homophoneSentence: '泽茨奥尔佛特戴.' },
    { word: 'We\'ll continue tomorrow', phonetic: '/wiːl kənˈtɪnjuː təˈmɒrəʊ/', homophone: '威尔康提纽特莫柔', meaning: '我们明天继续', sentence: 'We\'ll continue tomorrow.', translation: '我们明天继续。', homophoneSentence: '威尔康提纽特莫柔.' },
    { word: 'See you then', phonetic: '/siː juː ðen/', homophone: '西油泽恩', meaning: '到时候见', sentence: 'See you then!', translation: '到时候见！', homophoneSentence: '西油泽恩!' },
    { word: 'Have a good weekend', phonetic: '/hæv ə ɡʊd ˈwiːkend/', homophone: '海夫啊古德威肯德', meaning: '周末愉快', sentence: 'Have a good weekend!', translation: '周末愉快！', homophoneSentence: '海夫啊古德威肯德!' },
    { word: 'Enjoy your vacation', phonetic: '/ɪnˈdʒɔɪ jɔː vəˈkeɪʃn/', homophone: '因照伊哟沃凯申', meaning: '享受你的假期', sentence: 'Enjoy your vacation!', translation: '享受你的假期！', homophoneSentence: '因照伊哟沃凯申!' },
    { word: 'Safe travels', phonetic: '/seɪf ˈtrævlz/', homophone: '赛夫特拉维尔兹', meaning: '一路平安', sentence: 'Safe travels!', translation: '一路平安！', homophoneSentence: '赛夫特拉维尔兹!' },
    { word: 'Bon voyage', phonetic: '/ˌbɒn vɔɪˈɑːʒ/', homophone: '邦沃亚日', meaning: '一路顺风', sentence: 'Bon voyage!', translation: '一路顺风！', homophoneSentence: '邦沃亚日!' },
    { word: 'Break a leg', phonetic: '/breɪk ə leɡ/', homophone: '布雷克啊莱格', meaning: '祝你好运', sentence: 'Break a leg!', translation: '祝你好运！', homophoneSentence: '布雷克啊莱格!' },
    { word: 'Fingers crossed', phonetic: '/ˈfɪŋɡəz krɒst/', homophone: '芬格尔兹克罗斯特', meaning: '祈祷好运', sentence: 'Fingers crossed!', translation: '祈祷好运！', homophoneSentence: '芬格尔兹克罗斯特!' },
    { word: 'Wish me luck', phonetic: '/wɪʃ miː lʌk/', homophone: '威什米拉客', meaning: '祝我好运', sentence: 'Wish me luck!', translation: '祝我好运！', homophoneSentence: '威什米拉客!' },
    { word: 'I\'m keeping my fingers crossed', phonetic: '/aɪm ˈkiːpɪŋ maɪ ˈfɪŋɡəz krɒst/', homophone: '爱姆基平麦芬格尔兹克罗斯特', meaning: '我祈祷好运', sentence: 'I\'m keeping my fingers crossed.', translation: '我祈祷好运。', homophoneSentence: '爱姆基平麦芬格尔兹克罗斯特.' },
    { word: 'Knock on wood', phonetic: '/nɒk ɒn wʊd/', homophone: '诺克昂伍德', meaning: '但愿好运持续', sentence: 'Knock on wood!', translation: '但愿好运持续！', homophoneSentence: '诺克昂伍德!' },
    { word: 'Touch wood', phonetic: '/tʌtʃ wʊd/', homophone: '塔奇伍德', meaning: '但愿好运持续', sentence: 'Touch wood!', translation: '但愿好运持续！', homophoneSentence: '塔奇伍德!' },
    { word: 'Best of luck', phonetic: '/best əv lʌk/', homophone: '贝斯特啊夫拉客', meaning: '祝你好运', sentence: 'Best of luck!', translation: '祝你好运！', homophoneSentence: '贝斯特啊夫拉客!' },
    { word: 'Good for you', phonetic: '/ɡʊd fɔː juː/', homophone: '古德佛油', meaning: '真为你高兴', sentence: 'Good for you!', translation: '真为你高兴！', homophoneSentence: '古德佛油!' },
    { word: 'I\'m happy for you', phonetic: '/aɪm ˈhæpi fɔː juː/', homophone: '爱姆嗨皮佛油', meaning: '我为你高兴', sentence: 'I\'m happy for you!', translation: '我为你高兴！', homophoneSentence: '爱姆嗨皮佛油!' },
    { word: 'That\'s wonderful news', phonetic: '/ðæts ˈwʌndəfl njuːz/', homophone: '泽茨旺德夫欧纽兹', meaning: '那是个好消息', sentence: 'That\'s wonderful news!', translation: '那是个好消息！', homophoneSentence: '泽茨旺德夫欧纽兹!' },
    { word: 'I\'m thrilled', phonetic: '/aɪm θrɪld/', homophone: '爱姆斯瑞尔德', meaning: '我太激动了', sentence: 'I\'m thrilled!', translation: '我太激动了！', homophoneSentence: '爱姆斯瑞尔德!' },
    { word: 'How exciting', phonetic: '/haʊ ɪkˈsaɪtɪŋ/', homophone: '好伊克赛特英', meaning: '太令人兴奋了', sentence: 'How exciting!', translation: '太令人兴奋了！', homophoneSentence: '好伊克赛特英!' },
    { word: 'That\'s a relief', phonetic: '/ðæts ə rɪˈliːf/', homophone: '泽茨啊瑞利夫', meaning: '真是松了一口气', sentence: 'That\'s a relief!', translation: '真是松了一口气！', homophoneSentence: '泽茨啊瑞利夫!' },
    { word: 'You made my day', phonetic: '/juː meɪd maɪ deɪ/', homophone: '优梅德麦戴', meaning: '你让我很开心', sentence: 'You made my day!', translation: '你让我很开心！', homophoneSentence: '优梅德麦戴!' },
    { word: 'That\'s very kind of you', phonetic: '/ðæts ˈveri kaɪnd əv juː/', homophone: '泽茨维里坎德啊夫油', meaning: '你真是太好了', sentence: 'That\'s very kind of you.', translation: '你真是太好了。', homophoneSentence: '泽茨维里坎德啊夫油.' },
    { word: 'You shouldn\'t have', phonetic: '/juː ˈʃʊdnt hæv/', homophone: '优休登特海夫', meaning: '你太客气了', sentence: 'You shouldn\'t have!', translation: '你太客气了！', homophoneSentence: '优休登特海夫!' },
    { word: 'It\'s the thought that counts', phonetic: '/ɪts ðə θɔːt ðæt kaʊnts/', homophone: '伊茨泽索特泽特康茨', meaning: '心意最重要', sentence: 'It\'s the thought that counts.', translation: '心意最重要。', homophoneSentence: '伊茨泽索特泽特康茨.' }
];

module.exports = conversations100New;
