// 批量生成的日常问候单词数据 - 200个
const greetingsBatch = [
    // 基础问候和时间 (1-50)
    { word: "Morning", phonetic: "/ˈmɔːnɪŋ/", homophone: "莫宁", meaning: "早晨", sentence: "Good morning!", translation: "早上好！", homophoneSentence: "古德莫宁!" },
    { word: "Afternoon", phonetic: "/ˌɑːftəˈnuːn/", homophone: "阿夫特努恩", meaning: "下午", sentence: "Good afternoon!", translation: "下午好！", homophoneSentence: "古德阿夫特努恩!" },
    { word: "Evening", phonetic: "/ˈiːvnɪŋ/", homophone: "伊夫宁", meaning: "晚上", sentence: "Good evening!", translation: "晚上好！", homophoneSentence: "古德伊夫宁!" },
    { word: "Night", phonetic: "/naɪt/", homophone: "奈特", meaning: "夜晚", sentence: "Good night!", translation: "晚安！", homophoneSentence: "古德奈特!" },
    { word: "Today", phonetic: "/təˈdeɪ/", homophone: "特戴", meaning: "今天", sentence: "How are you today?", translation: "你今天好吗？", homophoneSentence: "好啊油特戴?" },
    { word: "Tomorrow", phonetic: "/təˈmɒrəʊ/", homophone: "特莫柔", meaning: "明天", sentence: "See you tomorrow!", translation: "明天见！", homophoneSentence: "西优特莫柔!" },
    { word: "Yesterday", phonetic: "/ˈjestədeɪ/", homophone: "耶斯特戴", meaning: "昨天", sentence: "I saw you yesterday.", translation: "我昨天看到你了。", homophoneSentence: "爱索油耶斯特戴." },
    { word: "Week", phonetic: "/wiːk/", homophone: "威克", meaning: "星期", sentence: "Have a good week!", translation: "祝你这周愉快！", homophoneSentence: "海夫啊古德威克!" },
    { word: "Weekend", phonetic: "/ˌwiːkˈend/", homophone: "威肯德", meaning: "周末", sentence: "Happy weekend!", translation: "周末快乐！", homophoneSentence: "嗨皮威肯德!" },
    { word: "Monday", phonetic: "/ˈmʌndeɪ/", homophone: "曼戴", meaning: "星期一", sentence: "See you on Monday!", translation: "星期一见！", homophoneSentence: "西优昂曼戴!" },
    { word: "Tuesday", phonetic: "/ˈtjuːzdeɪ/", homophone: "丘兹戴", meaning: "星期二", sentence: "Tuesday meeting.", translation: "星期二开会。", homophoneSentence: "丘兹戴米听." },
    { word: "Wednesday", phonetic: "/ˈwenzdeɪ/", homophone: "温兹戴", meaning: "星期三", sentence: "Happy Wednesday!", translation: "星期三快乐！", homophoneSentence: "嗨皮温兹戴!" },
    { word: "Thursday", phonetic: "/ˈθɜːzdeɪ/", homophone: "色兹戴", meaning: "星期四", sentence: "Thursday is busy.", translation: "星期四很忙。", homophoneSentence: "色兹戴is比兹." },
    { word: "Friday", phonetic: "/ˈfraɪdeɪ/", homophone: "夫来戴", meaning: "星期五", sentence: "Happy Friday!", translation: "星期五快乐！", homophoneSentence: "嗨皮夫来戴!" },
    { word: "Saturday", phonetic: "/ˈsætədeɪ/", homophone: "萨特戴", meaning: "星期六", sentence: "Saturday is fun!", translation: "星期六很有趣！", homophoneSentence: "萨特戴is范!" },
    { word: "Sunday", phonetic: "/ˈsʌndeɪ/", homophone: "桑戴", meaning: "星期日", sentence: "Relax on Sunday.", translation: "星期日放松。", homophoneSentence: "瑞来克斯昂桑戴." },
    { word: "January", phonetic: "/ˈdʒænjuəri/", homophone: "詹纽瑞", meaning: "一月", sentence: "January is cold.", translation: "一月很冷。", homophoneSentence: "詹纽瑞is扣德." },
    { word: "February", phonetic: "/ˈfebruəri/", homophone: "夫布鲁瑞", meaning: "二月", sentence: "February is short.", translation: "二月很短。", homophoneSentence: "夫布鲁瑞is绍特." },
    { word: "March", phonetic: "/mɑːtʃ/", homophone: "马奇", meaning: "三月", sentence: "March is windy.", translation: "三月多风。", homophoneSentence: "马奇is温迪." },
    { word: "April", phonetic: "/ˈeɪprəl/", homophone: "艾普柔", meaning: "四月", sentence: "April showers.", translation: "四月阵雨。", homophoneSentence: "艾普柔绍尔斯." },
    { word: "May", phonetic: "/meɪ/", homophone: "梅", meaning: "五月", sentence: "May is beautiful.", translation: "五月很美。", homophoneSentence: "梅is比欧特夫欧." },
    { word: "June", phonetic: "/dʒuːn/", homophone: "均", meaning: "六月", sentence: "June is warm.", translation: "六月很温暖。", homophoneSentence: "均is沃姆." },
    { word: "July", phonetic: "/dʒuˈlaɪ/", homophone: "均来", meaning: "七月", sentence: "July is hot.", translation: "七月很热。", homophoneSentence: "均来is豪特." },
    { word: "August", phonetic: "/ˈɔːɡəst/", homophone: "奥古斯特", meaning: "八月", sentence: "August vacation.", translation: "八月假期。", homophoneSentence: "奥古斯特沃凯申." },
    { word: "September", phonetic: "/sepˈtembə(r)/", homophone: "塞普腾波", meaning: "九月", sentence: "September school.", translation: "九月开学。", homophoneSentence: "塞普腾波斯古." },
    { word: "October", phonetic: "/ɒkˈtəʊbə(r)/", homophone: "奥克托波", meaning: "十月", sentence: "October leaves.", translation: "十月落叶。", homophoneSentence: "奥克托波利夫兹." },
    { word: "November", phonetic: "/nəʊˈvembə(r)/", homophone: "诺文波", meaning: "十一月", sentence: "November rain.", translation: "十一月雨。", homophoneSentence: "诺文波瑞恩." },
    { word: "December", phonetic: "/dɪˈsembə(r)/", homophone: "迪森波", meaning: "十二月", sentence: "December snow.", translation: "十二月雪。", homophoneSentence: "迪森波斯诺." },
    { word: "Spring", phonetic: "/sprɪŋ/", homophone: "斯普林", meaning: "春天", sentence: "Happy spring!", translation: "春天快乐！", homophoneSentence: "嗨皮斯普林!" },
    { word: "Summer", phonetic: "/ˈsʌmə(r)/", homophone: "萨默", meaning: "夏天", sentence: "Enjoy summer!", translation: "享受夏天！", homophoneSentence: "因照伊萨默!" },
    { word: "Autumn", phonetic: "/ˈɔːtəm/", homophone: "奥腾", meaning: "秋天", sentence: "Beautiful autumn.", translation: "美丽的秋天。", homophoneSentence: "比欧特夫欧奥腾." },
    { word: "Winter", phonetic: "/ˈwɪntə(r)/", homophone: "温特", meaning: "冬天", sentence: "Cold winter.", translation: "寒冷的冬天。", homophoneSentence: "扣德温特." },
    { word: "Sunny", phonetic: "/ˈsʌni/", homophone: "萨尼", meaning: "晴朗的", sentence: "It's sunny today.", translation: "今天晴朗。", homophoneSentence: "伊茨萨尼特戴." },
    { word: "Rainy", phonetic: "/ˈreɪni/", homophone: "瑞尼", meaning: "下雨的", sentence: "It's rainy today.", translation: "今天下雨。", homophoneSentence: "伊茨瑞尼特戴." },
    { word: "Cloudy", phonetic: "/ˈklaʊdi/", homophone: "克劳迪", meaning: "多云的", sentence: "It's cloudy today.", translation: "今天多云。", homophoneSentence: "伊茨克劳迪特戴." },
    { word: "Snowy", phonetic: "/ˈsnəʊi/", homophone: "斯诺伊", meaning: "下雪的", sentence: "It's snowy today.", translation: "今天下雪。", homophoneSentence: "伊茨斯诺伊特戴." },
    { word: "Windy", phonetic: "/ˈwɪndi/", homophone: "温迪", meaning: "有风的", sentence: "It's windy today.", translation: "今天有风。", homophoneSentence: "伊茨温迪特戴." },
    { word: "Hot", phonetic: "/hɒt/", homophone: "豪特", meaning: "热的", sentence: "It's so hot!", translation: "太热了！", homophoneSentence: "伊茨搜豪特!" },
    { word: "Cold", phonetic: "/kəʊld/", homophone: "扣德", meaning: "冷的", sentence: "It's so cold!", translation: "太冷了！", homophoneSentence: "伊茨搜扣德!" },
    { word: "Warm", phonetic: "/wɔːm/", homophone: "沃姆", meaning: "温暖的", sentence: "It's warm today.", translation: "今天很温暖。", homophoneSentence: "伊茨沃姆特戴." },
    { word: "Cool", phonetic: "/kuːl/", homophone: "库尔", meaning: "凉爽的", sentence: "It's cool today.", translation: "今天很凉爽。", homophoneSentence: "伊茨库尔特戴." },
    { word: "Birthday", phonetic: "/ˈbɜːθdeɪ/", homophone: "波斯戴", meaning: "生日", sentence: "Happy birthday!", translation: "生日快乐！", homophoneSentence: "嗨皮波斯戴!" },
    { word: "Holiday", phonetic: "/ˈhɒlədeɪ/", homophone: "豪利戴", meaning: "假期", sentence: "Happy holiday!", translation: "假期快乐！", homophoneSentence: "嗨皮豪利戴!" },
    { word: "Vacation", phonetic: "/vəˈkeɪʃn/", homophone: "沃凯申", meaning: "假期", sentence: "Enjoy your vacation!", translation: "享受你的假期！", homophoneSentence: "因照伊油儿沃凯申!" },
    { word: "Welcome", phonetic: "/ˈwelkəm/", homophone: "威尔康", meaning: "欢迎", sentence: "Welcome home!", translation: "欢迎回家！", homophoneSentence: "威尔康厚姆!" },
    { word: "Farewell", phonetic: "/ˌfeəˈwel/", homophone: "夫尔威尔", meaning: "告别", sentence: "Farewell, my friend!", translation: "再见，我的朋友！", homophoneSentence: "夫尔威尔麦夫瑞恩德!" },
    { word: "Greetings", phonetic: "/ɡrɪˈtiːŋz/", homophone: "格瑞听兹", meaning: "问候", sentence: "Season's greetings!", translation: "节日问候！", homophoneSentence: "西曾兹格瑞听兹!" },
    { word: "Hey", phonetic: "/heɪ/", homophone: "嘿", meaning: "嘿", sentence: "Hey, how are you?", translation: "嘿，你好吗？", homophoneSentence: "嘿好啊油?" },
    { word: "Yo", phonetic: "/jəʊ/", homophone: "哟", meaning: "哟", sentence: "Yo! What's up?", translation: "哟！怎么了？", homophoneSentence: "哟沃特阿普?" },
    { word: "Howdy", phonetic: "/ˈhaʊdi/", homophone: "豪迪", meaning: "你好", sentence: "Howdy partner!", translation: "你好伙伴！", homophoneSentence: "豪迪帕特纳!" },
    { word: "Cheers", phonetic: "/tʃɪəz/", homophone: "切尔斯", meaning: "干杯", sentence: "Cheers to us!", translation: "为我们干杯！", homophoneSentence: "切尔斯土阿斯!" },
    { word: "Take care", phonetic: "/teɪk keə/", homophone: "忒克凯尔", meaning: "保重", sentence: "Take care!", translation: "保重！", homophoneSentence: "忒克凯尔!" },
    
    // 祝福与祝愿 (51-100)
    { word: "Congratulations", phonetic: "/kənˌɡrætʃuˈleɪʃnz/", homophone: "康格雷丘雷申兹", meaning: "恭喜", sentence: "Congratulations on your success!", translation: "恭喜你的成功！", homophoneSentence: "康格雷丘雷申兹昂油儿色克塞斯!" },
    { word: "Best wishes", phonetic: "/best ˈwɪʃɪz/", homophone: "百斯特维希兹", meaning: "最美好的祝愿", sentence: "Best wishes for you!", translation: "给你最美好的祝愿！", homophoneSentence: "百斯特维希兹for油!" },
    { word: "Good luck", phonetic: "/ɡʊd lʌk/", homophone: "古德拉科", meaning: "祝你好运", sentence: "Good luck!", translation: "祝你好运！", homophoneSentence: "古德拉科!" },
    { word: "Get well", phonetic: "/ɡet wel/", homophone: "盖特威尔", meaning: "早日康复", sentence: "Get well soon!", translation: "早日康复！", homophoneSentence: "盖特威尔苏恩!" },
    { word: "Bless you", phonetic: "/bles juː/", homophone: "布莱斯优", meaning: "保佑你", sentence: "Bless you!", translation: "保佑你！", homophoneSentence: "布莱斯优!" },
    { word: "Have fun", phonetic: "/hæv fʌn/", homophone: "海夫范", meaning: "玩得开心", sentence: "Have fun!", translation: "玩得开心！", homophoneSentence: "海夫范!" },
    { word: "Enjoy", phonetic: "/ɪnˈdʒɔɪ/", homophone: "因照伊", meaning: "享受", sentence: "Enjoy your meal!", translation: "享受你的餐食！", homophoneSentence: "因照伊油儿米尔!" },
    { word: "Safe trip", phonetic: "/seɪf trɪp/", homophone: "塞夫纯普", meaning: "一路平安", sentence: "Have a safe trip!", translation: "一路平安！", homophoneSentence: "海夫啊塞夫纯普!" },
    { word: "Success", phonetic: "/səkˈses/", homophone: "色克塞斯", meaning: "成功", sentence: "Wish you success!", translation: "祝你成功！", homophoneSentence: "维什油色克塞斯!" },
    { word: "Happiness", phonetic: "/ˈhæpinəs/", homophone: "嗨皮内斯", meaning: "幸福", sentence: "Wish you happiness!", translation: "祝你幸福！", homophoneSentence: "维什油嗨皮内斯!" },
    { word: "Health", phonetic: "/helθ/", homophone: "海尔斯", meaning: "健康", sentence: "Wish you good health!", translation: "祝你健康！", homophoneSentence: "维什油古德海尔斯!" },
    { word: "Wealth", phonetic: "/welθ/", homophone: "威尔斯", meaning: "财富", sentence: "Wish you wealth!", translation: "祝你发财！", homophoneSentence: "维什油威尔斯!" },
    { word: "Prosperity", phonetic: "/prɒˈsperəti/", homophone: "普罗斯佩瑞提", meaning: "繁荣", sentence: "Wish you prosperity!", translation: "祝你繁荣！", homophoneSentence: "维什油普罗斯佩瑞提!" },
    { word: "Long life", phonetic: "/lɒŋ laɪf/", homophone: "朗来夫", meaning: "长寿", sentence: "Wish you long life!", translation: "祝你长寿！", homophoneSentence: "维什油朗来夫!" },
    { word: "Peace", phonetic: "/piːs/", homophone: "皮斯", meaning: "和平", sentence: "Wish you peace!", translation: "祝你平安！", homophoneSentence: "维什油皮斯!" },
    { word: "Joy", phonetic: "/dʒɔɪ/", homophone: "卓伊", meaning: "欢乐", sentence: "Wish you joy!", translation: "祝你欢乐！", homophoneSentence: "维什油卓伊!" },
    { word: "Love", phonetic: "/lʌv/", homophone: "拉夫", meaning: "爱", sentence: "Wish you love!", translation: "祝你拥有爱！", homophoneSentence: "维什油拉夫!" },
    { word: "Harmony", phonetic: "/ˈhɑːməni/", homophone: "哈莫尼", meaning: "和谐", sentence: "Wish you harmony!", translation: "祝你和谐！", homophoneSentence: "维什油哈莫尼!" },
    { word: "Fortune", phonetic: "/ˈfɔːtʃuːn/", homophone: "佛纯", meaning: "好运", sentence: "Wish you good fortune!", translation: "祝你好运！", homophoneSentence: "维什油古德佛纯!" },
    { word: "Victory", phonetic: "/ˈvɪktəri/", homophone: "维克托瑞", meaning: "胜利", sentence: "Wish you victory!", translation: "祝你胜利！", homophoneSentence: "维什油维克托瑞!" },
    { word: "Strength", phonetic: "/streŋθ/", homophone: "斯纯斯", meaning: "力量", sentence: "Wish you strength!", translation: "祝你力量！", homophoneSentence: "维什油斯纯斯!" },
    { word: "Courage", phonetic: "/ˈkʌrɪdʒ/", homophone: "卡瑞吉", meaning: "勇气", sentence: "Wish you courage!", translation: "祝你勇气！", homophoneSentence: "维什油卡瑞吉!" },
    { word: "Wisdom", phonetic: "/ˈwɪzdəm/", homophone: "维兹德姆", meaning: "智慧", sentence: "Wish you wisdom!", translation: "祝你智慧！", homophoneSentence: "维什油维兹德姆!" },
    { word: "Patience", phonetic: "/ˈpeɪʃns/", homophone: "佩申斯", meaning: "耐心", sentence: "Wish you patience!", translation: "祝你耐心！", homophoneSentence: "维什油佩申斯!" },
    { word: "Kindness", phonetic: "/ˈkaɪndnəs/", homophone: "凯恩德内斯", meaning: "善良", sentence: "Wish you kindness!", translation: "祝你善良！", homophoneSentence: "维什油凯恩德内斯!" },
    { word: "Friendship", phonetic: "/ˈfrendʃɪp/", homophone: "夫瑞恩德什普", meaning: "友谊", sentence: "Wish you friendship!", translation: "祝你友谊！", homophoneSentence: "维什油夫瑞恩德什普!" },
    { word: "Unity", phonetic: "/ˈjuːnəti/", homophone: "尤尼提", meaning: "团结", sentence: "Wish you unity!", translation: "祝你团结！", homophoneSentence: "维什油尤尼提!" },
    { word: "Hope", phonetic: "/həʊp/", homophone: "厚普", meaning: "希望", sentence: "Never lose hope!", translation: "永远不要失去希望！", homophoneSentence: "奈弗洛斯拉夫厚普!" },
    { word: "Dream", phonetic: "/driːm/", homophone: "追姆", meaning: "梦想", sentence: "Follow your dream!", translation: "追随你的梦想！", homophoneSentence: "佛洛油儿追姆!" },
    { word: "Future", phonetic: "/ˈfjuːtʃə(r)/", homophone: "夫优彻", meaning: "未来", sentence: "Bright future ahead!", translation: "光明的未来在前方！", homophoneSentence: "布来特夫优彻阿海德!" },
    { word: "Journey", phonetic: "/ˈdʒɜːni/", homophone: "卓尼", meaning: "旅程", sentence: "Safe journey!", translation: "一路平安！", homophoneSentence: "塞夫卓尼!" },
    { word: "Adventure", phonetic: "/ədˈventʃə(r)/", homophone: "阿德文彻", meaning: "冒险", sentence: "Enjoy your adventure!", translation: "享受你的冒险！", homophoneSentence: "因照伊油儿阿德文彻!" },
    { word: "Discovery", phonetic: "/dɪˈskʌvəri/", homophone: "迪斯卡夫瑞", meaning: "发现", sentence: "Happy discovery!", translation: "愉快的发现！", homophoneSentence: "嗨皮迪斯卡夫瑞!" },
    { word: "Achievement", phonetic: "/əˈtʃiːvmənt/", homophone: "阿奇夫门特", meaning: "成就", sentence: "Great achievement!", translation: "伟大的成就！", homophoneSentence: "格瑞特阿奇夫门特!" },
    { word: "Progress", phonetic: "/ˈprəʊɡres/", homophone: "普柔格瑞斯", meaning: "进步", sentence: "Keep making progress!", translation: "继续进步！", homophoneSentence: "吉普梅克英普柔格瑞斯!" },
    { word: "Growth", phonetic: "/ɡrəʊθ/", homophone: "格柔斯", meaning: "成长", sentence: "Continuous growth!", translation: "持续成长！", homophoneSentence: "康提牛斯格柔斯!" },
    { word: "Learning", phonetic: "/ˈlɜːnɪŋ/", homophone: "勒宁", meaning: "学习", sentence: "Happy learning!", translation: "快乐学习！", homophoneSentence: "嗨皮勒宁!" },
    { word: "Knowledge", phonetic: "/ˈnɒlɪdʒ/", homophone: "诺利吉", meaning: "知识", sentence: "Gain knowledge!", translation: "获取知识！", homophoneSentence: "盖恩诺利吉!" },
    { word: "Understanding", phonetic: "/ˌʌndəˈstændɪŋ/", homophone: "昂德斯丹丁", meaning: "理解", sentence: "Mutual understanding!", translation: "相互理解！", homophoneSentence: "缪求昂德斯丹丁!" },
    { word: "Cooperation", phonetic: "/kəʊˌɒpəˈreɪʃn/", homophone: "勾奥佩雷申", meaning: "合作", sentence: "Good cooperation!", translation: "良好的合作！", homophoneSentence: "古德勾奥佩雷申!" },
    { word: "Teamwork", phonetic: "/ˈtiːmwɜːk/", homophone: "提姆沃克", meaning: "团队合作", sentence: "Great teamwork!", translation: "很棒的团队合作！", homophoneSentence: "格瑞特提姆沃克!" },
    { word: "Support", phonetic: "/səˈpɔːt/", homophone: "瑟坡特", meaning: "支持", sentence: "Thank you for your support!", translation: "谢谢你的支持！", homophoneSentence: "三克油for油儿瑟坡特!" },
    { word: "Encouragement", phonetic: "/ɪnˈkʌrɪdʒmənt/", homophone: "因卡瑞吉门特", meaning: "鼓励", sentence: "Your encouragement means a lot!", translation: "你的鼓励意义重大！", homophoneSentence: "油儿因卡瑞吉门特敏斯啊洛特!" },
    { word: "Inspiration", phonetic: "/ˌɪnspəˈreɪʃn/", homophone: "因斯佩雷申", meaning: "灵感", sentence: "You are my inspiration!", translation: "你是我的灵感！", homophoneSentence: "油啊麦因斯佩雷申!" },
    { word: "Motivation", phonetic: "/ˌməʊtɪˈveɪʃn/", homophone: "莫提维雷申", meaning: "动力", sentence: "Keep your motivation high!", translation: "保持你的动力！", homophoneSentence: "吉普油儿莫提维雷申嗨!" },
    { word: "Confidence", phonetic: "/ˈkɒnfɪdəns/", homophone: "康菲登斯", meaning: "信心", sentence: "Have confidence!", translation: "要有信心！", homophoneSentence: "海夫康菲登斯!" },
    { word: "Determination", phonetic: "/dɪˌtɜːmɪˈneɪʃn/", homophone: "迪特米内申", meaning: "决心", sentence: "Show your determination!", translation: "展示你的决心！", homophoneSentence: "秀油儿迪特米内申!" },
    { word: "Dedication", phonetic: "/ˌdedɪˈkeɪʃn/", homophone: "戴迪克雷申", meaning: "奉献", sentence: "Your dedication is admirable!", translation: "你的奉献令人钦佩！", homophoneSentence: "油儿戴迪克雷申is艾德米瑞波欧!" },
    { word: "Commitment", phonetic: "/kəˈmɪtmənt/", homophone: "克米特门特", meaning: "承诺", sentence: "Keep your commitment!", translation: "信守你的承诺！", homophoneSentence: "吉普油儿克米特门特!" },
    { word: "Loyalty", phonetic: "/ˈlɔɪəlti/", homophone: "洛亚尔提", meaning: "忠诚", sentence: "Your loyalty is appreciated!", translation: "感谢你的忠诚！", homophoneSentence: "油儿洛亚尔提is阿普瑞希埃提德!" },
    { word: "Trust", phonetic: "/trʌst/", homophone: "特拉斯特", meaning: "信任", sentence: "Trust is important!", translation: "信任很重要！", homophoneSentence: "特拉斯特is因坡腾特!" },
    { word: "Respect", phonetic: "/rɪˈspekt/", homophone: "瑞斯佩克特", meaning: "尊重", sentence: "Show respect!", translation: "表示尊重！", homophoneSentence: "秀瑞斯佩克特!" },
    { word: "Honesty", phonetic: "/ˈɒnəsti/", homophone: "奥内斯提", meaning: "诚实", sentence: "Honesty is the best policy!", translation: "诚实是最好的策略！", homophoneSentence: "奥内斯提is则百斯特波利西!" },
    
    // 日常表达 (101-150)
    { word: "Absolutely", phonetic: "/ˈæbsəluːtli/", homophone: "艾布索鲁特里", meaning: "绝对", sentence: "Absolutely! I agree!", translation: "绝对！我同意！", homophoneSentence: "艾布索鲁特里爱阿格瑞!" },
    { word: "Definitely", phonetic: "/ˈdefɪnətli/", homophone: "戴菲尼特里", meaning: "肯定", sentence: "Definitely! No doubt!", translation: "肯定！毫无疑问！", homophoneSentence: "戴菲尼特里诺道特!" },
    { word: "Certainly", phonetic: "/ˈsɜːtnli/", homophone: "色腾利", meaning: "当然", sentence: "Certainly! My pleasure!", translation: "当然！我的荣幸！", homophoneSentence: "色腾利麦普莱舍!" },
    { word: "Exactly", phonetic: "/ɪɡˈzæktli/", homophone: "伊格扎克特里", meaning: "正是", sentence: "Exactly! You are right!", translation: "正是！你说得对！", homophoneSentence: "伊格扎克特里油啊来特!" },
    { word: "Precisely", phonetic: "/prɪˈsaɪsli/", homophone: "普瑞赛斯利", meaning: "精确地", sentence: "Precisely! Well said!", translation: "精确地！说得好！", homophoneSentence: "普瑞赛斯利威尔塞德!" },
    { word: "Indeed", phonetic: "/ɪnˈdiːd/", homophone: "因迪德", meaning: "确实", sentence: "Indeed! That's true!", translation: "确实！那是真的！", homophoneSentence: "因迪德戴茨纯!" },
    { word: "Exactly right", phonetic: "/ɪɡˈzæktli raɪt/", homophone: "伊格扎克特里来特", meaning: "完全正确", sentence: "Exactly right! Perfect!", translation: "完全正确！完美！", homophoneSentence: "伊格扎克特里来特坡佛费克特!" },
    { word: "You bet", phonetic: "/juː bet/", homophone: "优百特", meaning: "当然", sentence: "You bet! Anytime!", translation: "当然！随时！", homophoneSentence: "优百特安尼泰姆!" },
    { word: "No problem", phonetic: "/nəʊ ˈprɒbləm/", homophone: "诺普罗布勒姆", meaning: "没问题", sentence: "No problem! Happy to help!", translation: "没问题！乐意帮忙！", homophoneSentence: "诺普罗布勒姆嗨皮to海尔普!" },
    { word: "My pleasure", phonetic: "/maɪ ˈpleʒə(r)/", homophone: "麦普莱舍", meaning: "我的荣幸", sentence: "My pleasure! Anytime!", translation: "我的荣幸！随时！", homophoneSentence: "麦普莱舍安尼泰姆!" },
    { word: "You're welcome", phonetic: "/jɔː(r) ˈwelkəm/", homophone: "优儿威尔康", meaning: "不客气", sentence: "You're welcome! Don't mention it!", translation: "不客气！别客气！", homophoneSentence: "优儿威尔康东特门申伊特!" },
    { word: "Don't mention it", phonetic: "/dəʊnt ˈmenʃn ɪt/", homophone: "东特门申伊特", meaning: "别客气", sentence: "Don't mention it! Glad to help!", translation: "别客气！很高兴帮忙！", homophoneSentence: "东特门申伊特格拉德to海尔普!" },
    { word: "Forget it", phonetic: "/fəˈɡet ɪt/", homophone: "夫盖特伊特", meaning: "算了", sentence: "Forget it! No worries!", translation: "算了！别担心！", homophoneSentence: "夫盖特伊特诺沃瑞兹!" },
    { word: "Never mind", phonetic: "/ˈnevə(r) maɪnd/", homophone: "奈夫曼德", meaning: "没关系", sentence: "Never mind! It's okay!", translation: "没关系！没事的！", homophoneSentence: "奈夫曼德伊茨欧凯!" },
    { word: "It's okay", phonetic: "/ɪts əʊˈkeɪ/", homophone: "伊茨欧凯", meaning: "没事", sentence: "It's okay! Don't worry!", translation: "没事！别担心！", homophoneSentence: "伊茨欧凯东特沃瑞!" },
    { word: "No worries", phonetic: "/nəʊ ˈwʌriz/", homophone: "诺沃瑞兹", meaning: "别担心", sentence: "No worries! All good!", translation: "别担心！一切都好！", homophoneSentence: "诺沃瑞兹奥古德!" },
    { word: "All good", phonetic: "/ɔːl ɡʊd/", homophone: "奥古德", meaning: "一切都好", sentence: "All good! No problem!", translation: "一切都好！没问题！", homophoneSentence: "奥古德诺普罗布勒姆!" },
    { word: "Sounds good", phonetic: "/saʊndz ɡʊd/", homophone: "桑兹古德", meaning: "听起来不错", sentence: "Sounds good! Let's do it!", translation: "听起来不错！我们开始吧！", homophoneSentence: "桑兹古德来茨度伊特!" },
    { word: "That's great", phonetic: "/ðæts ɡreɪt/", homophone: "戴茨格瑞特", meaning: "太好了", sentence: "That's great! Wonderful!", translation: "太好了！太棒了！", homophoneSentence: "戴茨格瑞特旺德夫欧!" },
    { word: "Awesome", phonetic: "/ˈɔːsəm/", homophone: "奥瑟姆", meaning: "太棒了", sentence: "Awesome! Fantastic!", translation: "太棒了！极好的！", homophoneSentence: "奥瑟姆范泰斯提克!" },
    { word: "Fantastic", phonetic: "/fænˈtæstɪk/", homophone: "范泰斯提克", meaning: "极好的", sentence: "Fantastic! Well done!", translation: "极好的！做得好！", homophoneSentence: "范泰斯提克威尔丹!" },
    { word: "Wonderful", phonetic: "/ˈwʌndəfl/", homophone: "旺德夫欧", meaning: "精彩的", sentence: "Wonderful! Amazing!", translation: "精彩的！令人惊叹的！", homophoneSentence: "旺德夫欧阿梅兹英!" },
    { word: "Amazing", phonetic: "/əˈmeɪzɪŋ/", homophone: "阿梅兹英", meaning: "惊人的", sentence: "Amazing! Incredible!", translation: "惊人的！不可思议的！", homophoneSentence: "阿梅兹英因克瑞德波欧!" },
    { word: "Incredible", phonetic: "/ɪnˈkredəbl/", homophone: "因克瑞德波欧", meaning: "不可思议的", sentence: "Incredible! Unbelievable!", translation: "不可思议的！难以置信！", homophoneSentence: "因克瑞德波欧昂比利夫波欧!" },
    { word: "Unbelievable", phonetic: "/ˌʌnbɪˈliːvəbl/", homophone: "昂比利夫波欧", meaning: "难以置信的", sentence: "Unbelievable! Mind-blowing!", translation: "难以置信的！令人震惊的！", homophoneSentence: "昂比利夫波欧迈恩德布洛英!" },
    { word: "Phenomenal", phonetic: "/fəˈnɒmɪnl/", homophone: "夫诺米诺", meaning: "非凡的", sentence: "Phenomenal! Outstanding!", translation: "非凡的！杰出的！", homophoneSentence: "夫诺米诺奥特斯丹丁!" },
    { word: "Outstanding", phonetic: "/aʊtˈstændɪŋ/", homophone: "奥特斯丹丁", meaning: "杰出的", sentence: "Outstanding! Exceptional!", translation: "杰出的！卓越的！", homophoneSentence: "奥特斯丹丁伊克塞普申诺!" },
    { word: "Excellent", phonetic: "/ˈeksələnt/", homophone: "艾克瑟伦特", meaning: "极好的", sentence: "Excellent! Perfect!", translation: "极好的！完美的！", homophoneSentence: "艾克瑟伦特坡佛费克特!" },
    { word: "Perfect", phonetic: "/ˈpɜːfɪkt/", homophone: "坡佛费克特", meaning: "完美的", sentence: "Perfect! Couldn't be better!", translation: "完美的！不能再好了！", homophoneSentence: "坡佛费克特库登特比百特!" },
    { word: "Brilliant", phonetic: "/ˈbrɪliənt/", homophone: "布里连特", meaning: "杰出的", sentence: "Brilliant! Genius!", translation: "杰出的！天才！", homophoneSentence: "布里连特吉尼尔斯!" },
    { word: "Superb", phonetic: "/suːˈpɜːb/", homophone: "苏坡布", meaning: "卓越的", sentence: "Superb! First class!", translation: "卓越的！一流的！", homophoneSentence: "苏坡布佛斯特克拉斯!" },
    { word: "Marvelous", phonetic: "/ˈmɑːvələs/", homophone: "马夫勒斯", meaning: "极好的", sentence: "Marvelous! Magnificent!", translation: "极好的！壮丽的！", homophoneSentence: "马夫勒斯马格尼费森特!" },
    { word: "Terrific", phonetic: "/təˈrɪfɪk/", homophone: "特瑞费克", meaning: "极好的", sentence: "Terrific! Impressive!", translation: "极好的！令人印象深刻！", homophoneSentence: "特瑞费克因普热斯夫!" },
    { word: "Splendid", phonetic: "/ˈsplendɪd/", homophone: "斯普伦迪德", meaning: "极好的", sentence: "Splendid! Glorious!", translation: "极好的！光荣的！", homophoneSentence: "斯普伦迪德格洛瑞尔斯!" },
    { word: "Fabulous", phonetic: "/ˈfæbjələs/", homophone: "法丘勒斯", meaning: "极好的", sentence: "Fabulous! Spectacular!", translation: "极好的！壮观的！", homophoneSentence: "法丘勒斯斯佩克泰丘勒!" },
    { word: "Impressive", phonetic: "/ɪmˈpresɪv/", homophone: "因普热斯夫", meaning: "令人印象深刻的", sentence: "Impressive! Remarkable!", translation: "令人印象深刻的！非凡的！", homophoneSentence: "因普热斯夫瑞马克波欧!" },
    { word: "Remarkable", phonetic: "/rɪˈmɑːkəbl/", homophone: "瑞马克波欧", meaning: "非凡的", sentence: "Remarkable! Extraordinary!", translation: "非凡的！非凡的！", homophoneSentence: "瑞马克波欧伊克斯特奥登瑞!" },
    { word: "Extraordinary", phonetic: "/ɪkˈstrɔːdnri/", homophone: "伊克斯特奥登瑞", meaning: "非凡的", sentence: "Extraordinary! Exceptional!", translation: "非凡的！卓越的！", homophoneSentence: "伊克斯特奥登瑞伊克塞普申诺!" },
    { word: "Exceptional", phonetic: "/ɪkˈsepʃənl/", homophone: "伊克塞普申诺", meaning: "卓越的", sentence: "Exceptional! World-class!", translation: "卓越的！世界级的！", homophoneSentence: "伊克塞普申诺沃德克拉斯!" },
    { word: "Magnificent", phonetic: "/mæɡˈnɪfɪsnt/", homophone: "马格尼费森特", meaning: "壮丽的", sentence: "Magnificent! Grand!", translation: "壮丽的！宏伟的！", homophoneSentence: "马格尼费森特格兰德!" },
    { word: "Spectacular", phonetic: "/spekˈtækjələ(r)/", homophone: "斯佩克泰丘勒", meaning: "壮观的", sentence: "Spectacular! Breathtaking!", translation: "壮观的！令人惊叹的！", homophoneSentence: "斯佩克泰丘勒布雷斯泰克英!" },
    { word: "Stunning", phonetic: "/ˈstʌnɪŋ/", homophone: "斯丹宁", meaning: "令人惊叹的", sentence: "Stunning! Jaw-dropping!", translation: "令人惊叹的！令人瞠目结舌的！", homophoneSentence: "斯丹宁卓德洛平!" },
    { word: "Breathtaking", phonetic: "/ˈbreθteɪkɪŋ/", homophone: "布雷斯泰克英", meaning: "令人惊叹的", sentence: "Breathtaking! Awe-inspiring!", translation: "令人惊叹的！令人敬畏的！", homophoneSentence: "布雷斯泰克英奥因斯派瑞英!" },
    { word: "Awe-inspiring", phonetic: "/ˈɔː ɪnˌspaɪərɪŋ/", homophone: "奥因斯派瑞英", meaning: "令人敬畏的", sentence: "Awe-inspiring! Majestic!", translation: "令人敬畏的！雄伟的！", homophoneSentence: "奥因斯派瑞英马杰斯提克!" },
    { word: "Majestic", phonetic: "/məˈdʒestɪk/", homophone: "马杰斯提克", meaning: "雄伟的", sentence: "Majestic! Grandiose!", translation: "雄伟的！宏伟的！", homophoneSentence: "马杰斯提克格兰迪欧斯!" },
    { word: "Grandiose", phonetic: "/ˈɡrændiəʊs/", homophone: "格兰迪欧斯", meaning: "宏伟的", sentence: "Grandiose! Epic!", translation: "宏伟的！史诗般的！", homophoneSentence: "格兰迪欧斯艾皮克!" },
    { word: "Epic", phonetic: "/ˈepɪk/", homophone: "艾皮克", meaning: "史诗般的", sentence: "Epic! Legendary!", translation: "史诗般的！传奇的！", homophoneSentence: "艾皮克莱真德瑞!" },
    { word: "Legendary", phonetic: "/ˈledʒəndri/", homophone: "莱真德瑞", meaning: "传奇的", sentence: "Legendary! Iconic!", translation: "传奇的！标志性的！", homophoneSentence: "莱真德瑞艾康尼克!" },
    { word: "Iconic", phonetic: "/aɪˈkɒnɪk/", homophone: "艾康尼克", meaning: "标志性的", sentence: "Iconic! Timeless!", translation: "标志性的！永恒的！", homophoneSentence: "艾康尼克泰姆利斯!" },
    { word: "Timeless", phonetic: "/ˈtaɪmləs/", homophone: "泰姆利斯", meaning: "永恒的", sentence: "Timeless! Classic!", translation: "永恒的！经典的！", homophoneSentence: "泰姆利斯克拉斯伊克!" },
    { word: "Classic", phonetic: "/ˈklæsɪk/", homophone: "克拉斯伊克", meaning: "经典的", sentence: "Classic! Elegant!", translation: "经典的！优雅的！", homophoneSentence: "克拉斯伊克艾利根特!" },
    { word: "Elegant", phonetic: "/ˈelɪɡənt/", homophone: "艾利根特", meaning: "优雅的", sentence: "Elegant! Refined!", translation: "优雅的！精致的！", homophoneSentence: "艾利根特里凡德!" },
    { word: "Refined", phonetic: "/rɪˈfaɪnd/", homophone: "里凡德", meaning: "精致的", sentence: "Refined! Sophisticated!", translation: "精致的！复杂的！", homophoneSentence: "里凡德索菲斯提凯特德!" },
    { word: "Sophisticated", phonetic: "/səˈfɪstɪkeɪtɪd/", homophone: "索菲斯提凯特德", meaning: "复杂的", sentence: "Sophisticated! Polished!", translation: "复杂的！优雅的！", homophoneSentence: "索菲斯提凯特德波利什特!" },
    { word: "Polished", phonetic: "/ˈpɒlɪʃt/", homophone: "波利什特", meaning: "优雅的", sentence: "Polished! Professional!", translation: "优雅的！专业的！", homophoneSentence: "波利什特普若费申诺!" },
    { word: "Professional", phonetic: "/prəˈfeʃənl/", homophone: "普若费申诺", meaning: "专业的", sentence: "Professional! Expert!", translation: "专业的！专家的！", homophoneSentence: "普若费申诺艾克斯坡特!" },
    { word: "Expert", phonetic: "/ˈekspɜːt/", homophone: "艾克斯坡特", meaning: "专家的", sentence: "Expert! Masterful!", translation: "专家的！精湛的！", homophoneSentence: "艾克斯坡特马斯特夫欧!" },
    { word: "Masterful", phonetic: "/ˈmɑːstəfl/", homophone: "马斯特夫欧", meaning: "精湛的", sentence: "Masterful! Skillful!", translation: "精湛的！熟练的！", homophoneSentence: "马斯特夫欧斯ki夫欧!" },
    { word: "Skillful", phonetic: "/ˈskɪlfl/", homophone: "斯ki夫欧", meaning: "熟练的", sentence: "Skillful! Dexterous!", translation: "熟练的！灵巧的！", homophoneSentence: "斯ki夫欧戴克斯特勒斯!" },
    { word: "Dexterous", phonetic: "/ˈdekstrəs/", homophone: "戴克斯特勒斯", meaning: "灵巧的", sentence: "Dexterous! Nimble!", translation: "灵巧的！敏捷的！", homophoneSentence: "戴克斯特勒斯尼姆波欧!" },
    { word: "Nimble", phonetic: "/ˈnɪmbl/", homophone: "尼姆波欧", meaning: "敏捷的", sentence: "Nimble! Agile!", translation: "敏捷的！灵活的！", homophoneSentence: "尼姆波欧艾吉尔!" },
    { word: "Agile", phonetic: "/ˈædʒaɪl/", homophone: "艾吉尔", meaning: "灵活的", sentence: "Agile! Quick!", translation: "灵活的！快速的！", homophoneSentence: "艾吉尔奎克!" },
    { word: "Quick", phonetic: "/kwɪk/", homophone: "奎克", meaning: "快速的", sentence: "Quick! Swift!", translation: "快速的！迅速的！", homophoneSentence: "奎克斯威夫特!" },
    { word: "Swift", phonetic: "/swɪft/", homophone: "斯威夫特", meaning: "迅速的", sentence: "Swift! Rapid!", translation: "迅速的！快速的！", homophoneSentence: "斯威夫特拉皮德!" },
    { word: "Rapid", phonetic: "/ˈræpɪd/", homophone: "拉皮德", meaning: "快速的", sentence: "Rapid! Speedy!", translation: "快速的！迅速的！", homophoneSentence: "拉皮德斯皮迪!" },
    { word: "Speedy", phonetic: "/ˈspiːdi/", homophone: "斯皮迪", meaning: "迅速的", sentence: "Speedy! Fast!", translation: "迅速的！快的！", homophoneSentence: "斯皮迪法斯特!" },
    { word: "Fast", phonetic: "/fɑːst/", homophone: "法斯特", meaning: "快的", sentence: "Fast! Efficient!", translation: "快的！高效的！", homophoneSentence: "法斯特伊菲申特!" },
    { word: "Efficient", phonetic: "/ɪˈfɪʃnt/", homophone: "伊菲申特", meaning: "高效的", sentence: "Efficient! Productive!", translation: "高效的！富有成效的！", homophoneSentence: "伊菲申特普若达克提夫!" },
    { word: "Productive", phonetic: "/prəˈdʌktɪv/", homophone: "普若达克提夫", meaning: "富有成效的", sentence: "Productive! Fruitful!", translation: "富有成效的！硕果累累的！", homophoneSentence: "普若达克提夫夫鲁特夫欧!" },
    { word: "Fruitful", phonetic: "/ˈfruːtfl/", homophone: "夫鲁特夫欧", meaning: "硕果累累的", sentence: "Fruitful! Rewarding!", translation: "硕果累累的！有益的！", homophoneSentence: "夫鲁特夫欧瑞沃丁!" },
    { word: "Rewarding", phonetic: "/rɪˈwɔːdɪŋ/", homophone: "瑞沃丁", meaning: "有益的", sentence: "Rewarding! Satisfying!", translation: "有益的！令人满意的！", homophoneSentence: "瑞沃丁萨提斯法艾英!" },
    { word: "Satisfying", phonetic: "/ˈsætɪsfaɪɪŋ/", homophone: "萨提斯法艾英", meaning: "令人满意的", sentence: "Satisfying! Fulfilling!", translation: "令人满意的！令人满足的！", homophoneSentence: "萨提斯法艾英夫欧菲林!" },
    { word: "Fulfilling", phonetic: "/fʊlˈfɪlɪŋ/", homophone: "夫欧菲林", meaning: "令人满足的", sentence: "Fulfilling! Enriching!", translation: "令人满足的！丰富的！", homophoneSentence: "夫欧菲林因瑞奇英!" },
    { word: "Enriching", phonetic: "/ɪnˈrɪtʃɪŋ/", homophone: "因瑞奇英", meaning: "丰富的", sentence: "Enriching! Uplifting!", translation: "丰富的！振奋人心的！", homophoneSentence: "因瑞奇英阿普利夫提英!" },
    { word: "Uplifting", phonetic: "/ʌpˈlɪftɪŋ/", homophone: "阿普利夫提英", meaning: "振奋人心的", sentence: "Uplifting! Heartwarming!", translation: "振奋人心的！暖心的！", homophoneSentence: "阿普利夫提英哈特沃明!" },
    { word: "Heartwarming", phonetic: "/ˈhɑːtwɔːmɪŋ/", homophone: "哈特沃明", meaning: "暖心的", sentence: "Heartwarming! Touching!", translation: "暖心的！感人的！", homophoneSentence: "哈特沃明塔奇英!" },
    { word: "Touching", phonetic: "/ˈtʌtʃɪŋ/", homophone: "塔奇英", meaning: "感人的", sentence: "Touching! Moving!", translation: "感人的！动人的！", homophoneSentence: "塔奇英穆文!" },
    { word: "Moving", phonetic: "/ˈmuːvɪŋ/", homophone: "穆文", meaning: "动人的", sentence: "Moving! Emotional!", translation: "动人的！情感丰富的！", homophoneSentence: "穆文伊莫申诺!" },
    { word: "Emotional", phonetic: "/ɪˈməʊʃənl/", homophone: "伊莫申诺", meaning: "情感丰富的", sentence: "Emotional! Passionate!", translation: "情感丰富的！热情的！", homophoneSentence: "伊莫申诺帕申内特!" },
    { word: "Passionate", phonetic: "/ˈpæʃənət/", homophone: "帕申内特", meaning: "热情的", sentence: "Passionate! Enthusiastic!", translation: "热情的！热情的！", homophoneSentence: "帕申内特因斯优西艾斯提克!" },
    { word: "Enthusiastic", phonetic: "/ɪnˌθjuːziˈæstɪk/", homophone: "因斯优西艾斯提克", meaning: "热情的", sentence: "Enthusiastic! Eager!", translation: "热情的！渴望的！", homophoneSentence: "因斯优西艾斯提克伊格!" },
    { word: "Eager", phonetic: "/ˈiːɡə(r)/", homophone: "伊格", meaning: "渴望的", sentence: "Eager! Keen!", translation: "渴望的！热心的！", homophoneSentence: "伊格kin!" },
    { word: "Keen", phonetic: "/kiːn/", homophone: "kin", meaning: "热心的", sentence: "Keen! Zealous!", translation: "热心的！热情的！", homophoneSentence: "kin泽勒斯!" },
    { word: "Zealous", phonetic: "/ˈzeləs/", homophone: "泽勒斯", meaning: "热情的", sentence: "Zealous! Fervent!", translation: "热情的！热烈的！", homophoneSentence: "泽勒斯佛文特!" },
    { word: "Fervent", phonetic: "/ˈfɜːvnt/", homophone: "佛文特", meaning: "热烈的", sentence: "Fervent! Ardent!", translation: "热烈的！热情的！", homophoneSentence: "佛文特阿登特!" },
    { word: "Ardent", phonetic: "/ˈɑːdnt/", homophone: "阿登特", meaning: "热情的", sentence: "Ardent! Devoted!", translation: "热情的！忠诚的！", homophoneSentence: "阿登特迪沃提德!" },
    { word: "Devoted", phonetic: "/dɪˈvəʊtɪd/", homophone: "迪沃提德", meaning: "忠诚的", sentence: "Devoted! Committed!", translation: "忠诚的！坚定的！", homophoneSentence: "迪沃提德克米提德!" },
    { word: "Committed", phonetic: "/kəˈmɪtɪd/", homophone: "克米提德", meaning: "坚定的", sentence: "Committed! Dedicated!", translation: "坚定的！专注的！", homophoneSentence: "克米提德戴迪克雷提德!" },
    { word: "Dedicated", phonetic: "/ˈdedɪkeɪtɪd/", homophone: "戴迪克雷提德", meaning: "专注的", sentence: "Dedicated! Determined!", translation: "专注的！坚决的！", homophoneSentence: "戴迪克雷提德迪特米恩德!" },
    { word: "Determined", phonetic: "/dɪˈtɜːmɪnd/", homophone: "迪特米恩德", meaning: "坚决的", sentence: "Determined! Resolute!", translation: "坚决的！果断的！", homophoneSentence: "迪特米恩德瑞索鲁特!" },
    { word: "Resolute", phonetic: "/ˈrezəluːt/", homophone: "瑞索鲁特", meaning: "果断的", sentence: "Resolute! Steadfast!", translation: "果断的！坚定的！", homophoneSentence: "瑞索鲁特斯泰德法斯特!" },
    { word: "Steadfast", phonetic: "/ˈstedfɑːst/", homophone: "斯泰德法斯特", meaning: "坚定的", sentence: "Steadfast! Unwavering!", translation: "坚定的！不动摇的！", homophoneSentence: "斯泰德法斯特昂威夫瑞英!" },
    { word: "Unwavering", phonetic: "/ʌnˈweɪvərɪŋ/", homophone: "昂威夫瑞英", meaning: "不动摇的", sentence: "Unwavering! Unyielding!", translation: "不动摇的！不屈的！", homophoneSentence: "昂威夫瑞英昂伊尔丁!" },
    { word: "Unyielding", phonetic: "/ʌnˈjiːldɪŋ/", homophone: "昂伊尔丁", meaning: "不屈的", sentence: "Unyielding! Indomitable!", translation: "不屈的！不可战胜的！", homophoneSentence: "昂伊尔丁因多米特波欧!" },
    { word: "Indomitable", phonetic: "/ɪnˈdɒmɪtəbl/", homophone: "因多米特波欧", meaning: "不可战胜的", sentence: "Indomitable! Invincible!", translation: "不可战胜的！无敌的！", homophoneSentence: "因多米特波欧因文西波欧!" },
    { word: "Invincible", phonetic: "/ɪnˈvɪnsəbl/", homophone: "因文西波欧", meaning: "无敌的", sentence: "Invincible! Unconquerable!", translation: "无敌的！不可征服的！", homophoneSentence: "因文西波欧昂康克瑞波欧!" },
    { word: "Unconquerable", phonetic: "/ʌnˈkɒŋkərəbl/", homophone: "昂康克瑞波欧", meaning: "不可征服的", sentence: "Unconquerable! Supreme!", translation: "不可征服的！至高无上的！", homophoneSentence: "昂康克瑞波欧苏普瑞姆!" },
    { word: "Supreme", phonetic: "/suːˈpriːm/", homophone: "苏普瑞姆", meaning: "至高无上的", sentence: "Supreme! Ultimate!", translation: "至高无上的！最终的！", homophoneSentence: "苏普瑞姆阿尔提米特!" },
    { word: "Ultimate", phonetic: "/ˈʌltɪmət/", homophone: "阿尔提米特", meaning: "最终的", sentence: "Ultimate! Paramount!", translation: "最终的！最重要的！", homophoneSentence: "阿尔提米特帕拉蒙特!" },
    { word: "Paramount", phonetic: "/ˈpærəmaʊnt/", homophone: "帕拉蒙特", meaning: "最重要的", sentence: "Paramount! Preeminent!", translation: "最重要的！卓越的！", homophoneSentence: "帕拉蒙特普瑞艾米内特!" },
    { word: "Preeminent", phonetic: "/priˈemɪnənt/", homophone: "普瑞艾米内特", meaning: "卓越的", sentence: "Preeminent! Distinguished!", translation: "卓越的！杰出的！", homophoneSentence: "普瑞艾米内特斯汀圭什特!" },
    { word: "Distinguished", phonetic: "/dɪˈstɪŋɡwɪʃt/", homophone: "斯汀圭什特", meaning: "杰出的", sentence: "Distinguished! Eminent!", translation: "杰出的！著名的！", homophoneSentence: "斯汀圭什特艾米内特!" },
    { word: "Eminent", phonetic: "/ˈemɪnənt/", homophone: "艾米内特", meaning: "著名的", sentence: "Eminent! Illustrious!", translation: "著名的！杰出的！", homophoneSentence: "艾米内伊利拉斯特瑞尔斯!" },
    { word: "Illustrious", phonetic: "/ɪˈlʌstriəs/", homophone: "伊利拉斯特瑞尔斯", meaning: "杰出的", sentence: "Illustrious! Renowned!", translation: "杰出的！著名的！", homophoneSentence: "伊利拉斯特瑞尔斯瑞诺恩德!" },
    { word: "Renowned", phonetic: "/rɪˈnaʊnd/", homophone: "瑞诺恩德", meaning: "著名的", sentence: "Renowned! Celebrated!", translation: "著名的！著名的！", homophoneSentence: "瑞诺恩德塞勒布雷提德!" },
    { word: "Celebrated", phonetic: "/ˈselɪbreɪtɪd/", homophone: "塞勒布雷提德", meaning: "著名的", sentence: "Celebrated! Acclaimed!", translation: "著名的！受赞誉的！", homophoneSentence: "塞勒布雷提德阿克莱姆德!" },
    { word: "Acclaimed", phonetic: "/əˈkleɪmd/", homophone: "阿克莱姆德", meaning: "受赞誉的", sentence: "Acclaimed! Honored!", translation: "受赞誉的！受尊敬的！", homophoneSentence: "阿克莱姆德奥诺德!" },
    { word: "Honored", phonetic: "/ˈɒnəd/", homophone: "奥诺德", meaning: "受尊敬的", sentence: "Honored! Respected!", translation: "受尊敬的！受尊重的！", homophoneSentence: "奥诺德瑞斯佩克提德!" },
    { word: "Respected", phonetic: "/rɪˈspektɪd/", homophone: "瑞斯佩克提德", meaning: "受尊重的", sentence: "Respected! Admired!", translation: "受尊重的！受钦佩的！", homophoneSentence: "瑞斯佩克提德阿德迈尔德!" },
    { word: "Admired", phonetic: "/ədˈmaɪəd/", homophone: "阿德迈尔德", meaning: "受钦佩的", sentence: "Admired! Revered!", translation: "受钦佩的！受尊敬的！", homophoneSentence: "阿德迈尔德瑞维尔德!" },
    { word: "Revered", phonetic: "/rɪˈvɪəd/", homophone: "瑞维尔德", meaning: "受尊敬的", sentence: "Revered! Venerated!", translation: "受尊敬的！受崇敬的！", homophoneSentence: "瑞维尔德维纳瑞提德!" },
    { word: "Venerated", phonetic: "/ˈvenəreɪtɪd/", homophone: "维纳瑞提德", meaning: "受崇敬的", sentence: "Venerated! Exalted!", translation: "受崇敬的！崇高的！", homophoneSentence: "维纳瑞提德伊格佐尔提德!" },
    { word: "Exalted", phonetic: "/ɪɡˈzɔːltɪd/", homophone: "伊格佐尔提德", meaning: "崇高的", sentence: "Exalted! Sublime!", translation: "崇高的！卓越的！", homophoneSentence: "伊格佐尔提德萨布来姆!" },
    { word: "Sublime", phonetic: "/səˈblaɪm/", homophone: "萨布来姆", meaning: "卓越的", sentence: "Sublime! Transcendent!", translation: "卓越的！超凡的！", homophoneSentence: "萨布来姆特兰森登特!" },
    { word: "Transcendent", phonetic: "/trænˈsendənt/", homophone: "特兰森登特", meaning: "超凡的", sentence: "Transcendent! Divine!", translation: "超凡的！神圣的！", homophoneSentence: "特兰森登特迪万!" },
    { word: "Divine", phonetic: "/dɪˈvaɪn/", homophone: "迪万", meaning: "神圣的", sentence: "Divine! Heavenly!", translation: "神圣的！天堂般的！", homophoneSentence: "迪万海文利!" },
    { word: "Heaven