#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更新交流对话单词到 word-data.js
"""

import re
import json

# 200个新的交流对话单词
new_words = [
    {"word": "Goodbye", "phonetic": "/ˌɡʊdˈbaɪ/", "homophone": "古德拜", "meaning": "再见", "sentence": "Goodbye for now!", "translation": "暂时再见！", "homophoneSentence": "古德拜佛闹!"},
    {"word": "Bye bye", "phonetic": "/ˈbaɪ ˈbaɪ/", "homophone": "拜拜", "meaning": "拜拜", "sentence": "Bye bye!", "translation": "拜拜！", "homophoneSentence": "拜拜!"},
    {"word": "Catch you later", "phonetic": "/kætʃ juː ˈleɪtə/", "homophone": "凯奇油雷特", "meaning": "回头见", "sentence": "Catch you later!", "translation": "回头见！", "homophoneSentence": "凯奇油雷特!"},
    {"word": "Talk to you soon", "phonetic": "/tɔːk tuː juː suːn/", "homophone": "托克图油苏恩", "meaning": "很快再聊", "sentence": "Talk to you soon!", "translation": "很快再聊！", "homophoneSentence": "托克图油苏恩!"},
    {"word": "Until next time", "phonetic": "/ənˈtɪl nekst taɪm/", "homophone": "昂提尔奈克斯特泰姆", "meaning": "下次见", "sentence": "Until next time!", "translation": "下次见！", "homophoneSentence": "昂提尔奈克斯特泰姆!"},
    {"word": "So long", "phonetic": "/səʊ lɒŋ/", "homophone": "搜朗", "meaning": "再见", "sentence": "So long!", "translation": "再见！", "homophoneSentence": "搜朗!"},
    {"word": "Farewell", "phonetic": "/ˌfeəˈwel/", "homophone": "夫尔威尔", "meaning": "告别", "sentence": "Farewell my friend!", "translation": "告别我的朋友！", "homophoneSentence": "夫尔威尔麦夫瑞恩德!"},
    {"word": "See you", "phonetic": "/siː juː/", "homophone": "西油", "meaning": "再见", "sentence": "See you!", "translation": "再见！", "homophoneSentence": "西油!"},
    {"word": "Later", "phonetic": "/ˈleɪtə/", "homophone": "雷特", "meaning": "回头见", "sentence": "Later!", "translation": "回头见！", "homophoneSentence": "雷特!"},
    {"word": "Peace out", "phonetic": "/piːs aʊt/", "homophone": "皮斯奥特", "meaning": "和平再见", "sentence": "Peace out!", "translation": "和平再见！", "homophoneSentence": "皮斯奥特!"},
    {"word": "I gotta go", "phonetic": "/aɪ ˈɡɒtə ɡəʊ/", "homophone": "爱嘎塔勾", "meaning": "我得走了", "sentence": "I gotta go now.", "translation": "我现在得走了。", "homophoneSentence": "爱嘎塔勾闹."},
    {"word": "I have to run", "phonetic": "/aɪ hæv tuː rʌn/", "homophone": "爱海夫图然", "meaning": "我得赶紧走了", "sentence": "I have to run!", "translation": "我得赶紧走了！", "homophoneSentence": "爱海夫图然!"},
    {"word": "Take it easy", "phonetic": "/teɪk ɪt ˈiːzi/", "homophone": "泰克伊特伊兹", "meaning": "放轻松", "sentence": "Take it easy!", "translation": "放轻松！", "homophoneSentence": "泰克伊特伊兹!"},
    {"word": "Keep in touch", "phonetic": "/kiːp ɪn tʌtʃ/", "homophone": "基普因塔奇", "meaning": "保持联系", "sentence": "Keep in touch!", "translation": "保持联系！", "homophoneSentence": "基普因塔奇!"},
    {"word": "Don't be a stranger", "phonetic": "/dəʊnt biː ə ˈstreɪndʒə/", "homophone": "东特比啊斯纯德热", "meaning": "别见外", "sentence": "Don't be a stranger!", "translation": "别见外！", "homophoneSentence": "东特比啊斯纯德热!"},
    {"word": "Have a good one", "phonetic": "/hæv ə ɡʊd wʌn/", "homophone": "海夫啊古德万", "meaning": "祝你过得愉快", "sentence": "Have a good one!", "translation": "祝你过得愉快！", "homophoneSentence": "海夫啊古德万!"},
    {"word": "Enjoy your day", "phonetic": "/ɪnˈdʒɔɪ jɔː deɪ/", "homophone": "因照伊哟戴", "meaning": "享受你的一天", "sentence": "Enjoy your day!", "translation": "享受你的一天！", "homophoneSentence": "因照伊哟戴!"},
    {"word": "Make yourself at home", "phonetic": "/meɪk jɔːˈself æt həʊm/", "homophone": "梅克哟塞尔夫艾特厚姆", "meaning": "别客气", "sentence": "Make yourself at home!", "translation": "别客气！", "homophoneSentence": "梅克哟塞尔夫艾特厚姆!"},
    {"word": "Help yourself", "phonetic": "/help jɔːˈself/", "homophone": "赫尔普哟塞尔夫", "meaning": "请自便", "sentence": "Help yourself to some tea.", "translation": "请自便喝茶。", "homophoneSentence": "赫尔普哟塞尔夫图萨姆提."},
    {"word": "Be my guest", "phonetic": "/biː maɪ ɡest/", "homophone": "比麦盖斯特", "meaning": "请随意", "sentence": "Be my guest!", "translation": "请随意！", "homophoneSentence": "比麦盖斯特!"},
    {"word": "After you", "phonetic": "/ˈɑːftə juː/", "homophone": "阿夫特油", "meaning": "您先请", "sentence": "After you!", "translation": "您先请！", "homophoneSentence": "阿夫特油!"},
    {"word": "Ladies first", "phonetic": "/ˈleɪdiz fɜːst/", "homophone": "雷迪兹佛斯特", "meaning": "女士优先", "sentence": "Ladies first!", "translation": "女士优先！", "homophoneSentence": "雷迪兹佛斯特!"},
    {"word": "Age before beauty", "phonetic": "/eɪdʒ bɪˈfɔː ˈbjuːti/", "homophone": "艾吉比佛比欧提", "meaning": "长者优先", "sentence": "Age before beauty!", "translation": "长者优先！", "homophoneSentence": "艾吉比佛比欧提!"},
    {"word": "Please go ahead", "phonetic": "/pliːz ɡəʊ əˈhed/", "homophone": "普利斯勾啊海德", "meaning": "请继续", "sentence": "Please go ahead!", "translation": "请继续！", "homophoneSentence": "普利斯勾啊海德!"},
    {"word": "Don't mind me", "phonetic": "/dəʊnt maɪnd miː/", "homophone": "东特迈因德米", "meaning": "别管我", "sentence": "Don't mind me.", "translation": "别管我。", "homophoneSentence": "东特迈因德米."},
    {"word": "Pardon me", "phonetic": "/ˈpɑːdn miː/", "homophone": "帕登米", "meaning": "请原谅", "sentence": "Pardon me?", "translation": "请再说一遍？", "homophoneSentence": "帕登米?"},
    {"word": "I beg your pardon", "phonetic": "/aɪ beɡ jɔː ˈpɑːdn/", "homophone": "爱贝格哟帕登", "meaning": "请您原谅", "sentence": "I beg your pardon?", "translation": "请您再说一遍？", "homophoneSentence": "爱贝格哟帕登?"},
    {"word": "What was that", "phonetic": "/wɒt wɒz ðæt/", "homophone": "沃特沃兹泽特", "meaning": "那是什么", "sentence": "What was that?", "translation": "那是什么？", "homophoneSentence": "沃特沃兹泽特?"},
    {"word": "Come again", "phonetic": "/kʌm əˈɡen/", "homophone": "卡姆阿根", "meaning": "再说一遍", "sentence": "Come again?", "translation": "再说一遍？", "homophoneSentence": "卡姆阿根?"},
    {"word": "Say that again", "phonetic": "/seɪ ðæt əˈɡen/", "homophone": "赛泽特阿根", "meaning": "再说一遍", "sentence": "Say that again?", "translation": "再说一遍？", "homophoneSentence": "赛泽特阿根?"},
    {"word": "I didn't catch that", "phonetic": "/aɪ ˈdɪdnt kætʃ ðæt/", "homophone": "爱迪登特凯奇泽特", "meaning": "我没听清", "sentence": "I didn't catch that.", "translation": "我没听清。", "homophoneSentence": "爱迪登特凯奇泽特."},
    {"word": "Could you say that again", "phonetic": "/kʊd juː seɪ ðæt əˈɡen/", "homophone": "库德油赛泽特阿根", "meaning": "你能再说一遍吗", "sentence": "Could you say that again?", "translation": "你能再说一遍吗？", "homophoneSentence": "库德油赛泽特阿根?"},
    {"word": "Speak up", "phonetic": "/spiːk ʌp/", "homophone": "斯皮克阿普", "meaning": "大声点", "sentence": "Please speak up!", "translation": "请大声点！", "homophoneSentence": "普利斯斯皮克阿普!"},
    {"word": "Louder please", "phonetic": "/ˈlaʊdə pliːz/", "homophone": "劳德普利斯", "meaning": "请大声点", "sentence": "Louder please!", "translation": "请大声点！", "homophoneSentence": "劳德普利斯!"},
    {"word": "I can't hear you", "phonetic": "/aɪ kɑːnt hɪə juː/", "homophone": "爱康特希尔油", "meaning": "我听不见你", "sentence": "I can't hear you!", "translation": "我听不见你！", "homophoneSentence": "爱康特希尔油!"},
    {"word": "It's too noisy", "phonetic": "/ɪts tuː ˈnɔɪzi/", "homophone": "伊茨图诺伊兹", "meaning": "太吵了", "sentence": "It's too noisy here.", "translation": "这里太吵了。", "homophoneSentence": "伊茨图诺伊兹希尔."},
    {"word": "Could you speak slower", "phonetic": "/kʊd juː spiːk ˈsləʊə/", "homophone": "库德油斯皮克斯楼尔", "meaning": "你能说慢点吗", "sentence": "Could you speak slower?", "translation": "你能说慢点吗？", "homophoneSentence": "库德油斯皮克斯楼尔?"},
    {"word": "One more time", "phonetic": "/wʌn mɔː taɪm/", "homophone": "万莫泰姆", "meaning": "再来一次", "sentence": "One more time please!", "translation": "请再来一次！", "homophoneSentence": "万莫泰姆普利斯!"},
    {"word": "What do you mean", "phonetic": "/wɒt duː juː miːn/", "homophone": "沃特度油米恩", "meaning": "你是什么意思", "sentence": "What do you mean?", "translation": "你是什么意思？", "homophoneSentence": "沃特度油米恩?"},
    {"word": "Are you serious", "phonetic": "/ɑː juː ˈsɪəriəs/", "homophone": "阿油希尔瑞尔斯", "meaning": "你是认真的吗", "sentence": "Are you serious?", "translation": "你是认真的吗？", "homophoneSentence": "阿油希尔瑞尔斯?"},
    {"word": "Really", "phonetic": "/ˈrɪəli/", "homophone": "瑞尔利", "meaning": "真的吗", "sentence": "Really?", "translation": "真的吗？", "homophoneSentence": "瑞尔利?"},
    {"word": "Are you kidding", "phonetic": "/ɑː juː ˈkɪdɪŋ/", "homophone": "阿油基丁", "meaning": "你在开玩笑吗", "sentence": "Are you kidding me?", "translation": "你在开玩笑吗？", "homophoneSentence": "阿油基丁米?"},
    {"word": "No way", "phonetic": "/nəʊ weɪ/", "homophone": "诺威", "meaning": "不可能", "sentence": "No way!", "translation": "不可能！", "homophoneSentence": "诺威!"},
    {"word": "Get out of here", "phonetic": "/ɡet aʊt əv hɪə/", "homophone": "盖特奥特啊夫希尔", "meaning": "别开玩笑了", "sentence": "Get out of here!", "translation": "别开玩笑了！", "homophoneSentence": "盖特奥特啊夫希尔!"},
    {"word": "You're joking", "phonetic": "/jɔː ˈdʒəʊkɪŋ/", "homophone": "哟卓克英", "meaning": "你在开玩笑", "sentence": "You're joking!", "translation": "你在开玩笑！", "homophoneSentence": "哟卓克英!"},
    {"word": "I can't believe it", "phonetic": "/aɪ kɑːnt bɪˈliːv ɪt/", "homophone": "爱康特比利夫伊特", "meaning": "我不敢相信", "sentence": "I can't believe it!", "translation": "我不敢相信！", "homophoneSentence": "爱康特比利夫伊特!"},
    {"word": "That's unbelievable", "phonetic": "/ðæts ʌnbɪˈliːvəbl/", "homophone": "泽茨昂比利夫波欧", "meaning": "难以置信", "sentence": "That's unbelievable!", "translation": "难以置信！", "homophoneSentence": "泽茨昂比利夫波欧!"},
    {"word": "Wow", "phonetic": "/waʊ/", "homophone": "哇", "meaning": "哇", "sentence": "Wow!", "translation": "哇！", "homophoneSentence": "哇!"},
    {"word": "Oh my god", "phonetic": "/əʊ maɪ ɡɒd/", "homophone": "欧麦高德", "meaning": "我的天", "sentence": "Oh my god!", "translation": "我的天！", "homophoneSentence": "欧麦高德!"},
    {"word": "Oh my goodness", "phonetic": "/əʊ maɪ ˈɡʊdnəs/", "homophone": "欧麦古德内斯", "meaning": "我的天哪", "sentence": "Oh my goodness!", "translation": "我的天哪！", "homophoneSentence": "欧麦古德内斯!"},
    {"word": "Holy cow", "phonetic": "/ˈhəʊli kaʊ/", "homophone": "厚利考", "meaning": "天哪", "sentence": "Holy cow!", "translation": "天哪！", "homophoneSentence": "厚利考!"},
    {"word": "Oh no", "phonetic": "/əʊ nəʊ/", "homophone": "欧诺", "meaning": "哦不", "sentence": "Oh no!", "translation": "哦不！", "homophoneSentence": "欧诺!"},
    {"word": "What a pity", "phonetic": "/wɒt ə ˈpɪti/", "homophone": "沃特啊皮提", "meaning": "真遗憾", "sentence": "What a pity!", "translation": "真遗憾！", "homophoneSentence": "沃特啊皮提!"},
    {"word": "What a shame", "phonetic": "/wɒt ə ʃeɪm/", "homophone": "沃特啊谢姆", "meaning": "真可惜", "sentence": "What a shame!", "translation": "真可惜！", "homophoneSentence": "沃特啊谢姆!"},
    {"word": "That's too bad", "phonetic": "/ðæts tuː bæd/", "homophone": "泽茨图拜德", "meaning": "太糟糕了", "sentence": "That's too bad!", "translation": "太糟糕了！", "homophoneSentence": "泽茨图拜德!"},
    {"word": "I'm so sorry", "phonetic": "/aɪm səʊ ˈsɒri/", "homophone": "爱姆搜索里", "meaning": "我很抱歉", "sentence": "I'm so sorry!", "translation": "我很抱歉！", "homophoneSentence": "爱姆搜索里!"},
    {"word": "My condolences", "phonetic": "/maɪ kənˈdəʊlənsɪz/", "homophone": "麦康德楼恩西兹", "meaning": "请节哀", "sentence": "My condolences.", "translation": "请节哀。", "homophoneSentence": "麦康德楼恩西兹."},
    {"word": "I feel bad", "phonetic": "/aɪ fiːl bæd/", "homophone": "爱菲尔拜德", "meaning": "我感到难过", "sentence": "I feel bad about that.", "translation": "我对此感到难过。", "homophoneSentence": "爱菲尔拜德阿鲍特泽特."},
    {"word": "That's awful", "phonetic": "/ðæts ˈɔːfl/", "homophone": "泽茨奥夫欧", "meaning": "太可怕了", "sentence": "That's awful!", "translation": "太可怕了！", "homophoneSentence": "泽茨奥夫欧!"},
    {"word": "How terrible", "phonetic": "/haʊ ˈterəbl/", "homophone": "好泰瑞波欧", "meaning": "太可怕了", "sentence": "How terrible!", "translation": "太可怕了！", "homophoneSentence": "好泰瑞波欧!"},
    {"word": "Poor you", "phonetic": "/pɔː juː/", "homophone": "坡油", "meaning": "可怜的你", "sentence": "Poor you!", "translation": "可怜的你！", "homophoneSentence": "坡油!"},
    {"word": "Bless your heart", "phonetic": "/bles jɔː hɑːt/", "homophone": "布莱斯哟哈特", "meaning": "保佑你", "sentence": "Bless your heart!", "translation": "保佑你！", "homophoneSentence": "布莱斯哟哈特!"},
    {"word": "Hang in there", "phonetic": "/hæŋ ɪn ðeə/", "homophone": "杭因泽尔", "meaning": "坚持下去", "sentence": "Hang in there!", "translation": "坚持下去！", "homophoneSentence": "杭因泽尔!"},
    {"word": "Keep your chin up", "phonetic": "/kiːp jɔː tʃɪn ʌp/", "homophone": "基普哟钦阿普", "meaning": "振作起来", "sentence": "Keep your chin up!", "translation": "振作起来！", "homophoneSentence": "基普哟钦阿普!"},
    {"word": "Things will get better", "phonetic": "/θɪŋz wɪl ɡet ˈbetə/", "homophone": "星兹威尔盖特百特", "meaning": "事情会好起来的", "sentence": "Things will get better.", "translation": "事情会好起来的。", "homophoneSentence": "星兹威尔盖特百特."},
    {"word": "Don't worry", "phonetic": "/dəʊnt ˈwʌri/", "homophone": "东特沃瑞", "meaning": "别担心", "sentence": "Don't worry!", "translation": "别担心！", "homophoneSentence": "东特沃瑞!"},
    {"word": "It will be okay", "phonetic": "/ɪt wɪl biː əʊˈkeɪ/", "homophone": "伊特威尔比欧凯", "meaning": "会没事的", "sentence": "It will be okay.", "translation": "会没事的。", "homophoneSentence": "伊特威尔比欧凯."},
    {"word": "Everything will be fine", "phonetic": "/ˈevriθɪŋ wɪl biː faɪn/", "homophone": "埃瑞星威尔比法因", "meaning": "一切都会好的", "sentence": "Everything will be fine.", "translation": "一切都会好的。", "homophoneSentence": "埃瑞星威尔比法因."},
    {"word": "Stay positive", "phonetic": "/steɪ ˈpɒzətɪv/", "homophone": "斯泰波兹提夫", "meaning": "保持乐观", "sentence": "Stay positive!", "translation": "保持乐观！", "homophoneSentence": "斯泰波兹提夫!"},
    {"word": "Look on the bright side", "phonetic": "/lʊk ɒn ðə braɪt saɪd/", "homophone": "卢克昂泽布来特赛德", "meaning": "往好处想", "sentence": "Look on the bright side!", "translation": "往好处想！", "homophoneSentence": "卢克昂泽布来特赛德!"},
    {"word": "Every cloud has a silver lining", "phonetic": "/ˈevri klaʊd hæz ə ˈsɪlvə ˈlaɪnɪŋ/", "homophone": "埃瑞克劳德海兹啊西尔瓦来宁", "meaning": "黑暗中总有一线光明", "sentence": "Every cloud has a silver lining.", "translation": "黑暗中总有一线光明。", "homophoneSentence": "埃瑞克劳德海兹啊西尔瓦来宁."},
    {"word": "Better luck next time", "phonetic": "/ˈbetə lʌk nekst taɪm/", "homophone": "百特拉客奈克斯特泰姆", "meaning": "下次好运", "sentence": "Better luck next time!", "translation": "下次好运！", "homophoneSentence": "百特拉客奈克斯特泰姆!"},
    {"word": "You'll do better", "phonetic": "/juːl duː ˈbetə/", "homophone": "优欧度百特", "meaning": "你会做得更好", "sentence": "You'll do better next time.", "translation": "你下次会做得更好。", "homophoneSentence": "优欧度百特奈克斯特泰姆."},
    {"word": "Practice makes perfect", "phonetic": "/ˈpræktɪs meɪks ˈpɜːfɪkt/", "homophone": "普拉克提斯梅克斯坡佛费克特", "meaning": "熟能生巧", "sentence": "Practice makes perfect.", "translation": "熟能生巧。", "homophoneSentence": "普拉克提斯梅克斯坡佛费克特."},
    {"word": "Never give up", "phonetic": "/ˈnevə ɡɪv ʌp/", "homophone": "奈夫盖夫阿普", "meaning": "永不放弃", "sentence": "Never give up!", "translation": "永不放弃！", "homophoneSentence": "奈夫盖夫阿普!"},
    {"word": "Keep trying", "phonetic": "/kiːp ˈtraɪɪŋ/", "homophone": "基普踹英", "meaning": "继续尝试", "sentence": "Keep trying!", "translation": "继续尝试！", "homophoneSentence": "基普踹英!"},
    {"word": "Don't give up", "phonetic": "/dəʊnt ɡɪv ʌp/", "homophone": "东特盖夫阿普", "meaning": "不要放弃", "sentence": "Don't give up!", "translation": "不要放弃！", "homophoneSentence": "东特盖夫阿普!"},
    {"word": "You can do it", "phonetic": "/juː kæn duː ɪt/", "homophone": "优坎度伊特", "meaning": "你能做到", "sentence": "You can do it!", "translation": "你能做到！", "homophoneSentence": "优坎度伊特!"},
    {"word": "I believe in you", "phonetic": "/aɪ bɪˈliːv ɪn juː/", "homophone": "爱比利夫因油", "meaning": "我相信你", "sentence": "I believe in you!", "translation": "我相信你！", "homophoneSentence": "爱比利夫因油!"},
    {"word": "You're the best", "phonetic": "/jɔː ðə best/", "homophone": "哟泽百斯特", "meaning": "你是最棒的", "sentence": "You're the best!", "translation": "你是最棒的！", "homophoneSentence": "哟泽百斯特!"},
    {"word": "Way to go", "phonetic": "/weɪ tuː ɡəʊ/", "homophone": "威图勾", "meaning": "干得好", "sentence": "Way to go!", "translation": "干得好！", "homophoneSentence": "威图勾!"},
    {"word": "Good for you", "phonetic": "/ɡʊd fɔː juː/", "homophone": "古德佛油", "meaning": "真为你高兴", "sentence": "Good for you!", "translation": "真为你高兴！", "homophoneSentence": "古德佛油!"},
    {"word": "I'm proud of you", "phonetic": "/aɪm praʊd əv juː/", "homophone": "爱姆普绕德啊夫油", "meaning": "我为你骄傲", "sentence": "I'm proud of you!", "translation": "我为你骄傲！", "homophoneSentence": "爱姆普绕德啊夫油!"},
    {"word": "You deserve it", "phonetic": "/juː dɪˈzɜːv ɪt/", "homophone": "优迪泽夫伊特", "meaning": "这是你应得的", "sentence": "You deserve it!", "translation": "这是你应得的！", "homophoneSentence": "优迪泽夫伊特!"},
    {"word": "That's amazing", "phonetic": "/ðæts əˈmeɪzɪŋ/", "homophone": "泽茨阿梅兹英", "meaning": "太棒了", "sentence": "That's amazing!", "translation": "太棒了！", "homophoneSentence": "泽茨阿梅兹英!"},
    {"word": "I'm impressed", "phonetic": "/aɪm ɪmˈprest/", "homophone": "爱姆因普热斯特", "meaning": "我很佩服", "sentence": "I'm impressed!", "translation": "我很佩服！", "homophoneSentence": "爱姆因普热斯特!"},
    {"word": "You did great", "phonetic": "/juː dɪd ɡreɪt/", "homophone": "优迪德格瑞特", "meaning": "你做得很好", "sentence": "You did great!", "translation": "你做得很好！", "homophoneSentence": "优迪德格瑞特!"},
    {"word": "Nice work", "phonetic": "/naɪs wɜːk/", "homophone": "奈斯沃克", "meaning": "干得好", "sentence": "Nice work!", "translation": "干得好！", "homophoneSentence": "奈斯沃克!"},
    {"word": "Good job", "phonetic": "/ɡʊd dʒɒb/", "homophone": "古德焦布", "meaning": "做得好", "sentence": "Good job!", "translation": "做得好！", "homophoneSentence": "古德焦布!"},
    {"word": "Atta boy", "phonetic": "/ˈætə bɔɪ/", "homophone": "阿塔波伊", "meaning": "好样的", "sentence": "Atta boy!", "translation": "好样的！", "homophoneSentence": "阿塔波伊!"},
    {"word": "Atta girl", "phonetic": "/ˈætə ɡɜːl/", "homophone": "阿塔格尔", "meaning": "好样的", "sentence": "Atta girl!", "translation": "好样的！", "homophoneSentence": "阿塔格尔!"},
    {"word": "Hats off to you", "phonetic": "/hæts ɒf tuː juː/", "homophone": "海茨奥夫图油", "meaning": "向你致敬", "sentence": "Hats off to you!", "translation": "向你致敬！", "homophoneSentence": "海茨奥夫图油!"},
    {"word": "You rock", "phonetic": "/juː rɒk/", "homophone": "优若克", "meaning": "你太棒了", "sentence": "You rock!", "translation": "你太棒了！", "homophoneSentence": "优若克!"},
    {"word": "You rule", "phonetic": "/juː ruːl/", "homophone": "优如欧", "meaning": "你最厉害", "sentence": "You rule!", "translation": "你最厉害！", "homophoneSentence": "优如欧!"},
    {"word": "Kudos to you", "phonetic": "/ˈkjuːdɒs tuː juː/", "homophone": "丘多斯图油", "meaning": "向你致敬", "sentence": "Kudos to you!", "translation": "向你致敬！", "homophoneSentence": "丘多斯图油!"},
    {"word": "Bravo", "phonetic": "/ˈbrɑːvəʊ/", "homophone": "布拉沃", "meaning": "太棒了", "sentence": "Bravo!", "translation": "太棒了！", "homophoneSentence": "布拉沃!"},
    {"word": "Hooray", "phonetic": "/hʊˈreɪ/", "homophone": "胡瑞", "meaning": "万岁", "sentence": "Hooray!", "translation": "万岁！", "homophoneSentence": "胡瑞!"},
    {"word": "Yay", "phonetic": "/jeɪ/", "homophone": "耶", "meaning": "耶", "sentence": "Yay!", "translation": "耶！", "homophoneSentence": "耶!"},
    {"word": "Woohoo", "phonetic": "/ˈwuːhuː/", "homophone": "乌胡", "meaning": "哇呼", "sentence": "Woohoo!", "translation": "哇呼！", "homophoneSentence": "乌胡!"},
    {"word": "Yippee", "phonetic": "/ˈjɪpi/", "homophone": "伊皮", "meaning": "好哇", "sentence": "Yippee!", "translation": "好哇！", "homophoneSentence": "伊皮!"},
    {"word": "What a relief", "phonetic": "/wɒt ə rɪˈliːf/", "homophone": "沃特啊瑞利夫", "meaning": "真是松了口气", "sentence": "What a relief!", "translation": "真是松了口气！", "homophoneSentence": "沃特啊瑞利夫!"},
    {"word": "Thank goodness", "phonetic": "/θæŋk ˈɡʊdnəs/", "homophone": "森克古德内斯", "meaning": "谢天谢地", "sentence": "Thank goodness!", "translation": "谢天谢地！", "homophoneSentence": "森克古德内斯!"},
    {"word": "Thank heavens", "phonetic": "/θæŋk ˈhevnz/", "homophone": "森克海文斯", "meaning": "谢天谢地", "sentence": "Thank heavens!", "translation": "谢天谢地！", "homophoneSentence": "森克海文斯!"},
    {"word": "What a surprise", "phonetic": "/wɒt ə səˈpraɪz/", "homophone": "沃特啊色普来兹", "meaning": "真惊喜", "sentence": "What a surprise!", "translation": "真惊喜！", "homophoneSentence": "沃特啊色普来兹!"},
    {"word": "I'm speechless", "phonetic": "/aɪm ˈspiːtʃləs/", "homophone": "爱姆斯皮奇勒斯", "meaning": "我无言以对", "sentence": "I'm speechless!", "translation": "我无言以对！", "homophoneSentence": "爱姆斯皮奇勒斯!"},
    {"word": "I'm stunned", "phonetic": "/aɪm stʌnd/", "homophone": "爱姆斯坦德", "meaning": "我惊呆了", "sentence": "I'm stunned!", "translation": "我惊呆了！", "homophoneSentence": "爱姆斯坦德!"},
    {"word": "I'm shocked", "phonetic": "/aɪm ʃɒkt/", "homophone": "爱姆肖克特", "meaning": "我很震惊", "sentence": "I'm shocked!", "translation": "我很震惊！", "homophoneSentence": "爱姆肖克特!"},
    {"word": "That's shocking", "phonetic": "/ðæts ˈʃɒkɪŋ/", "homophone": "泽茨肖克英", "meaning": "太令人震惊了", "sentence": "That's shocking!", "translation": "太令人震惊了！", "homophoneSentence": "泽茨肖克英!"},
    {"word": "I can't take it", "phonetic": "/aɪ kɑːnt teɪk ɪt/", "homophone": "爱康特泰克伊特", "meaning": "我受不了了", "sentence": "I can't take it anymore!", "translation": "我再也受不了了！", "homophoneSentence": "爱康特泰克伊特安妮莫!"},
    {"word": "This is too much", "phonetic": "/ðɪs ɪz tuː mʌtʃ/", "homophone": "迪斯伊兹图马奇", "meaning": "这太过分了", "sentence": "This is too much!", "translation": "这太过分了！", "homophoneSentence": "迪斯伊兹图马奇!"},
    {"word": "I've had enough", "phonetic": "/aɪv hæd ɪˈnʌf/", "homophone": "爱夫海德因纳夫", "meaning": "我受够了", "sentence": "I've had enough!", "translation": "我受够了！", "homophoneSentence": "爱夫海德因纳夫!"},
    {"word": "That's it", "phonetic": "/ðæts ɪt/", "homophone": "泽茨伊特", "meaning": "就这样", "sentence": "That's it!", "translation": "就这样！", "homophoneSentence": "泽茨伊特!"},
    {"word": "I'm done", "phonetic": "/aɪm dʌn/", "homophone": "爱姆丹", "meaning": "我结束了", "sentence": "I'm done!", "translation": "我结束了！", "homophoneSentence": "爱姆丹!"},
    {"word": "Forget it", "phonetic": "/fəˈɡet ɪt/", "homophone": "佛盖特伊特", "meaning": "算了吧", "sentence": "Forget it!", "translation": "算了吧！", "homophoneSentence": "佛盖特伊特!"},
    {"word": "Never mind", "phonetic": "/ˈnevə maɪnd/", "homophone": "奈夫迈因德", "meaning": "没关系", "sentence": "Never mind!", "translation": "没关系！", "homophoneSentence": "奈夫迈因德!"},
    {"word": "It doesn't matter", "phonetic": "/ɪt ˈdʌznt ˈmætə/", "homophone": "伊特达曾特麦特", "meaning": "没关系", "sentence": "It doesn't matter.", "translation": "没关系。", "homophoneSentence": "伊特达曾特麦特."},
    {"word": "No big deal", "phonetic": "/nəʊ bɪɡ diːl/", "homophone": "诺比格迪尔", "meaning": "没什么大不了的", "sentence": "No big deal!", "translation": "没什么大不了的！", "homophoneSentence": "诺比格迪尔!"},
    {"word": "It's not important", "phonetic": "/ɪts nɒt ɪmˈpɔːtnt/", "homophone": "伊茨诺特因坡腾特", "meaning": "这不重要", "sentence": "It's not important.", "translation": "这不重要。", "homophoneSentence": "伊茨诺特因坡腾特."},
    {"word": "Who cares", "phonetic": "/huː keəz/", "homophone": "胡凯尔兹", "meaning": "谁在乎", "sentence": "Who cares?", "translation": "谁在乎？", "homophoneSentence": "胡凯尔兹?"},
    {"word": "So what", "phonetic": "/səʊ wɒt/", "homophone": "搜沃特", "meaning": "那又怎样", "sentence": "So what?", "translation": "那又怎样？", "homophoneSentence": "搜沃特?"},
    {"word": "Whatever", "phonetic": "/wɒtˈevə/", "homophone": "沃特埃弗", "meaning": "随便", "sentence": "Whatever!", "translation": "随便！", "homophoneSentence": "沃特埃弗!"},
    {"word": "I don't care", "phonetic": "/aɪ dəʊnt keə/", "homophone": "爱东特凯尔", "meaning": "我不在乎", "sentence": "I don't care!", "translation": "我不在乎！", "homophoneSentence": "爱东特凯尔!"},
    {"word": "Leave me alone", "phonetic": "/liːv miː əˈləʊn/", "homophone": "利夫米啊楼恩", "meaning": "别烦我", "sentence": "Leave me alone!", "translation": "别烦我！", "homophoneSentence": "利夫米啊楼恩!"},
    {"word": "Get lost", "phonetic": "/ɡet lɒst/", "homophone": "盖特洛斯特", "meaning": "走开", "sentence": "Get lost!", "translation": "走开！", "homophoneSentence": "盖特洛斯特!"},
    {"word": "Go away", "phonetic": "/ɡəʊ əˈweɪ/", "homophone": "勾啊威", "meaning": "走开", "sentence": "Go away!", "translation": "走开！", "homophoneSentence": "勾啊威!"},
    {"word": "Back off", "phonetic": "/bæk ɒf/", "homophone": "拜克奥夫", "meaning": "退后", "sentence": "Back off!", "translation": "退后！", "homophoneSentence": "拜克奥夫!"},
    {"word": "Cut it out", "phonetic": "/kʌt ɪt aʊt/", "homophone": "卡特伊特奥特", "meaning": "住手", "sentence": "Cut it out!", "translation": "住手！", "homophoneSentence": "卡特伊特奥特!"},
    {"word": "Stop it", "phonetic": "/stɒp ɪt/", "homophone": "斯道普伊特", "meaning": "停下", "sentence": "Stop it!", "translation": "停下！", "homophoneSentence": "斯道普伊特!"},
    {"word": "Knock it off", "phonetic": "/nɒk ɪt ɒf/", "homophone": "诺克伊特奥夫", "meaning": "住手", "sentence": "Knock it off!", "translation": "住手！", "homophoneSentence": "诺克伊特奥夫!"},
    {"word": "Give me a break", "phonetic": "/ɡɪv miː ə breɪk/", "homophone": "盖夫米啊布雷克", "meaning": "饶了我吧", "sentence": "Give me a break!", "translation": "饶了我吧！", "homophoneSentence": "盖夫米啊布雷克!"},
    {"word": "Come on", "phonetic": "/kʌm ɒn/", "homophone": "卡姆昂", "meaning": "拜托", "sentence": "Come on!", "translation": "拜托！", "homophoneSentence": "卡姆昂!"},
    {"word": "Oh please", "phonetic": "/əʊ pliːz/", "homophone": "欧普利斯", "meaning": "哦拜托", "sentence": "Oh please!", "translation": "哦拜托！", "homophoneSentence": "欧普利斯!"},
    {"word": "You've got to be kidding", "phonetic": "/juːv ɡɒt tuː biː ˈkɪdɪŋ/", "homophone": "优欧夫哥特图比基丁", "meaning": "你一定在开玩笑", "sentence": "You've got to be kidding!", "translation": "你一定在开玩笑！", "homophoneSentence": "优欧夫哥特图比基丁!"},
    {"word": "Yeah right", "phonetic": "/jeə raɪt/", "homophone": "耶尔来特", "meaning": "是啊，才怪", "sentence": "Yeah right!", "translation": "是啊，才怪！", "homophoneSentence": "耶尔来特!"},
    {"word": "As if", "phonetic": "/æz ɪf/", "homophone": "艾兹伊夫", "meaning": "好像", "sentence": "As if!", "translation": "好像！", "homophoneSentence": "艾兹伊夫!"},
    {"word": "In your dreams", "phonetic": "/ɪn jɔː driːmz/", "homophone": "因哟追姆斯", "meaning": "做梦吧", "sentence": "In your dreams!", "translation": "做梦吧！", "homophoneSentence": "因哟追姆斯!"},
    {"word": "Not a chance", "phonetic": "/nɒt ə tʃɑːns/", "homophone": "诺特啊查恩斯", "meaning": "没门", "sentence": "Not a chance!", "translation": "没门！", "homophoneSentence": "诺特啊查恩斯!"},
    {"word": "No way Jose", "phonetic": "/nəʊ weɪ həʊˈzeɪ/", "homophone": "诺威海欧泽", "meaning": "绝对不可能", "sentence": "No way Jose!", "translation": "绝对不可能！", "homophoneSentence": "诺威海欧泽!"},
    {"word": "Fat chance", "phonetic": "/fæt tʃɑːns/", "homophone": "法特查恩斯", "meaning": "机会渺茫", "sentence": "Fat chance!", "translation": "机会渺茫！", "homophoneSentence": "法特查恩斯!"},
    {"word": "Dream on", "phonetic": "/driːm ɒn/", "homophone": "追姆昂", "meaning": "做梦去吧", "sentence": "Dream on!", "translation": "做梦去吧！", "homophoneSentence": "追姆昂!"},
    {"word": "Keep dreaming", "phonetic": "/kiːp ˈdriːmɪŋ/", "homophone": "基普追明", "meaning": "继续做梦", "sentence": "Keep dreaming!", "translation": "继续做梦！", "homophoneSentence": "基普追明!"},
    {"word": "Tell me about it", "phonetic": "/tel miː əˈbaʊt ɪt/", "homophone": "泰尔米阿鲍特伊特", "meaning": "可不是嘛", "sentence": "Tell me about it!", "translation": "可不是嘛！", "homophoneSentence": "泰尔米阿鲍特伊特!"},
    {"word": "You can say that again", "phonetic": "/juː kæn seɪ ðæt əˈɡen/", "homophone": "优坎赛泽特阿根", "meaning": "你说得对", "sentence": "You can say that again!", "translation": "你说得对！", "homophoneSentence": "优坎赛泽特阿根!"},
    {"word": "I know right", "phonetic": "/aɪ nəʊ raɪt/", "homophone": "爱诺来特", "meaning": "我知道对吧", "sentence": "I know right!", "translation": "我知道对吧！", "homophoneSentence": "爱诺来特!"},
    {"word": "Exactly", "phonetic": "/ɪɡˈzæktli/", "homophone": "伊格扎克特里", "meaning": "正是", "sentence": "Exactly!", "translation": "正是！", "homophoneSentence": "伊格扎克特里!"},
    {"word": "Precisely", "phonetic": "/prɪˈsaɪsli/", "homophone": "普瑞赛斯利", "meaning": "精确地说", "sentence": "Precisely!", "translation": "精确地说！", "homophoneSentence": "普瑞赛斯利!"},
    {"word": "You said it", "phonetic": "/juː sed ɪt/", "homophone": "优赛德伊特", "meaning": "你说得对", "sentence": "You said it!", "translation": "你说得对！", "homophoneSentence": "优赛德伊特!"},
    {"word": "That's for sure", "phonetic": "/ðæts fɔː ʃʊə/", "homophone": "泽茨佛休尔", "meaning": "那是肯定的", "sentence": "That's for sure!", "translation": "那是肯定的！", "homophoneSentence": "泽茨佛休尔!"},
    {"word": "No doubt", "phonetic": "/nəʊ daʊt/", "homophone": "诺当特", "meaning": "毫无疑问", "sentence": "No doubt!", "translation": "毫无疑问！", "homophoneSentence": "诺当特!"},
    {"word": "For real", "phonetic": "/fɔː rɪəl/", "homophone": "佛瑞尔", "meaning": "真的吗", "sentence": "For real?", "translation": "真的吗？", "homophoneSentence": "佛瑞尔?"},
    {"word": "Is that so", "phonetic": "/ɪz ðæt səʊ/", "homophone": "伊兹泽特搜", "meaning": "是这样吗", "sentence": "Is that so?", "translation": "是这样吗？", "homophoneSentence": "伊兹泽特搜?"},
    {"word": "Are you sure", "phonetic": "/ɑː juː ʃʊə/", "homophone": "阿油休尔", "meaning": "你确定吗", "sentence": "Are you sure?", "translation": "你确定吗？", "homophoneSentence": "阿油休尔?"},
    {"word": "Do you think so", "phonetic": "/duː juː θɪŋk səʊ/", "homophone": "度油星克搜", "meaning": "你这么认为吗", "sentence": "Do you think so?", "translation": "你这么认为吗？", "homophoneSentence": "度油星克搜?"},
    {"word": "I suppose so", "phonetic": "/aɪ səˈpəʊz səʊ/", "homophone": "爱色剖兹搜", "meaning": "我想是吧", "sentence": "I suppose so.", "translation": "我想是吧。", "homophoneSentence": "爱色剖兹搜."},
    {"word": "I guess so", "phonetic": "/aɪ ɡes səʊ/", "homophone": "爱盖斯搜", "meaning": "我猜是吧", "sentence": "I guess so.", "translation": "我猜是吧。", "homophoneSentence": "爱盖斯搜."},
    {"word": "I hope so", "phonetic": "/aɪ həʊp səʊ/", "homophone": "爱厚普斯搜", "meaning": "我希望如此", "sentence": "I hope so.", "translation": "我希望如此。", "homophoneSentence": "爱厚普斯搜."},
    {"word": "I don't think so", "phonetic": "/aɪ dəʊnt θɪŋk səʊ/", "homophone": "爱东特星克搜", "meaning": "我不这么认为", "sentence": "I don't think so.", "translation": "我不这么认为。", "homophoneSentence": "爱东特星克搜."},
    {"word": "I hope not", "phonetic": "/aɪ həʊp nɒt/", "homophone": "爱厚普诺特", "meaning": "我希望不是", "sentence": "I hope not.", "translation": "我希望不是。", "homophoneSentence": "爱厚普诺特."},
    {"word": "Not really", "phonetic": "/nɒt ˈrɪəli/", "homophone": "诺特里尔利", "meaning": "不完全是", "sentence": "Not really.", "translation": "不完全是。", "homophoneSentence": "诺特里尔利."},
    {"word": "Sort of", "phonetic": "/sɔːt əv/", "homophone": "索特啊夫", "meaning": "有点", "sentence": "Sort of.", "translation": "有点。", "homophoneSentence": "索特啊夫."},
    {"word": "Kind of", "phonetic": "/kaɪnd əv/", "homophone": "坎德啊夫", "meaning": "有点", "sentence": "Kind of.", "translation": "有点。", "homophoneSentence": "坎德啊夫."},
    {"word": "More or less", "phonetic": "/mɔː ɔː les/", "homophone": "莫尔奥莱斯", "meaning": "或多或少", "sentence": "More or less.", "translation": "或多或少。", "homophoneSentence": "莫尔奥莱斯."},
    {"word": "It depends", "phonetic": "/ɪt dɪˈpendz/", "homophone": "伊特迪潘兹", "meaning": "看情况", "sentence": "It depends.", "translation": "看情况。", "homophoneSentence": "伊特迪潘兹."},
    {"word": "That depends", "phonetic": "/ðæt dɪˈpendz/", "homophone": "泽特迪潘兹", "meaning": "那要看情况", "sentence": "That depends.", "translation": "那要看情况。", "homophoneSentence": "泽特迪潘兹."},
    {"word": "It varies", "phonetic": "/ɪt ˈveəriːz/", "homophone": "伊特维尔瑞兹", "meaning": "因情况而异", "sentence": "It varies.", "translation": "因情况而异。", "homophoneSentence": "伊特维尔瑞兹."},
    {"word": "It's hard to say", "phonetic": "/ɪts hɑːd tuː seɪ/", "homophone": "伊茨哈德图赛", "meaning": "很难说", "sentence": "It's hard to say.", "translation": "很难说。", "homophoneSentence": "伊茨哈德图赛."},
    {"word": "I have no idea", "phonetic": "/aɪ hæv nəʊ aɪˈdɪə/", "homophone": "爱海夫诺艾迪尔", "meaning": "我不知道", "sentence": "I have no idea.", "translation": "我不知道。", "homophoneSentence": "爱海夫诺艾迪尔."},
    {"word": "I don't know", "phonetic": "/aɪ dəʊnt nəʊ/", "homophone": "爱东特诺", "meaning": "我不知道", "sentence": "I don't know.", "translation": "我不知道。", "homophoneSentence": "爱东特诺."},
    {"word": "Who knows", "phonetic": "/huː nəʊz/", "homophone": "胡诺兹", "meaning": "谁知道呢", "sentence": "Who knows?", "translation": "谁知道呢？", "homophoneSentence": "胡诺兹?"},
    {"word": "Your guess is as good as mine", "phonetic": "/jɔː ɡes ɪz æz ɡʊd æz maɪn/", "homophone": "哟盖斯伊兹艾兹古德艾兹迈恩", "meaning": "我和你一样不知道", "sentence": "Your guess is as good as mine.", "translation": "我和你一样不知道。", "homophoneSentence": "哟盖斯伊兹艾兹古德艾兹迈恩."},
    {"word": "Search me", "phonetic": "/sɜːtʃ miː/", "homophone": "瑟奇米", "meaning": "我不知道", "sentence": "Search me!", "translation": "我不知道！", "homophoneSentence": "瑟奇米!"},
    {"word": "Don't ask me", "phonetic": "/dəʊnt ɑːsk miː/", "homophone": "东特阿斯科米", "meaning": "别问我", "sentence": "Don't ask me!", "translation": "别问我！", "homophoneSentence": "东特阿斯科米!"},
    {"word": "How should I know", "phonetic": "/haʊ ʃʊd aɪ nəʊ/", "homophone": "好休德爱诺", "meaning": "我怎么会知道", "sentence": "How should I know?", "translation": "我怎么会知道？", "homophoneSentence": "好休德爱诺?"},
    {"word": "Beats me", "phonetic": "/biːts miː/", "homophone": "比茨米", "meaning": "难倒我了", "sentence": "Beats me!", "translation": "难倒我了！", "homophoneSentence": "比茨米!"},
    {"word": "It's beyond me", "phonetic": "/ɪts bɪˈjɒnd miː/", "homophone": "伊茨比扬德米", "meaning": "这超出了我的理解", "sentence": "It's beyond me.", "translation": "这超出了我的理解。", "homophoneSentence": "伊茨比扬德米."},
    {"word": "It's Greek to me", "phonetic": "/ɪts ɡriːk tuː miː/", "homophone": "伊茨格瑞克图米", "meaning": "我完全不懂", "sentence": "It's Greek to me.", "translation": "我完全不懂。", "homophoneSentence": "伊茨格瑞克图米."},
    {"word": "I'm clueless", "phonetic": "/aɪm ˈkluːləs/", "homophone": "爱姆克卢勒斯", "meaning": "我一无所知", "sentence": "I'm clueless!", "translation": "我一无所知！", "homophoneSentence": "爱姆克卢勒斯!"},
    {"word": "I'm lost", "phonetic": "/aɪm lɒst/", "homophone": "爱姆洛斯特", "meaning": "我糊涂了", "sentence": "I'm lost!", "translation": "我糊涂了！", "homophoneSentence": "爱姆洛斯特!"},
    {"word": "I'm confused", "phonetic": "/aɪm kənˈfjuːzd/", "homophone": "爱姆康夫优兹德", "meaning": "我很困惑", "sentence": "I'm confused!", "translation": "我很困惑！", "homophoneSentence": "爱姆康夫优兹德!"},
    {"word": "What's going on", "phonetic": "/wɒts ˈɡəʊɪŋ ɒn/", "homophone": "沃茨勾英昂", "meaning": "发生了什么事", "sentence": "What's going on?", "translation": "发生了什么事？", "homophoneSentence": "沃茨勾英昂?"},
    {"word": "What happened", "phonetic": "/wɒt ˈhæpənd/", "homophone": "沃特海彭德", "meaning": "发生了什么", "sentence": "What happened?", "translation": "发生了什么？", "homophoneSentence": "沃特海彭德?"},
    {"word": "What's the matter", "phonetic": "/wɒts ðə ˈmætə/", "homophone": "沃茨泽麦特", "meaning": "怎么了", "sentence": "What's the matter?", "translation": "怎么了？", "homophoneSentence": "沃茨泽麦特?"},
    {"word": "What's wrong", "phonetic": "/wɒts rɒŋ/", "homophone": "沃茨若昂", "meaning": "出什么问题了", "sentence": "What's wrong?", "translation": "出什么问题了？", "homophoneSentence": "沃茨若昂?"},
    {"word": "Are you okay", "phonetic": "/ɑː juː əʊˈkeɪ/", "homophone": "阿油欧凯", "meaning": "你还好吗", "sentence": "Are you okay?", "translation": "你还好吗？", "homophoneSentence": "阿油欧凯?"},
    {"word": "Is everything okay", "phonetic": "/ɪz ˈevriθɪŋ əʊˈkeɪ/", "homophone": "伊兹埃瑞星欧凯", "meaning": "一切都好吗", "sentence": "Is everything okay?", "translation": "一切都好吗？", "homophoneSentence": "伊兹埃瑞星欧凯?"},
    {"word": "What's up", "phonetic": "/wɒts ʌp/", "homophone": "沃茨阿普", "meaning": "怎么了", "sentence": "What's up?", "translation": "怎么了？", "homophoneSentence": "沃茨阿普?"},
    {"word": "What's happening", "phonetic": "/wɒts ˈhæpənɪŋ/", "homophone": "沃茨海彭宁", "meaning": "发生什么事了", "sentence": "What's happening?", "translation": "发生什么事了？", "homophoneSentence": "沃茨海彭宁?"},
    {"word": "Why so serious", "phonetic": "/waɪ səʊ ˈsɪəriəs/", "homophone": "外搜希尔瑞尔斯", "meaning": "为什么这么严肃", "sentence": "Why so serious?", "translation": "为什么这么严肃？", "homophoneSentence": "外搜希尔瑞尔斯?"},
    {"word": "What gives", "phonetic": "/wɒt ɡɪvz/", "homophone": "沃特给夫兹", "meaning": "怎么回事", "sentence": "What gives?", "translation": "怎么回事？", "homophoneSentence": "沃特给夫兹?"},
    {"word": "How come", "phonetic": "/haʊ kʌm/", "homophone": "好卡姆", "meaning": "怎么会", "sentence": "How come?", "translation": "怎么会？", "homophoneSentence": "好卡姆?"},
    {"word": "Is something wrong", "phonetic": "/ɪz ˈsʌmθɪŋ rɒŋ/", "homophone": "伊兹萨姆星若昂", "meaning": "有什么事吗", "sentence": "Is something wrong?", "translation": "有什么事吗？", "homophoneSentence": "伊兹萨姆星若昂?"},
    {"word": "Did I miss something", "phonetic": "/dɪd aɪ mɪs ˈsʌmθɪŋ/", "homophone": "迪德爱米斯萨姆星", "meaning": "我错过了什么吗", "sentence": "Did I miss something?", "translation": "我错过了什么吗？", "homophoneSentence": "迪德爱米斯萨姆星?"},
    {"word": "Fill me in", "phonetic": "/fɪl miː ɪn/", "homophone": "菲尔米因", "meaning": "告诉我详情", "sentence": "Fill me in!", "translation": "告诉我详情！", "homophoneSentence": "菲尔米因!"},
    {"word": "Let me know", "phonetic": "/let miː nəʊ/", "homophone": "莱特米诺", "meaning": "告诉我", "sentence": "Let me know!", "translation": "告诉我！", "homophoneSentence": "莱特米诺!"},
    {"word": "Keep me posted", "phonetic": "/kiːp miː ˈpəʊstɪd/", "homophone": "基普米剖斯提德", "meaning": "随时告诉我", "sentence": "Keep me posted!", "translation": "随时告诉我！", "homophoneSentence": "基普米剖斯提德!"},
    {"word": "I'll keep you posted", "phonetic": "/aɪl kiːp juː ˈpəʊstɪd/", "homophone": "爱欧基普油剖斯提德", "meaning": "我会随时告诉你", "sentence": "I'll keep you posted.", "translation": "我会随时告诉你。", "homophoneSentence": "爱欧基普油剖斯提德."},
    {"word": "I'll let you know", "phonetic": "/aɪl let juː nəʊ/", "homophone": "爱欧莱特油诺", "meaning": "我会告诉你", "sentence": "I'll let you know.", "translation": "我会告诉你。", "homophoneSentence": "爱欧莱特油诺."},
    {"word": "You'll be the first to know", "phonetic": "/juːl biː ðə fɜːst tuː nəʊ/", "homophone": "优欧比泽佛斯特图诺", "meaning": "你会是第一个知道的", "sentence": "You'll be the first to know.", "translation": "你会是第一个知道的。", "homophoneSentence": "优欧比泽佛斯特图诺."},
    {"word": "I'll tell you later", "phonetic": "/aɪl tel juː ˈleɪtə/", "homophone": "爱欧泰尔油雷特", "meaning": "我稍后告诉你", "sentence": "I'll tell you later.", "translation": "我稍后告诉你。", "homophoneSentence": "爱欧泰尔油雷特."},
    {"word": "It's a long story", "phonetic": "/ɪts ə lɒŋ ˈstɔːri/", "homophone": "伊茨啊朗斯托瑞", "meaning": "说来话长", "sentence": "It's a long story.", "translation": "说来话长。", "homophoneSentence": "伊茨啊朗斯托瑞."},
    {"word": "I'll explain later", "phonetic": "/aɪl ɪkˈspleɪn ˈle