const wordDatabase = {
    greetings: [
        { word: 'Hello', phonetic: '/həˈləʊ/', homophone: '哈喽', meaning: '你好', sentence: 'Hello, how are you?', translation: '你好吗？', homophoneSentence: '哈喽好啊油?' },
        { word: 'Good morning', phonetic: '/ɡʊd ˈmɔːnɪŋ/', homophone: '古德 莫宁', meaning: '早上好', sentence: 'Good morning everyone!', translation: '大家早上好！', homophoneSentence: '古德莫宁艾瑞碗!' },
        { word: 'Good afternoon', phonetic: '/ɡʊd ˌɑːftəˈnuːn/', homophone: '古德 阿夫特努恩', meaning: '下午好', sentence: 'Good afternoon, sir!', translation: '先生下午好！', homophoneSentence: '古德阿夫特努恩,色!' },
        { word: 'Good evening', phonetic: '/ɡʊd ˈiːvnɪŋ/', homophone: '古德 伊夫宁', meaning: '晚上好', sentence: 'Good evening, madam!', translation: '女士晚上好！', homophoneSentence: '古德伊夫宁,麦德姆!' },
        { word: 'Good night', phonetic: '/ɡʊd naɪt/', homophone: '古德 奈特', meaning: '晚安', sentence: 'Good night, sweet dreams!', translation: '晚安，做个好梦！', homophoneSentence: '古德奈特,斯威特追姆斯!' },
        { word: 'Goodbye', phonetic: '/ɡʊdˈbaɪ/', homophone: '古德拜', meaning: '再见', sentence: 'Goodbye, see you tomorrow!', translation: '再见，明天见！', homophoneSentence: '古德拜,希油特莫罗!' },
        { word: 'Hi', phonetic: '/haɪ/', homophone: '嗨', meaning: '嗨', sentence: 'Hi, nice to meet you!', translation: '嗨，很高兴认识你！', homophoneSentence: '嗨,奈斯图米特油!' },
        { word: 'Thank you', phonetic: '/θæŋk juː/', homophone: '三克油', meaning: '谢谢你', sentence: 'Thank you very much!', translation: '非常感谢！', homophoneSentence: '三克油歪瑞马奇!' },
        { word: 'Sorry', phonetic: '/ˈsɒri/', homophone: '索瑞', meaning: '对不起', sentence: 'Sorry, I\'m late!', translation: '对不起，我迟到了！', homophoneSentence: '索瑞,爱姆雷特!' },
        { word: 'Excuse me', phonetic: '/ɪkˈskjuːz miː/', homophone: '依克斯Q斯 密', meaning: '打扰一下', sentence: 'Excuse me, where is the station?', translation: '打扰一下，车站在哪？', homophoneSentence: '依克斯Q斯密,威尔依兹则斯戴申?' },
        { word: 'Please', phonetic: '/pliːz/', homophone: '普利斯', meaning: '请', sentence: 'Please help me!', translation: '请帮帮我！', homophoneSentence: '普利斯海尔普密!' },
        { word: 'Bye', phonetic: '/baɪ/', homophone: '拜', meaning: '再见', sentence: 'Bye, see you!', translation: '再见！', homophoneSentence: '拜,希油!' },
        { word: 'See you', phonetic: '/siː juː/', homophone: '西优', meaning: '再见', sentence: 'See you later!', translation: '待会儿见！', homophoneSentence: '西优雷特!' },
        { word: 'Yes', phonetic: '/jes/', homophone: '耶斯', meaning: '是的', sentence: 'Yes, I agree!', translation: '是的，我同意！', homophoneSentence: '耶斯,爱阿格瑞!' },
        { word: 'No', phonetic: '/nəʊ/', homophone: '诺', meaning: '不', sentence: 'No, thank you!', translation: '不用了，谢谢！', homophoneSentence: '诺,三克油!' },
        { word: 'OK', phonetic: '/ˌəʊˈkeɪ/', homophone: '欧凯', meaning: '好的', sentence: 'OK, no problem!', translation: '好的，没问题！', homophoneSentence: '欧凯,诺普若布勒姆!' },
        { word: 'Good luck', phonetic: '/ɡʊd lʌk/', homophone: '古德 拉克', meaning: '祝你好运', sentence: 'Good luck with your exam!', translation: '祝你考试顺利！', homophoneSentence: '古德拉克威兹油儿伊格赞!' }
    ],
    emotions: [
        { word: 'Happy', phonetic: '/ˈhæpi/', homophone: '嗨皮', meaning: '开心的', sentence: 'I\'m so happy today!', translation: '我今天很开心！', homophoneSentence: '爱姆搜嗨皮特戴!' },
        { word: 'Sad', phonetic: '/sæd/', homophone: '赛德', meaning: '难过的', sentence: 'Don\'t be sad, cheer up!', translation: '别难过，振作起来！', homophoneSentence: '东特比赛德,切尔啊普!' },
        { word: 'Angry', phonetic: '/ˈæŋɡri/', homophone: '安格瑞', meaning: '生气的', sentence: 'He looks very angry!', translation: '他看起来很生气！', homophoneSentence: '希鲁克斯歪瑞安格瑞!' },
        { word: 'Love', phonetic: '/lʌv/', homophone: '拉夫', meaning: '爱', sentence: 'I love you!', translation: '我爱你！', homophoneSentence: '爱拉夫油!' },
        { word: 'Like', phonetic: '/laɪk/', homophone: '来克', meaning: '喜欢', sentence: 'I like apples!', translation: '我喜欢苹果！', homophoneSentence: '爱来克艾坡z!' },
        { word: 'Hate', phonetic: '/heɪt/', homophone: '黑特', meaning: '讨厌', sentence: 'I hate rain!', translation: '我讨厌下雨！', homophoneSentence: '爱黑特瑞恩!' },
        { word: 'Afraid', phonetic: '/əˈfreɪd/', homophone: '阿夫瑞德', meaning: '害怕的', sentence: 'Don\'t be afraid!', translation: '别害怕！', homophoneSentence: '东特比阿夫瑞德!' },
        { word: 'Tired', phonetic: '/ˈtaɪəd/', homophone: '泰厄德', meaning: '累的', sentence: 'I\'m so tired!', translation: '我好累！', homophoneSentence: '爱姆搜泰厄德!' }
    ],
    numbers: [
        { word: 'One', phonetic: '/wʌn/', homophone: '万', meaning: '一', sentence: 'I have one apple.', translation: '我有一个苹果。', homophoneSentence: '爱哈夫万啊普欧.' },
        { word: 'Two', phonetic: '/tuː/', homophone: '图', meaning: '二', sentence: 'Two plus two equals four.', translation: '二加二等于四。', homophoneSentence: '图普拉斯图一阔尔斯佛.' },
        { word: 'Three', phonetic: '/θriː/', homophone: '斯瑞', meaning: '三', sentence: 'Three little birds.', translation: '三只小鸟。', homophoneSentence: '斯瑞里特波兹.' },
        { word: 'Four', phonetic: '/fɔː(r)/', homophone: '佛', meaning: '四', sentence: 'Four seasons a year.', translation: '一年四季。', homophoneSentence: '佛西森兹啊耶.' },
        { word: 'Five', phonetic: '/faɪv/', homophone: '法艾夫', meaning: '五', sentence: 'Give me five!', translation: '击个掌！', homophoneSentence: '基夫米法艾夫!' },
        { word: 'Six', phonetic: '/sɪks/', homophone: '西克斯', meaning: '六', sentence: 'Six is a lucky number.', translation: '六是个幸运数字。', homophoneSentence: '西克斯依兹啊拉基南波.' },
        { word: 'Seven', phonetic: '/ˈsevn/', homophone: '赛文', meaning: '七', sentence: 'Seven days a week.', translation: '一周七天。', homophoneSentence: '赛文戴兹啊维克.' },
        { word: 'Eight', phonetic: '/eɪt/', homophone: '艾特', meaning: '八', sentence: 'Eight hours sleep.', translation: '八小时睡眠。', homophoneSentence: '艾特阿瓦斯斯利普.' },
        { word: 'Nine', phonetic: '/naɪn/', homophone: '奈恩', meaning: '九', sentence: 'Nine lives of a cat.', translation: '猫有九条命。', homophoneSentence: '奈恩来夫兹奥夫啊凯特.' },
        { word: 'Ten', phonetic: '/ten/', homophone: '坦', meaning: '十', sentence: 'Ten fingers on hands.', translation: '双手十指。', homophoneSentence: '坦芬格兹昂汉兹.' },
        { word: 'Eleven', phonetic: '/ɪˈlevn/', homophone: '伊莱文', meaning: '十一', sentence: 'I have eleven books.', translation: '我有十一本书。', homophoneSentence: '爱哈夫伊莱文布克斯.' },
        { word: 'Twelve', phonetic: '/twelv/', homophone: '特维尔夫', meaning: '十二', sentence: 'Twelve months a year.', translation: '一年十二个月。', homophoneSentence: '特维尔夫芒斯啊耶.' },
        { word: 'Thirteen', phonetic: '/ˌθɜːˈtiːn/', homophone: '瑟廷', meaning: '十三', sentence: 'Thirteen is an unlucky number.', translation: '十三是个不吉利的数字。', homophoneSentence: '瑟廷依兹安昂拉基南波.' },
        { word: 'Fourteen', phonetic: '/ˌfɔːˈtiːn/', homophone: '佛廷', meaning: '十四', sentence: 'I am fourteen years old.', translation: '我十四岁了。', homophoneSentence: '爱阿姆佛廷耶斯欧德.' },
        { word: 'Fifteen', phonetic: '/ˌfɪfˈtiːn/', homophone: '菲廷', meaning: '十五', sentence: 'Fifteen minutes passed.', translation: '十五分钟过去了。', homophoneSentence: '菲廷米尼特斯帕斯德.' },
        { word: 'Sixteen', phonetic: '/ˌsɪksˈtiːn/', homophone: '西克斯廷', meaning: '十六', sentence: 'She is sixteen years old.', translation: '她十六岁了。', homophoneSentence: '西依兹西克斯廷耶斯欧德.' },
        { word: 'Seventeen', phonetic: '/ˌsevnˈtiːn/', homophone: '赛文廷', meaning: '十七', sentence: 'Seventeen students in class.', translation: '班里有十七个学生。', homophoneSentence: '赛文廷斯丢等茨因克莱斯.' },
        { word: 'Eighteen', phonetic: '/ˌeɪˈtiːn/', homophone: '艾廷', meaning: '十八', sentence: 'Eighteen is the legal age.', translation: '十八岁是法定年龄。', homophoneSentence: '艾廷依兹则里够累吉.' },
        { word: 'Nineteen', phonetic: '/ˌnaɪnˈtiːn/', homophone: '奈恩廷', meaning: '十九', sentence: 'Nineteen is my lucky number.', translation: '十九是我的幸运数字。', homophoneSentence: '奈恩廷依兹麦拉基南波.' },
        { word: 'Twenty', phonetic: '/ˈtwenti/', homophone: '湍踢', meaning: '二十', sentence: 'Twenty dollars for that.', translation: '那个二十美元。', homophoneSentence: '湍踢道乐兹佛扎特.' },
        { word: 'Thirty', phonetic: '/ˈθɜːti/', homophone: '瑟踢', meaning: '三十', sentence: 'Thirty days in April.', translation: '四月有三十天。', homophoneSentence: '瑟踢戴兹因艾普瑞欧.' },
        { word: 'Forty', phonetic: '/ˈfɔːti/', homophone: '佛踢', meaning: '四十', sentence: 'Forty students in class.', translation: '班里有四十个学生。', homophoneSentence: '佛踢斯丢等茨因克莱斯.' },
        { word: 'Fifty', phonetic: '/ˈfɪfti/', homophone: '菲夫踢', meaning: '五十', sentence: 'Fifty percent off.', translation: '五折优惠。', homophoneSentence: '菲夫踢波森特奥夫.' },
        { word: 'Hundred', phonetic: '/ˈhʌndrəd/', homophone: '汉德瑞德', meaning: '百', sentence: 'One hundred percent.', translation: '百分之百。', homophoneSentence: '万汉德瑞德波森特.' },
        { word: 'Zero', phonetic: '/ˈzɪərəʊ/', homophone: '泽柔', meaning: '零', sentence: 'The temperature is zero.', translation: '温度是零度。', homophoneSentence: '则坦普雷彻依兹泽柔.' }
    ],
    colors: [
        { word: 'Red', phonetic: '/red/', homophone: '瑞德', meaning: '红色', sentence: 'The rose is red.', translation: '玫瑰是红色的。', homophoneSentence: '则柔兹瑞德.' },
        { word: 'Blue', phonetic: '/bluː/', homophone: '布鲁', meaning: '蓝色', sentence: 'The sky is blue.', translation: '天空是蓝色的。', homophoneSentence: '则斯凯is布鲁.' },
        { word: 'Green', phonetic: '/ɡriːn/', homophone: '格林', meaning: '绿色', sentence: 'The grass is green.', translation: '草是绿色的。', homophoneSentence: '则格拉斯is格林.' },
        { word: 'Yellow', phonetic: '/ˈjeləʊ/', homophone: '耶喽', meaning: '黄色', sentence: 'The sun is yellow.', translation: '太阳是黄色的。', homophoneSentence: '则桑is耶喽.' },
        { word: 'Black', phonetic: '/blæk/', homophone: '布莱克', meaning: '黑色', sentence: 'The cat is black.', translation: '猫是黑色的。', homophoneSentence: '则凯特is布莱克.' },
        { word: 'White', phonetic: '/waɪt/', homophone: '怀特', meaning: '白色', sentence: 'Snow is white.', translation: '雪是白色的。', homophoneSentence: '斯诺is怀特.' },
        { word: 'Orange', phonetic: '/ˈɒrɪndʒ/', homophone: '奥润吉', meaning: '橙色', sentence: 'Oranges are orange.', translation: '橙子是橙色的。', homophoneSentence: '奥润吉兹啊奥润吉.' },
        { word: 'Pink', phonetic: '/pɪŋk/', homophone: '平克', meaning: '粉色', sentence: 'The flower is pink.', translation: '花是粉色的。', homophoneSentence: '则夫劳尔is平克.' }
    ],
    family: [
        { word: 'Father', phonetic: '/ˈfɑːðə(r)/', homophone: '法泽', meaning: '父亲', sentence: 'Father is my hero.', translation: '爸爸是我的英雄。', homophoneSentence: '法泽is麦黑柔.' },
        { word: 'Mother', phonetic: '/ˈmʌðə(r)/', homophone: '马泽', meaning: '母亲', sentence: 'Mother cooks for us.', translation: '妈妈为我们做饭。', homophoneSentence: '马泽库克斯for啊斯.' },
        { word: 'Brother', phonetic: '/ˈbrʌðə(r)/', homophone: '布拉泽', meaning: '兄弟', sentence: 'My brother is tall.', translation: '我哥哥很高。', homophoneSentence: '麦布拉泽is套.' },
        { word: 'Sister', phonetic: '/ˈsɪstə(r)/', homophone: '西斯特', meaning: '姐妹', sentence: 'My sister is kind.', translation: '我姐姐很善良。', homophoneSentence: '麦西斯特is凯恩德.' },
        { word: 'Grandfather', phonetic: '/ˈɡrænfɑːðə(r)/', homophone: '格兰德法泽', meaning: '祖父', sentence: 'Grandfather tells stories.', translation: '爷爷讲故事。', homophoneSentence: '格兰德法泽泰尔斯斯托瑞兹.' },
        { word: 'Grandmother', phonetic: '/ˈɡrænmʌðə(r)/', homophone: '格兰德马泽', meaning: '祖母', sentence: 'Grandmother bakes cookies.', translation: '奶奶烤饼干。', homophoneSentence: '格兰德马泽贝克斯库克斯.' },
        { word: 'Son', phonetic: '/sʌn/', homophone: '桑', meaning: '儿子', sentence: 'My son is five.', translation: '我儿子五岁了。', homophoneSentence: '麦桑is法艾夫.' },
        { word: 'Daughter', phonetic: '/ˈdɔːtə(r)/', homophone: '道特', meaning: '女儿', sentence: 'My daughter is cute.', translation: '我女儿很可爱。', homophoneSentence: '麦道特isQ特.' }
    ],
    time: [
        { word: 'Morning', phonetic: '/ˈmɔːnɪŋ/', homophone: '莫宁', meaning: '早晨', sentence: 'Good morning!', translation: '早上好！', homophoneSentence: '古德莫宁!' },
        { word: 'Afternoon', phonetic: '/ˌɑːftəˈnuːn/', homophone: '阿夫特努恩', meaning: '下午', sentence: 'Good afternoon!', translation: '下午好！', homophoneSentence: '古德阿夫特努恩!' },
        { word: 'Evening', phonetic: '/ˈiːvnɪŋ/', homophone: '伊夫宁', meaning: '傍晚', sentence: 'Good evening!', translation: '晚上好！', homophoneSentence: '古德伊夫宁!' },
        { word: 'Night', phonetic: '/naɪt/', homophone: '奈特', meaning: '夜晚', sentence: 'Good night!', translation: '晚安！', homophoneSentence: '古德奈特!' },
        { word: 'Today', phonetic: '/təˈdeɪ/', homophone: '特戴', meaning: '今天', sentence: 'Today is Monday.', translation: '今天是周一。', homophoneSentence: '特戴is曼迪.' },
        { word: 'Tomorrow', phonetic: '/təˈmɒrəʊ/', homophone: '特莫罗', meaning: '明天', sentence: 'See you tomorrow!', translation: '明天见！', homophoneSentence: '希油特莫罗!' },
        { word: 'Yesterday', phonetic: '/ˈjestədeɪ/', homophone: '耶斯特戴', meaning: '昨天', sentence: 'Yesterday was Sunday.', translation: '昨天是周日。', homophoneSentence: '耶斯特戴沃兹桑迪.' },
        { word: 'Week', phonetic: '/wiːk/', homophone: '维克', meaning: '周', sentence: 'A week has seven days.', translation: '一周有七天。', homophoneSentence: '啊维克哈兹赛文戴兹.' },
        { word: 'Month', phonetic: '/mʌnθ/', homophone: '芒斯', meaning: '月', sentence: 'A month has thirty days.', translation: '一个月有三十天。', homophoneSentence: '啊芒斯哈兹色提戴兹.' },
        { word: 'Year', phonetic: '/jɪə(r)/', homophone: '耶', meaning: '年', sentence: 'Happy New Year!', translation: '新年快乐！', homophoneSentence: '嗨皮纽耶!' }
    ],
    food: [
        { word: 'Apple', phonetic: '/ˈæpl/', homophone: '艾坡', meaning: '苹果', sentence: 'An apple a day.', translation: '一天一个苹果。', homophoneSentence: '嗯艾坡啊戴.' },
        { word: 'Banana', phonetic: '/bəˈnɑːnə/', homophone: '巴娜娜', meaning: '香蕉', sentence: 'I like bananas.', translation: '我喜欢香蕉。', homophoneSentence: '爱来克斯巴娜娜z.' },
        { word: 'Bread', phonetic: '/bred/', homophone: '布瑞德', meaning: '面包', sentence: 'I eat bread for breakfast.', translation: '我早餐吃面包。', homophoneSentence: '爱伊特布瑞德佛布瑞克法斯特.' },
        { word: 'Rice', phonetic: '/raɪs/', homophone: '莱斯', meaning: '米饭', sentence: 'Rice is a staple food.', translation: '米饭是主食。', homophoneSentence: '莱斯is啊斯泰普欧福德.' },
        { word: 'Water', phonetic: '/ˈwɔːtə(r)/', homophone: '沃特', meaning: '水', sentence: 'Drink more water!', translation: '多喝水！', homophoneSentence: '准克莫沃特!' },
        { word: 'Milk', phonetic: '/mɪlk/', homophone: '米尔克', meaning: '牛奶', sentence: 'Milk is good for health.', translation: '牛奶对健康有益。', homophoneSentence: '米尔克is古德佛海尔思.' },
        { word: 'Egg', phonetic: '/eɡ/', homophone: '艾格', meaning: '鸡蛋', sentence: 'I eat eggs for breakfast.', translation: '我早餐吃鸡蛋。', homophoneSentence: '爱伊特艾格斯佛布瑞克法斯特.' },
        { word: 'Meat', phonetic: '/miːt/', homophone: '密特', meaning: '肉', sentence: 'Meat gives protein.', translation: '肉类提供蛋白质。', homophoneSentence: '密特吉夫兹普罗廷.' }
    ],
    sentences: [
        { word: 'How are you', phonetic: '/haʊ ɑː juː/', homophone: '好啊 优', meaning: '你好吗', sentence: 'How are you today?', translation: '你今天好吗？', homophoneSentence: '好啊油特戴?' },
        { word: 'I\'m fine', phonetic: '/aɪm faɪn/', homophone: '爱姆 法艾恩', meaning: '我很好', sentence: 'I\'m fine, thank you!', translation: '我很好，谢谢你！', homophoneSentence: '爱姆法艾恩,三克油!' },
        { word: 'Nice to meet you', phonetic: '/naɪs tuː miːt juː/', homophone: '奈斯 图 密特 优', meaning: '很高兴认识你', sentence: 'Nice to meet you too!', translation: '我也很高兴认识你！', homophoneSentence: '奈斯图密特油图!' },
        { word: 'What\'s your name', phonetic: '/wɒts jɔː neɪm/', homophone: '沃茨 尤尔 内姆', meaning: '你叫什么名字', sentence: 'What\'s your name, please?', translation: '请问你叫什么名字？', homophoneSentence: '沃茨尤尔内姆,普利斯?' },
        { word: 'My name is', phonetic: '/maɪ neɪm ɪz/', homophone: '麦 内姆 依兹', meaning: '我的名字是', sentence: 'My name is Tom.', translation: '我叫汤姆。', homophoneSentence: '麦内姆依兹汤姆.' },
        { word: 'I don\'t know', phonetic: '/aɪ dəʊnt nəʊ/', homophone: '爱 东特 偶', meaning: '我不知道', sentence: 'I don\'t know the answer.', translation: '我不知道答案。', homophoneSentence: '爱东特偶则安色.' },
        { word: 'I understand', phonetic: '/aɪ ˌʌndəˈstænd/', homophone: '爱 安德斯坦德', meaning: '我明白了', sentence: 'I understand now!', translation: '我现在明白了！', homophoneSentence: '爱安德斯坦德闹!' },
        { word: 'Please help me', phonetic: '/pliːz help miː/', homophone: '普利斯 海尔普 密', meaning: '请帮帮我', sentence: 'Please help me with this.', translation: '请帮我做这个。', homophoneSentence: '普利斯海尔普密威斯则斯.' }
    ]
};
