const wordDatabase = {
    greetings: [
        { word: 'Morning', phonetic: '/ˈmɔːnɪŋ/', homophone: '莫宁', meaning: '早晨', sentence: 'Good morning!', translation: '早上好！', homophoneSentence: '古德莫宁!' },
        { word: 'Afternoon', phonetic: '/ˌɑːftəˈnuːn/', homophone: '阿夫特努恩', meaning: '下午', sentence: 'Good afternoon!', translation: '下午好！', homophoneSentence: '古德阿夫特努恩!' },
        { word: 'Evening', phonetic: '/ˈiːvnɪŋ/', homophone: '伊夫宁', meaning: '晚上', sentence: 'Good evening!', translation: '晚上好！', homophoneSentence: '古德伊夫宁!' },
        { word: 'Night', phonetic: '/naɪt/', homophone: '奈特', meaning: '夜晚', sentence: 'Good night!', translation: '晚安！', homophoneSentence: '古德奈特!' },
        { word: 'Today', phonetic: '/təˈdeɪ/', homophone: '特戴', meaning: '今天', sentence: 'How are you today?', translation: '你今天好吗？', homophoneSentence: '好啊油特戴?' },
        { word: 'Tomorrow', phonetic: '/təˈmɒrəʊ/', homophone: '特莫柔', meaning: '明天', sentence: 'See you tomorrow!', translation: '明天见！', homophoneSentence: '西优特莫柔!' },
        { word: 'Yesterday', phonetic: '/ˈjestədeɪ/', homophone: '耶斯特戴', meaning: '昨天', sentence: 'I saw you yesterday.', translation: '我昨天看到你了。', homophoneSentence: '爱索油耶斯特戴.' },
        { word: 'Week', phonetic: '/wiːk/', homophone: '威克', meaning: '星期', sentence: 'Have a good week!', translation: '祝你这周愉快！', homophoneSentence: '海夫啊古德威克!' },
        { word: 'Weekend', phonetic: '/ˌwiːkˈend/', homophone: '威肯德', meaning: '周末', sentence: 'Happy weekend!', translation: '周末快乐！', homophoneSentence: '嗨皮威肯德!' },
        { word: 'Monday', phonetic: '/ˈmʌndeɪ/', homophone: '曼戴', meaning: '星期一', sentence: 'See you on Monday!', translation: '星期一见！', homophoneSentence: '西优昂曼戴!' },
        { word: 'Tuesday', phonetic: '/ˈtjuːzdeɪ/', homophone: '丘兹戴', meaning: '星期二', sentence: 'Tuesday meeting.', translation: '星期二开会。', homophoneSentence: '丘兹戴米听.' },
        { word: 'Wednesday', phonetic: '/ˈwenzdeɪ/', homophone: '温兹戴', meaning: '星期三', sentence: 'Happy Wednesday!', translation: '星期三快乐！', homophoneSentence: '嗨皮温兹戴!' },
        { word: 'Thursday', phonetic: '/ˈθɜːzdeɪ/', homophone: '色兹戴', meaning: '星期四', sentence: 'Thursday is busy.', translation: '星期四很忙。', homophoneSentence: '色兹戴is比兹.' },
        { word: 'Friday', phonetic: '/ˈfraɪdeɪ/', homophone: '夫来戴', meaning: '星期五', sentence: 'Happy Friday!', translation: '星期五快乐！', homophoneSentence: '嗨皮夫来戴!' },
        { word: 'Saturday', phonetic: '/ˈsætədeɪ/', homophone: '萨特戴', meaning: '星期六', sentence: 'Saturday is fun!', translation: '星期六很有趣！', homophoneSentence: '萨特戴is范!' },
        { word: 'Sunday', phonetic: '/ˈsʌndeɪ/', homophone: '桑戴', meaning: '星期日', sentence: 'Relax on Sunday.', translation: '星期日放松。', homophoneSentence: '瑞来克斯昂桑戴.' },
        { word: 'January', phonetic: '/ˈdʒænjuəri/', homophone: '詹纽瑞', meaning: '一月', sentence: 'January is cold.', translation: '一月很冷。', homophoneSentence: '詹纽瑞is扣德.' },
        { word: 'February', phonetic: '/ˈfebruəri/', homophone: '夫布鲁瑞', meaning: '二月', sentence: 'February is short.', translation: '二月很短。', homophoneSentence: '夫布鲁瑞is绍特.' },
        { word: 'March', phonetic: '/mɑːtʃ/', homophone: '马奇', meaning: '三月', sentence: 'March is windy.', translation: '三月多风。', homophoneSentence: '马奇is温迪.' },
        { word: 'April', phonetic: '/ˈeɪprəl/', homophone: '艾普柔', meaning: '四月', sentence: 'April showers.', translation: '四月阵雨。', homophoneSentence: '艾普柔绍尔斯.' },
        { word: 'May', phonetic: '/meɪ/', homophone: '梅', meaning: '五月', sentence: 'May is beautiful.', translation: '五月很美。', homophoneSentence: '梅is比欧特夫欧.' },
        { word: 'June', phonetic: '/dʒuːn/', homophone: '均', meaning: '六月', sentence: 'June is warm.', translation: '六月很温暖。', homophoneSentence: '均is沃姆.' },
        { word: 'July', phonetic: '/dʒuˈlaɪ/', homophone: '均来', meaning: '七月', sentence: 'July is hot.', translation: '七月很热。', homophoneSentence: '均来is豪特.' },
        { word: 'August', phonetic: '/ˈɔːɡəst/', homophone: '奥古斯特', meaning: '八月', sentence: 'August vacation.', translation: '八月假期。', homophoneSentence: '奥古斯特沃凯申.' },
        { word: 'September', phonetic: '/sepˈtembə(r)/', homophone: '塞普腾波', meaning: '九月', sentence: 'September school.', translation: '九月开学。', homophoneSentence: '塞普腾波斯古.' },
        { word: 'October', phonetic: '/ɒkˈtəʊbə(r)/', homophone: '奥克托波', meaning: '十月', sentence: 'October leaves.', translation: '十月落叶。', homophoneSentence: '奥克托波利夫兹.' },
        { word: 'November', phonetic: '/nəʊˈvembə(r)/', homophone: '诺文波', meaning: '十一月', sentence: 'November rain.', translation: '十一月雨。', homophoneSentence: '诺文波瑞恩.' },
        { word: 'December', phonetic: '/dɪˈsembə(r)/', homophone: '迪森波', meaning: '十二月', sentence: 'December snow.', translation: '十二月雪。', homophoneSentence: '迪森波斯诺.' },
        { word: 'Spring', phonetic: '/sprɪŋ/', homophone: '斯普林', meaning: '春天', sentence: 'Happy spring!', translation: '春天快乐！', homophoneSentence: '嗨皮斯普林!' },
        { word: 'Summer', phonetic: '/ˈsʌmə(r)/', homophone: '萨默', meaning: '夏天', sentence: 'Enjoy summer!', translation: '享受夏天！', homophoneSentence: '因照伊萨默!' },
        { word: 'Autumn', phonetic: '/ˈɔːtəm/', homophone: '奥腾', meaning: '秋天', sentence: 'Beautiful autumn.', translation: '美丽的秋天。', homophoneSentence: '比欧特夫欧奥腾.' },
        { word: 'Winter', phonetic: '/ˈwɪntə(r)/', homophone: '温特', meaning: '冬天', sentence: 'Cold winter.', translation: '寒冷的冬天。', homophoneSentence: '扣德温特.' },
        { word: 'Sunny', phonetic: '/ˈsʌni/', homophone: '萨尼', meaning: '晴朗的', sentence: 'It's sunny today.', translation: '今天晴朗。', homophoneSentence: '伊茨萨尼特戴.' },
        { word: 'Rainy', phonetic: '/ˈreɪni/', homophone: '瑞尼', meaning: '下雨的', sentence: 'It's rainy today.', translation: '今天下雨。', homophoneSentence: '伊茨瑞尼特戴.' },
        { word: 'Cloudy', phonetic: '/ˈklaʊdi/', homophone: '克劳迪', meaning: '多云的', sentence: 'It's cloudy today.', translation: '今天多云。', homophoneSentence: '伊茨克劳迪特戴.' },
        { word: 'Snowy', phonetic: '/ˈsnəʊi/', homophone: '斯诺伊', meaning: '下雪的', sentence: 'It's snowy today.', translation: '今天下雪。', homophoneSentence: '伊茨斯诺伊特戴.' },
        { word: 'Windy', phonetic: '/ˈwɪndi/', homophone: '温迪', meaning: '有风的', sentence: 'It's windy today.', translation: '今天有风。', homophoneSentence: '伊茨温迪特戴.' },
        { word: 'Hot', phonetic: '/hɒt/', homophone: '豪特', meaning: '热的', sentence: 'It's so hot!', translation: '太热了！', homophoneSentence: '伊茨搜豪特!' },
        { word: 'Cold', phonetic: '/kəʊld/', homophone: '扣德', meaning: '冷的', sentence: 'It's so cold!', translation: '太冷了！', homophoneSentence: '伊茨搜扣德!' },
        { word: 'Warm', phonetic: '/wɔːm/', homophone: '沃姆', meaning: '温暖的', sentence: 'It's warm today.', translation: '今天很温暖。', homophoneSentence: '伊茨沃姆特戴.' },
        { word: 'Cool', phonetic: '/kuːl/', homophone: '库尔', meaning: '凉爽的', sentence: 'It's cool today.', translation: '今天很凉爽。', homophoneSentence: '伊茨库尔特戴.' },
        { word: 'Birthday', phonetic: '/ˈbɜːθdeɪ/', homophone: '波斯戴', meaning: '生日', sentence: 'Happy birthday!', translation: '生日快乐！', homophoneSentence: '嗨皮波斯戴!' },
        { word: 'Holiday', phonetic: '/ˈhɒlədeɪ/', homophone: '豪利戴', meaning: '假期', sentence: 'Happy holiday!', translation: '假期快乐！', homophoneSentence: '嗨皮豪利戴!' },
        { word: 'Vacation', phonetic: '/vəˈkeɪʃn/', homophone: '沃凯申', meaning: '假期', sentence: 'Enjoy your vacation!', translation: '享受你的假期！', homophoneSentence: '因照伊油儿沃凯申!' },
        { word: 'Welcome', phonetic: '/ˈwelkəm/', homophone: '威尔康', meaning: '欢迎', sentence: 'Welcome home!', translation: '欢迎回家！', homophoneSentence: '威尔康厚姆!' },
        { word: 'Farewell', phonetic: '/ˌfeəˈwel/', homophone: '夫尔威尔', meaning: '告别', sentence: 'Farewell, my friend!', translation: '再见，我的朋友！', homophoneSentence: '夫尔威尔麦夫瑞恩德!' },
        { word: 'Greetings', phonetic: '/ɡrɪˈtiːŋz/', homophone: '格瑞听兹', meaning: '问候', sentence: 'Season's greetings!', translation: '节日问候！', homophoneSentence: '西曾兹格瑞听兹!' },
        { word: 'Hey', phonetic: '/heɪ/', homophone: '嘿', meaning: '嘿', sentence: 'Hey, how are you?', translation: '嘿，你好吗？', homophoneSentence: '嘿好啊油?' },
        { word: 'Yo', phonetic: '/jəʊ/', homophone: '哟', meaning: '哟', sentence: 'Yo! What's up?', translation: '哟！怎么了？', homophoneSentence: '哟沃特阿普?' },
        { word: 'Howdy', phonetic: '/ˈhaʊdi/', homophone: '豪迪', meaning: '你好', sentence: 'Howdy partner!', translation: '你好伙伴！', homophoneSentence: '豪迪帕特纳!' },
        { word: 'Cheers', phonetic: '/tʃɪəz/', homophone: '切尔斯', meaning: '干杯', sentence: 'Cheers to us!', translation: '为我们干杯！', homophoneSentence: '切尔斯土阿斯!' },
        { word: 'Take care', phonetic: '/teɪk keə/', homophone: '忒克凯尔', meaning: '保重', sentence: 'Take care!', translation: '保重！', homophoneSentence: '忒克凯尔!' },
        { word: 'Congratulations', phonetic: '/kənˌɡrætʃuˈleɪʃnz/', homophone: '康格雷丘雷申兹', meaning: '恭喜', sentence: 'Congratulations on your success!', translation: '恭喜你的成功！', homophoneSentence: '康格雷丘雷申兹昂油儿色克塞斯!' },
        { word: 'Best wishes', phonetic: '/best ˈwɪʃɪz/', homophone: '百斯特维希兹', meaning: '最美好的祝愿', sentence: 'Best wishes for you!', translation: '给你最美好的祝愿！', homophoneSentence: '百斯特维希兹for油!' },
        { word: 'Get well', phonetic: '/ɡet wel/', homophone: '盖特威尔', meaning: '早日康复', sentence: 'Get well soon!', translation: '早日康复！', homophoneSentence: '盖特威尔苏恩!' },
        { word: 'Bless you', phonetic: '/bles juː/', homophone: '布莱斯优', meaning: '保佑你', sentence: 'Bless you!', translation: '保佑你！', homophoneSentence: '布莱斯优!' },
        { word: 'Have fun', phonetic: '/hæv fʌn/', homophone: '海夫范', meaning: '玩得开心', sentence: 'Have fun!', translation: '玩得开心！', homophoneSentence: '海夫范!' },
        { word: 'Enjoy', phonetic: '/ɪnˈdʒɔɪ/', homophone: '因照伊', meaning: '享受', sentence: 'Enjoy your meal!', translation: '享受你的餐食！', homophoneSentence: '因照伊油儿米尔!' },
        { word: 'Safe trip', phonetic: '/seɪf trɪp/', homophone: '塞夫纯普', meaning: '一路平安', sentence: 'Have a safe trip!', translation: '一路平安！', homophoneSentence: '海夫啊塞夫纯普!' },
        { word: 'Success', phonetic: '/səkˈses/', homophone: '色克塞斯', meaning: '成功', sentence: 'Wish you success!', translation: '祝你成功！', homophoneSentence: '维什油色克塞斯!' },
        { word: 'Happiness', phonetic: '/ˈhæpinəs/', homophone: '嗨皮内斯', meaning: '幸福', sentence: 'Wish you happiness!', translation: '祝你幸福！', homophoneSentence: '维什油嗨皮内斯!' },
        { word: 'Health', phonetic: '/helθ/', homophone: '海尔斯', meaning: '健康', sentence: 'Wish you good health!', translation: '祝你健康！', homophoneSentence: '维什油古德海尔斯!' },
        { word: 'Wealth', phonetic: '/welθ/', homophone: '威尔斯', meaning: '财富', sentence: 'Wish you wealth!', translation: '祝你发财！', homophoneSentence: '维什油威尔斯!' },
        { word: 'Peace', phonetic: '/piːs/', homophone: '皮斯', meaning: '和平', sentence: 'Wish you peace!', translation: '祝你平安！', homophoneSentence: '维什油皮斯!' },
        { word: 'Joy', phonetic: '/dʒɔɪ/', homophone: '卓伊', meaning: '欢乐', sentence: 'Wish you joy!', translation: '祝你欢乐！', homophoneSentence: '维什油卓伊!' },
        { word: 'Absolutely', phonetic: '/ˈæbsəluːtli/', homophone: '艾布索鲁特里', meaning: '绝对', sentence: 'Absolutely! I agree!', translation: '绝对！我同意！', homophoneSentence: '艾布索鲁特里爱阿格瑞!' },
        { word: 'Definitely', phonetic: '/ˈdefɪnətli/', homophone: '戴菲尼特里', meaning: '肯定', sentence: 'Definitely! No doubt!', translation: '肯定！毫无疑问！', homophoneSentence: '戴菲尼特里诺道特!' },
        { word: 'Certainly', phonetic: '/ˈsɜːtnli/', homophone: '色腾利', meaning: '当然', sentence: 'Certainly! My pleasure!', translation: '当然！我的荣幸！', homophoneSentence: '色腾利麦普莱舍!' },
        { word: 'Exactly', phonetic: '/ɪɡˈzæktli/', homophone: '伊格扎克特里', meaning: '正是', sentence: 'Exactly! You are right!', translation: '正是！你说得对！', homophoneSentence: '伊格扎克特里油啊来特!' },
        { word: 'Indeed', phonetic: '/ɪnˈdiːd/', homophone: '因迪德', meaning: '确实', sentence: 'Indeed! That's true!', translation: '确实！那是真的！', homophoneSentence: '因迪德戴茨纯!' },
        { word: 'You bet', phonetic: '/juː bet/', homophone: '优百特', meaning: '当然', sentence: 'You bet! Anytime!', translation: '当然！随时！', homophoneSentence: '优百特安尼泰姆!' },
        { word: 'No problem', phonetic: '/nəʊ ˈprɒbləm/', homophone: '诺普罗布勒姆', meaning: '没问题', sentence: 'No problem! Happy to help!', translation: '没问题！乐意帮忙！', homophoneSentence: '诺普罗布勒姆嗨皮to海尔普!' },
        { word: 'My pleasure', phonetic: '/maɪ ˈpleʒə(r)/', homophone: '麦普莱舍', meaning: '我的荣幸', sentence: 'My pleasure! Anytime!', translation: '我的荣幸！随时！', homophoneSentence: '麦普莱舍安尼泰姆!' },
        { word: 'You're welcome', phonetic: '/jɔː(r) ˈwelkəm/', homophone: '优儿威尔康', meaning: '不客气', sentence: 'You're welcome! Don't mention it!', translation: '不客气！别客气！', homophoneSentence: '优儿威尔康东特门申伊特!' },
        { word: 'Don't mention it', phonetic: '/dəʊnt ˈmenʃn ɪt/', homophone: '东特门申伊特', meaning: '别客气', sentence: 'Don't mention it! Glad to help!', translation: '别客气！很高兴帮忙！', homophoneSentence: '东特门申伊特格拉德to海尔普!' },
        { word: 'Never mind', phonetic: '/ˈnevə(r) maɪnd/', homophone: '奈夫曼德', meaning: '没关系', sentence: 'Never mind! It's okay!', translation: '没关系！没事的！', homophoneSentence: '奈夫曼德伊茨欧凯!' },
        { word: 'It's okay', phonetic: '/ɪts əʊˈkeɪ/', homophone: '伊茨欧凯', meaning: '没事', sentence: 'It's okay! Don't worry!', translation: '没事！别担心！', homophoneSentence: '伊茨欧凯东特沃瑞!' },
        { word: 'No worries', phonetic: '/nəʊ ˈwʌriz/', homophone: '诺沃瑞兹', meaning: '别担心', sentence: 'No worries! All good!', translation: '别担心！一切都好！', homophoneSentence: '诺沃瑞兹奥古德!' },
        { word: 'All good', phonetic: '/ɔːl ɡʊd/', homophone: '奥古德', meaning: '一切都好', sentence: 'All good! No problem!', translation: '一切都好！没问题！', homophoneSentence: '奥古德诺普罗布勒姆!' },
        { word: 'Sounds good', phonetic: '/saʊndz ɡʊd/', homophone: '桑兹古德', meaning: '听起来不错', sentence: 'Sounds good! Let's do it!', translation: '听起来不错！我们开始吧！', homophoneSentence: '桑兹古德来茨度伊特!' },
        { word: 'That's great', phonetic: '/ðæts ɡreɪt/', homophone: '戴茨格瑞特', meaning: '太好了', sentence: 'That's great! Wonderful!', translation: '太好了！太棒了！', homophoneSentence: '戴茨格瑞特旺德夫欧!' },
        { word: 'Awesome', phonetic: '/ˈɔːsəm/', homophone: '奥瑟姆', meaning: '太棒了', sentence: 'Awesome! Fantastic!', translation: '太棒了！极好的！', homophoneSentence: '奥瑟姆范泰斯提克!' },
        { word: 'Fantastic', phonetic: '/fænˈtæstɪk/', homophone: '范泰斯提克', meaning: '极好的', sentence: 'Fantastic! Well done!', translation: '极好的！做得好！', homophoneSentence: '范泰斯提克威尔丹!' },
        { word: 'Wonderful', phonetic: '/ˈwʌndəfl/', homophone: '旺德夫欧', meaning: '精彩的', sentence: 'Wonderful! Amazing!', translation: '精彩的！令人惊叹的！', homophoneSentence: '旺德夫欧阿梅兹英!' },
        { word: 'Amazing', phonetic: '/əˈmeɪzɪŋ/', homophone: '阿梅兹英', meaning: '惊人的', sentence: 'Amazing! Incredible!', translation: '惊人的！不可思议的！', homophoneSentence: '阿梅兹英因克瑞德波欧!' },
        { word: 'Incredible', phonetic: '/ɪnˈkredəbl/', homophone: '因克瑞德波欧', meaning: '不可思议的', sentence: 'Incredible! Unbelievable!', translation: '不可思议的！难以置信！', homophoneSentence: '因克瑞德波欧昂比利夫波欧!' },
        { word: 'Perfect', phonetic: '/ˈpɜːfɪkt/', homophone: '坡佛费克特', meaning: '完美的', sentence: 'Perfect! Couldn't be better!', translation: '完美的！不能再好了！', homophoneSentence: '坡佛费克特库登特比百特!' },
        { word: 'Excellent', phonetic: '/ˈeksələnt/', homophone: '艾克瑟伦特', meaning: '极好的', sentence: 'Excellent! Perfect!', translation: '极好的！完美的！', homophoneSentence: '艾克瑟伦特坡佛费克特!' },
        { word: 'Brilliant', phonetic: '/ˈbrɪliənt/', homophone: '布里连特', meaning: '杰出的', sentence: 'Brilliant! Genius!', translation: '杰出的！天才！', homophoneSentence: '布里连特吉尼尔斯!' },
        { word: 'Superb', phonetic: '/suːˈpɜːb/', homophone: '苏坡布', meaning: '卓越的', sentence: 'Superb! First class!', translation: '卓越的！一流的！', homophoneSentence: '苏坡布佛斯特克拉斯!' },
        { word: 'Marvelous', phonetic: '/ˈmɑːvələs/', homophone: '马夫勒斯', meaning: '极好的', sentence: 'Marvelous! Magnificent!', translation: '极好的！壮丽的！', homophoneSentence: '马夫勒斯马格尼费森特!' },
        { word: 'Terrific', phonetic: '/təˈrɪfɪk/', homophone: '特瑞费克', meaning: '极好的', sentence: 'Terrific! Impressive!', translation: '极好的！令人印象深刻！', homophoneSentence: '特瑞费克因普热斯夫!' },
        { word: 'Fabulous', phonetic: '/ˈfæbjələs/', homophone: '法丘勒斯', meaning: '极好的', sentence: 'Fabulous! Spectacular!', translation: '极好的！壮观的！', homophoneSentence: '法丘勒斯斯佩克泰丘勒!' },
        { word: 'Impressive', phonetic: '/ɪmˈpresɪv/', homophone: '因普热斯夫', meaning: '令人印象深刻的', sentence: 'Impressive! Remarkable!', translation: '令人印象深刻的！非凡的！', homophoneSentence: '因普热斯夫瑞马克波欧!' },
        { word: 'Outstanding', phonetic: '/aʊtˈstændɪŋ/', homophone: '奥特斯丹丁', meaning: '杰出的', sentence: 'Outstanding! Exceptional!', translation: '杰出的！卓越的！', homophoneSentence: '奥特斯丹丁伊克塞普申诺!' },
        { word: 'Magnificent', phonetic: '/mæɡˈnɪfɪsnt/', homophone: '马格尼费森特', meaning: '壮丽的', sentence: 'Magnificent! Grand!', translation: '壮丽的！宏伟的！', homophoneSentence: '马格尼费森特格兰德!' },
        { word: 'Spectacular', phonetic: '/spekˈtækjələ(r)/', homophone: '斯佩克泰丘勒', meaning: '壮观的', sentence: 'Spectacular! Breathtaking!', translation: '壮观的！令人惊叹的！', homophoneSentence: '斯佩克泰丘勒布雷斯泰克英!' },
        { word: 'Stunning', phonetic: '/ˈstʌnɪŋ/', homophone: '斯丹宁', meaning: '令人惊叹的', sentence: 'Stunning! Jaw-dropping!', translation: '令人惊叹的！令人瞠目结舌的！', homophoneSentence: '斯丹宁卓德洛平!' },
        { word: 'Breathtaking', phonetic: '/ˈbreθteɪkɪŋ/', homophone: '布雷斯泰克英', meaning: '令人惊叹的', sentence: 'Breathtaking! Awe-inspiring!', translation: '令人惊叹的！令人敬畏的！', homophoneSentence: '布雷斯泰克英奥因斯派瑞英!' }
    ],
    emotions: [
        { word: 'Happy', phonetic: '/ˈhæpi/', homophone: '嗨皮', meaning: '开心的', sentence: 'I\'m so happy today!', translation: '我今天很开心！', homophoneSentence: '爱姆搜嗨皮特戴!' },
        { word: 'Sad', phonetic: '/sæd/', homophone: '赛德', meaning: '难过的', sentence: 'Don\'t be sad, cheer up!', translation: '别难过，振作起来！', homophoneSentence: '东特比赛德,切尔啊普!' },
        { word: 'Angry', phonetic: '/ˈæŋɡri/', homophone: '安格瑞', meaning: '生气的', sentence: 'He looks very angry!', translation: '他看起来很生气！', homophoneSentence: '希鲁克斯歪瑞安格瑞!' },
        { word: 'Love', phonetic: '/lʌv/', homophone: '拉夫', meaning: '爱', sentence: 'I love you!', translation: '我爱你！', homophoneSentence: '爱拉夫油!' },
        { word: 'Like', phonetic: '/laɪk/', homophone: '来克', meaning: '喜欢', sentence: 'I like apples!', translation: '我喜欢苹果！', homophoneSentence: '爱来克艾坡z!' },
        { word: 'Hate', phonetic: '/heɪt/', homophone: '黑特', meaning: '讨厌', sentence: 'I hate rain!', translation: '我讨厌下雨！', homophoneSentence: '爱黑特瑞恩!' },
        { word: 'Afraid', phonetic: '/əˈfreɪd/', homophone: '阿夫瑞德', meaning: '害怕的', sentence: 'Don\'t be afraid!', translation: '别害怕！', homophoneSentence: '东特比阿夫瑞德!' },
        { word: 'Tired', phonetic: '/ˈtaɪəd/', homophone: '泰厄德', meaning: '累的', sentence: 'I\'m so tired!', translation: '我好累！', homophoneSentence: '爱姆搜泰厄德!' }
    ],
    numbers: [
{ word: 'One', phonetic: '/wʌn/', homophone: '万', meaning: '一', sentence: 'I have one apple.', translation: '我有一个苹果。', homophoneSentence: '爱哈夫万啊普欧.' },,
{ word: 'Two', phonetic: '/tuː/', homophone: '图', meaning: '二', sentence: 'Two plus two equals four.', translation: '二加二等于四。', homophoneSentence: '图普拉斯图一阔尔斯佛.' },,
{ word: 'Three', phonetic: '/θriː/', homophone: '斯瑞', meaning: '三', sentence: 'Three little birds.', translation: '三只小鸟。', homophoneSentence: '斯瑞里特波兹.' },,
{ word: 'Four', phonetic: '/fɔː(r)/', homophone: '佛', meaning: '四', sentence: 'Four seasons a year.', translation: '一年四季。', homophoneSentence: '佛西森兹啊耶.' },,
{ word: 'Five', phonetic: '/faɪv/', homophone: '法艾夫', meaning: '五', sentence: 'Give me five!', translation: '击个掌！', homophoneSentence: '基夫米法艾夫!' },,
{ word: 'Six', phonetic: '/sɪks/', homophone: '西克斯', meaning: '六', sentence: 'Six is a lucky number.', translation: '六是个幸运数字。', homophoneSentence: '西克斯依兹啊拉基南波.' },,
{ word: 'Seven', phonetic: '/ˈsevn/', homophone: '赛文', meaning: '七', sentence: 'Seven days a week.', translation: '一周七天。', homophoneSentence: '赛文戴兹啊维克.' },,
{ word: 'Eight', phonetic: '/eɪt/', homophone: '艾特', meaning: '八', sentence: 'Eight hours sleep.', translation: '八小时睡眠。', homophoneSentence: '艾特阿瓦斯斯利普.' },,
{ word: 'Nine', phonetic: '/naɪn/', homophone: '奈恩', meaning: '九', sentence: 'Nine lives of a cat.', translation: '猫有九条命。', homophoneSentence: '奈恩来夫兹奥夫啊凯特.' },,
{ word: 'Ten', phonetic: '/ten/', homophone: '坦', meaning: '十', sentence: 'Ten fingers on hands.', translation: '双手十指。', homophoneSentence: '坦芬格兹昂汉兹.' },,
{ word: 'Eleven', phonetic: '/ɪˈlevn/', homophone: '伊莱文', meaning: '十一', sentence: 'I have eleven books.', translation: '我有十一本书。', homophoneSentence: '爱哈夫伊莱文布克斯.' },,
{ word: 'Twelve', phonetic: '/twelv/', homophone: '特维尔夫', meaning: '十二', sentence: 'Twelve months a year.', translation: '一年十二个月。', homophoneSentence: '特维尔夫芒斯啊耶.' },,
{ word: 'Thirteen', phonetic: '/ˌθɜːˈtiːn/', homophone: '瑟廷', meaning: '十三', sentence: 'Thirteen is an unlucky number.', translation: '十三是个不吉利的数字。', homophoneSentence: '瑟廷依兹安昂拉基南波.' },,
{ word: 'Fourteen', phonetic: '/ˌfɔːˈtiːn/', homophone: '佛廷', meaning: '十四', sentence: 'I am fourteen years old.', translation: '我十四岁了。', homophoneSentence: '爱阿姆佛廷耶斯欧德.' },,
{ word: 'Fifteen', phonetic: '/ˌfɪfˈtiːn/', homophone: '菲廷', meaning: '十五', sentence: 'Fifteen minutes passed.', translation: '十五分钟过去了。', homophoneSentence: '菲廷米尼特斯帕斯德.' },,
{ word: 'Sixteen', phonetic: '/ˌsɪksˈtiːn/', homophone: '西克斯廷', meaning: '十六', sentence: 'She is sixteen years old.', translation: '她十六岁了。', homophoneSentence: '西依兹西克斯廷耶斯欧德.' },,
{ word: 'Seventeen', phonetic: '/ˌsevnˈtiːn/', homophone: '赛文廷', meaning: '十七', sentence: 'Seventeen students in class.', translation: '班里有十七个学生。', homophoneSentence: '赛文廷斯丢等茨因克莱斯.' },,
{ word: 'Eighteen', phonetic: '/ˌeɪˈtiːn/', homophone: '艾廷', meaning: '十八', sentence: 'Eighteen is the legal age.', translation: '十八岁是法定年龄。', homophoneSentence: '艾廷依兹则里够累吉.' },,
{ word: 'Nineteen', phonetic: '/ˌnaɪnˈtiːn/', homophone: '奈恩廷', meaning: '十九', sentence: 'Nineteen is my lucky number.', translation: '十九是我的幸运数字。', homophoneSentence: '奈恩廷依兹麦拉基南波.' },,
{ word: 'Twenty', phonetic: '/ˈtwenti/', homophone: '湍踢', meaning: '二十', sentence: 'Twenty dollars for that.', translation: '那个二十美元。', homophoneSentence: '湍踢道乐兹佛扎特.' },,
{ word: 'Thirty', phonetic: '/ˈθɜːti/', homophone: '瑟踢', meaning: '三十', sentence: 'Thirty days in April.', translation: '四月有三十天。', homophoneSentence: '瑟踢戴兹因艾普瑞欧.' },,
{ word: 'Forty', phonetic: '/ˈfɔːti/', homophone: '佛踢', meaning: '四十', sentence: 'Forty students in class.', translation: '班里有四十个学生。', homophoneSentence: '佛踢斯丢等茨因克莱斯.' },,
{ word: 'Fifty', phonetic: '/ˈfɪfti/', homophone: '菲夫踢', meaning: '五十', sentence: 'Fifty percent off.', translation: '五折优惠。', homophoneSentence: '菲夫踢波森特奥夫.' },,
{ word: 'Hundred', phonetic: '/ˈhʌndrəd/', homophone: '汉德瑞德', meaning: '百', sentence: 'One hundred percent.', translation: '百分之百。', homophoneSentence: '万汉德瑞德波森特.' },,
{ word: 'Zero', phonetic: '/ˈzɪərəʊ/', homophone: '泽柔', meaning: '零', sentence: 'The temperature is zero.', translation: '温度是零度。', homophoneSentence: '则坦普雷彻依兹泽柔.' },,
{ word: 'Sixty', phonetic: '/ˈsɪksti/', homophone: '西克斯踢', meaning: '六十', sentence: 'Sixty seconds in a minute.', translation: '一分钟六十秒。', homophoneSentence: '西克斯踢赛肯兹因啊米尼特.' },,
{ word: 'Seventy', phonetic: '/ˈsevnti/', homophone: '赛文踢', meaning: '七十', sentence: 'Seventy years old.', translation: '七十岁。', homophoneSentence: '赛文踢耶斯欧德.' },,
{ word: 'Eighty', phonetic: '/ˈeɪti/', homophone: '艾踢', meaning: '八十', sentence: 'Eighty people came.', translation: '八十个人来了。', homophoneSentence: '艾踢皮普欧凯姆.' },,
{ word: 'Ninety', phonetic: '/ˈnaɪnti/', homophone: '奈恩踢', meaning: '九十', sentence: 'Ninety percent done.', translation: '完成了百分之九十。', homophoneSentence: '奈恩踢波森特丹.' },,
{ word: 'Thousand', phonetic: '/ˈθaʊznd/', homophone: '萨赞德', meaning: '千', sentence: 'One thousand dollars.', translation: '一千美元。', homophoneSentence: '万萨赞德道乐兹.' },,
{ word: 'Million', phonetic: '/ˈmɪljən/', homophone: '米尔金', meaning: '百万', sentence: 'One million dreams.', translation: '一百万个梦想。', homophoneSentence: '万米尔金追姆兹.' },,
{ word: 'Billion', phonetic: '/ˈbɪljən/', homophone: '比尔金', meaning: '十亿', sentence: 'A billion stars.', translation: '十亿颗星星。', homophoneSentence: '啊比尔金星兹.' },,
{ word: 'First', phonetic: '/fɜːst/', homophone: '弗斯特', meaning: '第一', sentence: 'First come, first served.', translation: '先到先得。', homophoneSentence: '弗斯特卡姆,弗斯特瑟夫德.' },,
{ word: 'Second', phonetic: '/ˈsekənd/', homophone: '赛肯德', meaning: '第二', sentence: 'Second place winner.', translation: '第二名获得者。', homophoneSentence: '赛肯德普雷斯温纳.' },,
{ word: 'Third', phonetic: '/θɜːd/', homophone: '瑟德', meaning: '第三', sentence: 'Third time lucky.', translation: '第三次走运。', homophoneSentence: '瑟德泰姆拉基.' },,
{ word: 'Fourth', phonetic: '/fɔːθ/', homophone: '佛斯', meaning: '第四', sentence: 'Fourth of July.', translation: '七月四日。', homophoneSentence: '佛斯奥夫朱来.' },,
{ word: 'Fifth', phonetic: '/fɪfθ/', homophone: '菲夫斯', meaning: '第五', sentence: 'Fifth floor please.', translation: '请去五楼。', homophoneSentence: '菲夫斯弗洛普利斯.' },,
{ word: 'Sixth', phonetic: '/sɪksθ/', homophone: '西克斯斯', meaning: '第六', sentence: 'June is the sixth month.', translation: '六月是第六个月。', homophoneSentence: '朱恩依兹则西克斯斯芒斯.' },,
{ word: 'Seventh', phonetic: '/ˈsevnθ/', homophone: '赛文斯', meaning: '第七', sentence: 'Seventh day of the week.', translation: '一周的第七天。', homophoneSentence: '赛文斯戴奥夫则维克.' },,
{ word: 'Eighth', phonetic: '/eɪtθ/', homophone: '艾特斯', meaning: '第八', sentence: 'Eighth birthday party.', translation: '八岁生日派对。', homophoneSentence: '艾特斯伯斯戴帕提.' },,
{ word: 'Ninth', phonetic: '/naɪnθ/', homophone: '奈恩斯', meaning: '第九', sentence: 'Ninth grade student.', translation: '九年级学生。', homophoneSentence: '奈恩斯格瑞德斯丢等特.' },,
{ word: 'Tenth', phonetic: '/tenθ/', homophone: '坦斯', meaning: '第十', sentence: 'Tenth anniversary.', translation: '十周年纪念。', homophoneSentence: '坦斯艾尼沃瑟瑞.' },,
{ word: 'Twentieth', phonetic: '/ˈtwentiəθ/', homophone: '湍踢艾斯', meaning: '第二十', sentence: 'Twentieth century.', translation: '二十世纪。', homophoneSentence: '湍踢艾斯森彻瑞.' },,
{ word: 'Thirtieth', phonetic: '/ˈθɜːtiəθ/', homophone: '瑟踢艾斯', meaning: '第三十', sentence: 'Thirtieth birthday.', translation: '三十岁生日。', homophoneSentence: '瑟踢艾斯伯斯戴.' },,
{ word: 'Half', phonetic: '/hɑːf/', homophone: '哈夫', meaning: '一半', sentence: 'Half an hour.', translation: '半小时。', homophoneSentence: '哈夫安阿瓦.' },,
{ word: 'Quarter', phonetic: '/ˈkwɔːtə(r)/', homophone: '阔特', meaning: '四分之一', sentence: 'A quarter past three.', translation: '三点一刻。', homophoneSentence: '啊阔特帕斯特斯瑞.' },,
{ word: 'Double', phonetic: '/ˈdʌbl/', homophone: '达波', meaning: '双倍', sentence: 'Double the amount.', translation: '数量翻倍。', homophoneSentence: '达波则额芒特.' },,
{ word: 'Triple', phonetic: '/ˈtrɪpl/', homophone: '吹波', meaning: '三倍', sentence: 'Triple the price.', translation: '价格三倍。', homophoneSentence: '吹波则普瑞斯.' },,
{ word: 'Pair', phonetic: '/peə(r)/', homophone: '佩尔', meaning: '一对', sentence: 'A pair of shoes.', translation: '一双鞋。', homophoneSentence: '啊佩尔奥夫舒兹.' },,
{ word: 'Dozen', phonetic: '/ˈdʌzn/', homophone: '达赞', meaning: '一打', sentence: 'A dozen eggs.', translation: '一打鸡蛋。', homophoneSentence: '啊达赞艾格斯.' },,
{ word: 'Percent', phonetic: '/pəˈsent/', homophone: '波森特', meaning: '百分比', sentence: 'Ten percent off.', translation: '打九折。', homophoneSentence: '坦波森特奥夫.' },,
{ word: 'Point', phonetic: '/pɔɪnt/', homophone: '坡因特', meaning: '小数点', sentence: 'Three point five.', translation: '三点五。', homophoneSentence: '斯瑞坡因特法艾夫.' },
        { word: 'Ten thousand', phonetic: '/ten ˈθaʊznd/', homophone: '坦萨赞德', meaning: '一万', sentence: 'Ten thousand dollars.', translation: '一万美元。', homophoneSentence: '坦萨赞德道乐兹.' },
        { word: 'Hundred thousand', phonetic: '/ˈhʌndrəd ˈθaʊznd/', homophone: '汉德瑞德萨赞德', meaning: '十万', sentence: 'Hundred thousand people.', translation: '十万人。', homophoneSentence: '汉德瑞德萨赞德皮普欧.' },
        { word: 'Millionaire', phonetic: '/ˌmɪljəˈneə(r)/', homophone: '米尔金艾尔', meaning: '百万富翁', sentence: 'He is a millionaire.', translation: '他是个百万富翁。', homophoneSentence: '希依兹啊米尔金艾尔.' },
        { word: 'Billionaire', phonetic: '/ˌbɪljəˈneə(r)/', homophone: '比尔金艾尔', meaning: '十亿富翁', sentence: 'She is a billionaire.', translation: '她是个十亿富翁。', homophoneSentence: '西依兹啊比尔金艾尔.' },
        { word: 'Trillion', phonetic: '/ˈtrɪljən/', homophone: '吹林', meaning: '万亿', sentence: 'A trillion stars.', translation: '一万亿颗星星。', homophoneSentence: '啊吹林星兹.' },
        { word: 'Quadrillion', phonetic: '/kwɒˈdrɪljən/', homophone: '阔德林', meaning: '千万亿', sentence: 'Quadrillion bytes.', translation: '千万亿字节。', homophoneSentence: '阔德林拜茨.' },
        { word: 'Third', phonetic: '/θɜːd/', homophone: '瑟德', meaning: '三分之一', sentence: 'One third of the cake.', translation: '蛋糕的三分之一。', homophoneSentence: '万瑟德奥夫则凯克.' },
        { word: 'Fourth', phonetic: '/fɔːθ/', homophone: '佛斯', meaning: '四分之一', sentence: 'One fourth of the pizza.', translation: '披萨的四分之一。', homophoneSentence: '万佛斯奥夫则披萨.' },
        { word: 'Fifth', phonetic: '/fɪfθ/', homophone: '菲夫斯', meaning: '五分之一', sentence: 'One fifth of the pie.', translation: '派的五分之一。', homophoneSentence: '万菲夫斯奥夫则派.' },
        { word: 'Sixth', phonetic: '/sɪksθ/', homophone: '西克斯斯', meaning: '六分之一', sentence: 'One sixth of the book.', translation: '书的六分之一。', homophoneSentence: '万西克斯斯奥夫则布克.' },
        { word: 'Seventh', phonetic: '/ˈsevnθ/', homophone: '赛文斯', meaning: '七分之一', sentence: 'One seventh of the class.', translation: '班级的七分之一。', homophoneSentence: '万赛文斯奥夫则克莱斯.' },
        { word: 'Eighth', phonetic: '/eɪtθ/', homophone: '艾特斯', meaning: '八分之一', sentence: 'One eighth of the cake.', translation: '蛋糕的八分之一。', homophoneSentence: '万艾特斯奥夫则凯克.' },
        { word: 'Ninth', phonetic: '/naɪnθ/', homophone: '奈恩斯', meaning: '九分之一', sentence: 'One ninth of the pizza.', translation: '披萨的九分之一。', homophoneSentence: '万奈恩斯奥夫则披萨.' },
        { word: 'Tenth', phonetic: '/tenθ/', homophone: '坦斯', meaning: '十分之一', sentence: 'One tenth of the pie.', translation: '派的十分之一。', homophoneSentence: '万坦斯奥夫则派.' },
        { word: 'Zero point one', phonetic: '/ˈzɪərəʊ pɔɪnt wʌn/', homophone: '泽柔坡因特万', meaning: '零点一', sentence: 'Zero point one percent.', translation: '百分之零点一。', homophoneSentence: '泽柔坡因特万波森特.' },
        { word: 'Zero point five', phonetic: '/ˈzɪərəʊ pɔɪnt faɪv/', homophone: '泽柔坡因特法艾夫', meaning: '零点五', sentence: 'Zero point five meters.', translation: '零点五米。', homophoneSentence: '泽柔坡因特法艾夫米特斯.' },
        { word: 'One point five', phonetic: '/wʌn pɔɪnt faɪv/', homophone: '万坡因特法艾夫', meaning: '一点五', sentence: 'One point five hours.', translation: '一个半小时。', homophoneSentence: '万坡因特法艾夫阿瓦斯.' },
        { word: 'Two point five', phonetic: '/tuː pɔɪnt faɪv/', homophone: '图坡因特法艾夫', meaning: '二点五', sentence: 'Two point five miles.', translation: '二点五英里。', homophoneSentence: '图坡因特法艾夫迈尔斯.' },
        { word: 'Three point five', phonetic: '/θriː pɔɪnt faɪv/', homophone: '斯瑞坡因特法艾夫', meaning: '三点五', sentence: 'Three point five kilograms.', translation: '三点五公斤。', homophoneSentence: '斯瑞坡因特法艾夫基楼格拉姆斯.' },
        { word: 'Addition', phonetic: '/əˈdɪʃn/', homophone: '阿迪申', meaning: '加法', sentence: 'Addition is easy.', translation: '加法很简单。', homophoneSentence: '阿迪申依兹伊兹.' },
        { word: 'Subtraction', phonetic: '/səbˈtrækʃn/', homophone: '萨布拽克申', meaning: '减法', sentence: 'Subtraction is simple.', translation: '减法很简单。', homophoneSentence: '萨布拽克申依兹辛普尔.' },
        { word: 'Multiplication', phonetic: '/ˌmʌltɪplɪˈkeɪʃn/', homophone: '马尔踢普利凯申', meaning: '乘法', sentence: 'Multiplication tables.', translation: '乘法表。', homophoneSentence: '马尔踢普利凯申泰布尔兹.' },
        { word: 'Division', phonetic: '/dɪˈvɪʒn/', homophone: '迪维申', meaning: '除法', sentence: 'Division can be hard.', translation: '除法可能很难。', homophoneSentence: '迪维申坎比哈德.' },
        { word: 'Equals', phonetic: '/ˈiːkwəlz/', homophone: '伊阔尔斯', meaning: '等于', sentence: 'Two plus two equals four.', translation: '二加二等于四。', homophoneSentence: '图普拉斯图伊阔尔斯佛.' },
        { word: 'Plus', phonetic: '/plʌs/', homophone: '普拉斯', meaning: '加', sentence: 'Three plus four equals seven.', translation: '三加四等于七。', homophoneSentence: '斯瑞普拉斯佛伊阔尔斯赛文.' },
        { word: 'Minus', phonetic: '/ˈmaɪnəs/', homophone: '麦纳斯', meaning: '减', sentence: 'Five minus three equals two.', translation: '五减三等于二。', homophoneSentence: '法艾夫麦纳斯斯瑞伊阔尔斯图.' },
        { word: 'Times', phonetic: '/taɪmz/', homophone: '泰姆斯', meaning: '乘', sentence: 'Three times four equals twelve.', translation: '三乘四等于十二。', homophoneSentence: '斯瑞泰姆斯佛伊阔尔斯特维尔夫.' },
        { word: 'Divide', phonetic: '/dɪˈvaɪd/', homophone: '迪外德', meaning: '除', sentence: 'Twelve divided by three equals four.', translation: '十二除以三等于四。', homophoneSentence: '特维尔夫迪外德拜斯瑞伊阔尔斯佛.' },
        { word: 'Square', phonetic: '/skweə(r)/', homophone: '斯阔尔', meaning: '平方', sentence: 'Three squared is nine.', translation: '三的平方是九。', homophoneSentence: '斯瑞斯阔尔的依兹奈恩.' },
        { word: 'Cube', phonetic: '/kjuːb/', homophone: '丘布', meaning: '立方', sentence: 'Two cubed is eight.', translation: '二的立方是八。', homophoneSentence: '图丘布的依兹艾特.' },
        { word: 'Square root', phonetic: '/skweə ruːt/', homophone: '斯阔尔如特', meaning: '平方根', sentence: 'The square root of nine is three.', translation: '九的平方根是三。', homophoneSentence: '则斯阔尔如特奥夫奈恩依兹斯瑞.' },
        { word: 'Kilogram', phonetic: '/ˈkɪləɡræm/', homophone: '基楼格拉姆', meaning: '公斤', sentence: 'One kilogram of apples.', translation: '一公斤苹果。', homophoneSentence: '万基楼格拉姆奥夫艾坡z.' },
        { word: 'Gram', phonetic: '/ɡræm/', homophone: '格拉姆', meaning: '克', sentence: 'One gram of sugar.', translation: '一克糖。', homophoneSentence: '万格拉姆奥夫苏格.' },
        { word: 'Kilometer', phonetic: '/kɪˈlɒmɪtə(r)/', homophone: '基楼米特', meaning: '公里', sentence: 'One kilometer away.', translation: '一公里远。', homophoneSentence: '万基楼米特阿威.' },
        { word: 'Meter', phonetic: '/ˈmiːtə(r)/', homophone: '米特', meaning: '米', sentence: 'One meter tall.', translation: '一米高。', homophoneSentence: '万米特套.' },
        { word: 'Centimeter', phonetic: '/ˈsentɪmiːtə(r)/', homophone: '森提米特', meaning: '厘米', sentence: 'One centimeter long.', translation: '一厘米长。', homophoneSentence: '万森提米特长.' },
        { word: 'Millimeter', phonetic: '/ˈmɪlimiːtə(r)/', homophone: '米里米特', meaning: '毫米', sentence: 'One millimeter thick.', translation: '一毫米厚。', homophoneSentence: '万米里米特西克.' },
        { word: 'Liter', phonetic: '/ˈliːtə(r)/', homophone: '里特', meaning: '升', sentence: 'One liter of water.', translation: '一升水。', homophoneSentence: '万里特奥夫沃特.' },
        { word: 'Milliliter', phonetic: '/ˈmɪliliːtə(r)/', homophone: '米里里特', meaning: '毫升', sentence: 'One milliliter of medicine.', translation: '一毫升药。', homophoneSentence: '万米里里特奥夫麦迪森.' },
        { word: 'Kilowatt', phonetic: '/ˈkɪləwɒt/', homophone: '基楼瓦特', meaning: '千瓦', sentence: 'One kilowatt power.', translation: '一千瓦功率。', homophoneSentence: '万基楼瓦特泡尔.' },
        { word: 'Watt', phonetic: '/wɒt/', homophone: '瓦特', meaning: '瓦', sentence: 'One watt bulb.', translation: '一瓦灯泡。', homophoneSentence: '万瓦特布尔布.' },
        { word: 'Second', phonetic: '/ˈsekənd/', homophone: '赛肯德', meaning: '秒', sentence: 'One second please.', translation: '请等一秒。', homophoneSentence: '万赛肯德普利斯.' },
        { word: 'Minute', phonetic: '/ˈmɪnɪt/', homophone: '米尼特', meaning: '分钟', sentence: 'One minute wait.', translation: '等一分钟。', homophoneSentence: '万米尼特威特.' },
        { word: 'Hour', phonetic: '/ˈaʊə(r)/', homophone: '阿瓦', meaning: '小时', sentence: 'One hour later.', translation: '一小时后。', homophoneSentence: '万阿瓦雷特.' },
        { word: 'Day', phonetic: '/deɪ/', homophone: '戴', meaning: '天', sentence: 'One day off.', translation: '休息一天。', homophoneSentence: '万戴奥夫.' },
        { word: 'Week', phonetic: '/wiːk/', homophone: '维克', meaning: '周', sentence: 'One week vacation.', translation: '一周假期。', homophoneSentence: '万维克沃凯申.' },
        { word: 'Month', phonetic: '/mʌnθ/', homophone: '芒斯', meaning: '月', sentence: 'One month ago.', translation: '一个月前。', homophoneSentence: '万芒斯阿狗.' },
        { word: 'Year', phonetic: '/jɪə(r)/', homophone: '耶', meaning: '年', sentence: 'One year old.', translation: '一岁。', homophoneSentence: '万耶欧德.' },
        { word: 'Decade', phonetic: '/ˈdekeɪd/', homophone: '德凯德', meaning: '十年', sentence: 'One decade later.', translation: '十年后。', homophoneSentence: '万德凯德雷特.' },
        { word: 'Century', phonetic: '/ˈsentʃəri/', homophone: '森彻瑞', meaning: '世纪', sentence: 'One century ago.', translation: '一个世纪前。', homophoneSentence: '万森彻瑞阿狗.' },
        { word: 'Millennium', phonetic: '/mɪˈleniəm/', homophone: '米伦尼姆', meaning: '千年', sentence: 'One millennium history.', translation: '一千年历史。', homophoneSentence: '万米伦尼姆历史.' },
        { word: 'Dollar', phonetic: '/ˈdɒlə(r)/', homophone: '道乐', meaning: '美元', sentence: 'One dollar bill.', translation: '一美元纸币。', homophoneSentence: '万道乐比尔.' },
        { word: 'Cent', phonetic: '/sent/', homophone: '森特', meaning: '美分', sentence: 'One cent coin.', translation: '一美分硬币。', homophoneSentence: '万森特扣因.' },
        { word: 'Pound', phonetic: '/paʊnd/', homophone: '磅', meaning: '英镑', sentence: 'One pound note.', translation: '一英镑纸币。', homophoneSentence: '万磅诺特.' },
        { word: 'Penny', phonetic: '/ˈpeni/', homophone: '佩尼', meaning: '便士', sentence: 'One penny coin.', translation: '一便士硬币。', homophoneSentence: '万佩尼扣因.' },
        { word: 'Euro', phonetic: '/ˈjʊərəʊ/', homophone: '优柔', meaning: '欧元', sentence: 'One euro coin.', translation: '一欧元硬币。', homophoneSentence: '万优柔扣因.' },
        { word: 'Yen', phonetic: '/jen/', homophone: ' yen', meaning: '日元', sentence: 'One yen coin.', translation: '一日元硬币。', homophoneSentence: '万 yen 扣因.' },
        { word: 'Eleventh', phonetic: '/ɪˈlevnθ/', homophone: '伊莱文斯', meaning: '第十一', sentence: 'Eleventh hour.', translation: '最后时刻。', homophoneSentence: '伊莱文斯阿瓦.' },
        { word: 'Twelfth', phonetic: '/twelfθ/', homophone: '特维尔夫斯', meaning: '第十二', sentence: 'Twelfth night.', translation: '第十二夜。', homophoneSentence: '特维尔夫斯奈特.' },
        { word: 'Thirteenth', phonetic: '/ˌθɜːˈtiːnθ/', homophone: '瑟廷斯', meaning: '第十三', sentence: 'Thirteenth floor.', translation: '十三楼。', homophoneSentence: '瑟廷斯弗洛.' },
        { word: 'Fourteenth', phonetic: '/ˌfɔːˈtiːnθ/', homophone: '佛廷斯', meaning: '第十四', sentence: 'Fourteenth birthday.', translation: '十四岁生日。', homophoneSentence: '佛廷斯伯斯戴.' },
        { word: 'Fifteenth', phonetic: '/ˌfɪfˈtiːnθ/', homophone: '菲廷斯', meaning: '第十五', sentence: 'Fifteenth of March.', translation: '三月十五日。', homophoneSentence: '菲廷斯奥夫马奇.' },
        { word: 'Sixteenth', phonetic: '/ˌsɪksˈtiːnθ/', homophone: '西克斯廷斯', meaning: '第十六', sentence: 'Sixteenth century.', translation: '十六世纪。', homophoneSentence: '西克斯廷斯森彻瑞.' },
        { word: 'Seventeenth', phonetic: '/ˌsevnˈtiːnθ/', homophone: '赛文廷斯', meaning: '第十七', sentence: 'Seventeenth chapter.', translation: '第十七章。', homophoneSentence: '赛文廷斯查普特.' },
        { word: 'Eighteenth', phonetic: '/ˌeɪˈtiːnθ/', homophone: '艾廷斯', meaning: '第十八', sentence: 'Eighteenth century.', translation: '十八世纪。', homophoneSentence: '艾廷斯森彻瑞.' },
        { word: 'Nineteenth', phonetic: '/ˌnaɪnˈtiːnθ/', homophone: '奈恩廷斯', meaning: '第十九', sentence: 'Nineteenth century.', translation: '十九世纪。', homophoneSentence: '奈恩廷斯森彻瑞.' },
        { word: 'Twentieth', phonetic: '/ˈtwentiəθ/', homophone: '湍踢艾斯', meaning: '第二十', sentence: 'Twentieth century.', translation: '二十世纪。', homophoneSentence: '湍踢艾斯森彻瑞.' },
        { word: 'Thirtieth', phonetic: '/ˈθɜːtiəθ/', homophone: '瑟踢艾斯', meaning: '第三十', sentence: 'Thirtieth birthday.', translation: '三十岁生日。', homophoneSentence: '瑟踢艾斯伯斯戴.' },
        { word: 'Fortieth', phonetic: '/ˈfɔːtiəθ/', homophone: '佛踢艾斯', meaning: '第四十', sentence: 'Fortieth anniversary.', translation: '四十周年纪念。', homophoneSentence: '佛踢艾斯艾尼沃瑟瑞.' },
        { word: 'Fiftieth', phonetic: '/ˈfɪftiəθ/', homophone: '菲夫踢艾斯', meaning: '第五十', sentence: 'Fiftieth birthday.', translation: '五十岁生日。', homophoneSentence: '菲夫踢艾斯伯斯戴.' },
        { word: 'Sixtieth', phonetic: '/ˈsɪkstiəθ/', homophone: '西克斯踢艾斯', meaning: '第六十', sentence: 'Sixtieth anniversary.', translation: '六十周年纪念。', homophoneSentence: '西克斯踢艾斯艾尼沃瑟瑞.' },
        { word: 'Seventieth', phonetic: '/ˈsevntiəθ/', homophone: '赛文踢艾斯', meaning: '第七十', sentence: 'Seventieth birthday.', translation: '七十岁生日。', homophoneSentence: '赛文踢艾斯伯斯戴.' },
        { word: 'Eightieth', phonetic: '/ˈeɪtiəθ/', homophone: '艾踢艾斯', meaning: '第八十', sentence: 'Eightieth anniversary.', translation: '八十周年纪念。', homophoneSentence: '艾踢艾斯艾尼沃瑟瑞.' },
        { word: 'Ninetieth', phonetic: '/ˈnaɪntiəθ/', homophone: '奈恩踢艾斯', meaning: '第九十', sentence: 'Ninetieth birthday.', translation: '九十岁生日。', homophoneSentence: '奈恩踢艾斯伯斯戴.' },
        { word: 'Hundredth', phonetic: '/ˈhʌndrədθ/', homophone: '汉德瑞德斯', meaning: '第一百', sentence: 'Hundredth day.', translation: '第一百天。', homophoneSentence: '汉德瑞德斯戴.' },
        { word: 'Single', phonetic: '/ˈsɪŋɡl/', homophone: '辛格', meaning: '单个', sentence: 'Single room.', translation: '单人间。', homophoneSentence: '辛格如姆.' },
        { word: 'Double', phonetic: '/ˈdʌbl/', homophone: '达波', meaning: '双倍', sentence: 'Double room.', translation: '双人间。', homophoneSentence: '达波如姆.' },
        { word: 'Triple', phonetic: '/ˈtrɪpl/', homophone: '吹波', meaning: '三倍', sentence: 'Triple bonus.', translation: '三倍奖金。', homophoneSentence: '吹波波纳斯.' },
        { word: 'Quadruple', phonetic: '/ˈkwɒdrʊpl/', homophone: '阔朱波', meaning: '四倍', sentence: 'Quadruple the price.', translation: '价格四倍。', homophoneSentence: '阔朱波则普瑞斯.' },
        { word: 'Quintuple', phonetic: '/ˈkwɪntjʊpl/', homophone: '昆丘波', meaning: '五倍', sentence: 'Quintuple the amount.', translation: '数量五倍。', homophoneSentence: '昆丘波则额芒特.' },
        { word: 'Sextuple', phonetic: '/ˈsekstjʊpl/', homophone: '塞克斯丘波', meaning: '六倍', sentence: 'Sextuple the profit.', translation: '利润六倍。', homophoneSentence: '塞克斯丘波则普罗菲特.' },
        { word: 'Septuple', phonetic: '/ˈseptjʊpl/', homophone: '塞普丘波', meaning: '七倍', sentence: 'Septuple the sales.', translation: '销售额七倍。', homophoneSentence: '塞普丘波则塞尔斯.' },
        { word: 'Octuple', phonetic: '/ˈɒktjʊpl/', homophone: '奥克丘波', meaning: '八倍', sentence: 'Octuple the speed.', translation: '速度八倍。', homophoneSentence: '奥克丘波则斯皮德.' },
        { word: 'Nonuple', phonetic: '/ˈnɒnjʊpl/', homophone: '农丘波', meaning: '九倍', sentence: 'Nonuple the output.', translation: '产量九倍。', homophoneSentence: '农丘波则奥普特普特.' },
        { word: 'Decuple', phonetic: '/ˈdekjʊpl/', homophone: '德丘波', meaning: '十倍', sentence: 'Decuple the income.', translation: '收入十倍。', homophoneSentence: '德丘波则因卡姆.' }
    ],
    colors: [
        { word: 'Red', phonetic: '/red/', homophone: '瑞德', meaning: '红色', sentence: 'The rose is red.', translation: '玫瑰是红色的。', homophoneSentence: '则柔兹瑞德.' },
        { word: 'Blue', phonetic: '/bluː/', homophone: '布鲁', meaning: '蓝色', sentence: 'The sky is blue.', translation: '天空是蓝色的。', homophoneSentence: '则斯凯is布鲁.' },
        { word: 'Green', phonetic: '/ɡriːn/', homophone: '格林', meaning: '绿色', sentence: 'The grass is green.', translation: '草是绿色的。', homophoneSentence: '则格拉斯is格林.' },
        { word: 'Yellow', phonetic: '/ˈjeləʊ/', homophone: '耶喽', meaning: '黄色', sentence: 'The sun is yellow.', translation: '太阳是黄色的。', homophoneSentence: '则桑is耶喽.' },
        { word: 'Black', phonetic: '/blæk/', homophone: '布莱克', meaning: '黑色', sentence: 'The cat is black.', translation: '猫是黑色的。', homophoneSentence: '则凯特is布莱克.' },
        { word: 'White', phonetic: '/waɪt/', homophone: '怀特', meaning: '白色', sentence: 'Snow is white.', translation: '雪是白色的。', homophoneSentence: '斯诺is怀特.' },
        { word: 'Orange', phonetic: '/ˈɒrɪndʒ/', homophone: '奥润吉', meaning: '橙色', sentence: 'Oranges are orange.', translation: '橙子是橙色的。', homophoneSentence: '奥润吉兹啊奥润吉.' },
        { word: 'Pink', phonetic: '/pɪŋk/', homophone: '平克', meaning: '粉色', sentence: 'The flower is pink.', translation: '花是粉色的。', homophoneSentence: '则夫劳尔is平克.' },
        { word: 'Purple', phonetic: '/ˈpɜːpl/', homophone: '坡普尔', meaning: '紫色', sentence: 'Grapes are purple.', translation: '葡萄是紫色的。', homophoneSentence: '格雷普斯啊坡普尔.' },
        { word: 'Brown', phonetic: '/braʊn/', homophone: '布劳恩', meaning: '棕色', sentence: 'Chocolate is brown.', translation: '巧克力是棕色的。', homophoneSentence: '巧克雷特is布劳恩.' },
        { word: 'Gray', phonetic: '/ɡreɪ/', homophone: '格雷', meaning: '灰色', sentence: 'The elephant is gray.', translation: '大象是灰色的。', homophoneSentence: '则艾利芬特is格雷.' },
        { word: 'Silver', phonetic: '/ˈsɪlvə(r)/', homophone: '西尔弗', meaning: '银色', sentence: 'The ring is silver.', translation: '戒指是银色的。', homophoneSentence: '则林is西尔弗.' },
        { word: 'Gold', phonetic: '/ɡəʊld/', homophone: '勾德', meaning: '金色', sentence: 'The medal is gold.', translation: '奖牌是金色的。', homophoneSentence: '则麦德is勾德.' },
        { word: 'Beige', phonetic: '/beɪʒ/', homophone: '贝日', meaning: '米色', sentence: 'The wall is beige.', translation: '墙壁是米色的。', homophoneSentence: '则沃尔is贝日.' },
        { word: 'Navy', phonetic: '/ˈneɪvi/', homophone: '内维', meaning: '藏青色', sentence: 'His suit is navy.', translation: '他的西装是藏青色的。', homophoneSentence: '嘿斯苏特is内维.' },
        { word: 'Teal', phonetic: '/tiːl/', homophone: '提尔', meaning: '青绿色', sentence: 'The dress is teal.', translation: '这条裙子是青绿色的。', homophoneSentence: '则拽斯is提尔.' },
        { word: 'Maroon', phonetic: '/məˈruːn/', homophone: '马鲁恩', meaning: '栗色', sentence: 'The car is maroon.', translation: '这辆车是栗色的。', homophoneSentence: '则卡is马鲁恩.' },
        { word: 'Bronze', phonetic: '/brɒnz/', homophone: '布朗兹', meaning: '青铜色', sentence: 'The medal is bronze.', translation: '奖牌是青铜色的。', homophoneSentence: '则麦斗is布朗兹.' },
        { word: 'Copper', phonetic: '/ˈkɒpə(r)/', homophone: '卡珀', meaning: '铜色', sentence: 'The pipe is copper.', translation: '管道是铜色的。', homophoneSentence: '则派普is卡珀.' },
        { word: 'Cyan', phonetic: '/ˈsaɪən/', homophone: '赛恩', meaning: '青色', sentence: 'The sky is cyan.', translation: '天空是青色的。', homophoneSentence: '则斯凯is赛恩.' },
        { word: 'Magenta', phonetic: '/məˈdʒentə/', homophone: '马真塔', meaning: '洋红色', sentence: 'The flower is magenta.', translation: '花是洋红色的。', homophoneSentence: '则弗劳尔is马真塔.' },
        { word: 'Turquoise', phonetic: '/ˈtɜːkwɔɪz/', homophone: '特克沃伊兹', meaning: '绿松石色', sentence: 'The stone is turquoise.', translation: '石头是绿松石色的。', homophoneSentence: '则斯通is特克沃伊兹.' },
        { word: 'Olive', phonetic: '/ˈɒlɪv/', homophone: '奥利弗', meaning: '橄榄色', sentence: 'The leaf is olive.', translation: '叶子是橄榄色的。', homophoneSentence: '则利夫is奥利弗.' },
        { word: 'Ivory', phonetic: '/ˈaɪvəri/', homophone: '艾沃瑞', meaning: '象牙色', sentence: 'The piano is ivory.', translation: '钢琴是象牙色的。', homophoneSentence: '则皮安诺is艾沃瑞.' },
        { word: 'Khaki', phonetic: '/ˈkɑːki/', homophone: '卡其', meaning: '卡其色', sentence: 'The pants are khaki.', translation: '裤子是卡其色的。', homophoneSentence: '则潘ts啊卡其.' }
    ],
    family: [
        { word: 'Father', phonetic: '/ˈfɑːðə(r)/', homophone: '法泽', meaning: '父亲', sentence: 'Father is my hero.', translation: '爸爸是我的英雄。', homophoneSentence: '法泽is麦黑柔.' },
        { word: 'Mother', phonetic: '/ˈmʌðə(r)/', homophone: '马泽', meaning: '母亲', sentence: 'Mother cooks for us.', translation: '妈妈为我们做饭。', homophoneSentence: '马泽库克斯for啊斯.' },
        { word: 'Brother', phonetic: '/ˈbrʌðə(r)/', homophone: '布拉泽', meaning: '兄弟', sentence: 'My brother is tall.', translation: '我哥哥很高。', homophoneSentence: '麦布拉泽is套.' },
        { word: 'Sister', phonetic: '/ˈsɪstə(r)/', homophone: '西斯特', meaning: '姐妹', sentence: 'My sister is kind.', translation: '我姐姐很善良。', homophoneSentence: '麦西斯特is凯恩德.' },
        { word: 'Grandfather', phonetic: '/ˈɡrænfɑːðə(r)/', homophone: '格兰德法泽', meaning: '祖父', sentence: 'Grandfather tells stories.', translation: '爷爷讲故事。', homophoneSentence: '格兰德法泽泰尔斯斯托瑞兹.' },
        { word: 'Grandmother', phonetic: '/ˈɡrænmʌðə(r)/', homophone: '格兰德马泽', meaning: '祖母', sentence: 'Grandmother bakes cookies.', translation: '奶奶烤饼干。', homophoneSentence: '格兰德马泽贝克斯库克斯.' },
        { word: 'Son', phonetic: '/sʌn/', homophone: '桑', meaning: '儿子', sentence: 'My son is five.', translation: '我儿子五岁了。', homophoneSentence: '麦桑is法艾夫.' },
        { word: 'Daughter', phonetic: '/ˈdɔːtə(r)/', homophone: '道特', meaning: '女儿', sentence: 'My daughter is cute.', translation: '我女儿很可爱。', homophoneSentence: '麦道特isQ特.' },
        { word: 'Uncle', phonetic: '/ˈʌŋkl/', homophone: '昂克', meaning: '叔叔', sentence: 'My uncle is funny.', translation: '我叔叔很有趣。', homophoneSentence: '麦昂克is法尼.' },
        { word: 'Aunt', phonetic: '/ɑːnt/', homophone: '昂特', meaning: '阿姨', sentence: 'My aunt is nice.', translation: '我阿姨很好。', homophoneSentence: '麦昂特is奈斯.' },
        { word: 'Cousin', phonetic: '/ˈkʌzn/', homophone: '卡森', meaning: '表兄弟', sentence: 'My cousin is tall.', translation: '我表兄弟很高。', homophoneSentence: '麦卡森is套.' },
        { word: 'Nephew', phonetic: '/ˈnefjuː/', homophone: '内夫尤', meaning: '侄子', sentence: 'My nephew is smart.', translation: '我侄子很聪明。', homophoneSentence: '麦内夫尤is斯马特.' },
        { word: 'Niece', phonetic: '/niːs/', homophone: '尼斯', meaning: '侄女', sentence: 'My niece is lovely.', translation: '我侄女很可爱。', homophoneSentence: '麦尼斯is拉夫利.' },
        { word: 'Grandma', phonetic: '/ˈɡrænmɑː/', homophone: '格兰德玛', meaning: '奶奶', sentence: 'Grandma loves cookies.', translation: '奶奶喜欢做饼干。', homophoneSentence: '格兰德玛拉夫兹库克斯.' },
        { word: 'Grandpa', phonetic: '/ˈɡrænpɑː/', homophone: '格兰德帕', meaning: '爷爷', sentence: 'Grandpa likes fishing.', translation: '爷爷喜欢钓鱼。', homophoneSentence: '格兰德帕莱克斯菲兴.' },
        { word: 'Brother-in-law', phonetic: '/ˈbrʌðər ɪn lɔː/', homophone: '布拉泽因劳', meaning: '姐夫', sentence: 'My brother-in-law is kind.', translation: '我姐夫很善良。', homophoneSentence: '麦布拉泽因劳is凯恩德.' },
        { word: 'Sister-in-law', phonetic: '/ˈsɪstər ɪn lɔː/', homophone: '西斯特因劳', meaning: '嫂子', sentence: 'My sister-in-law is pretty.', translation: '我嫂子很漂亮。', homophoneSentence: '麦西斯特因劳is普瑞提.' },
        { word: 'Son-in-law', phonetic: '/ˈsʌn ɪn lɔː/', homophone: '桑因劳', meaning: '女婿', sentence: 'My son-in-law is helpful.', translation: '我女婿很乐于助人。', homophoneSentence: '麦桑因劳is海尔普夫.' },
        { word: 'Daughter-in-law', phonetic: '/ˈdɔːtər ɪn lɔː/', homophone: '道特因劳', meaning: '儿媳', sentence: 'My daughter-in-law is gentle.', translation: '我儿媳很温柔。', homophoneSentence: '麦道特因劳is金托.' },
        { word: 'Father-in-law', phonetic: '/ˈfɑːðər ɪn lɔː/', homophone: '法泽因劳', meaning: '岳父', sentence: 'My father-in-law is strict.', translation: '我岳父很严格。', homophoneSentence: '麦法泽因劳is斯垂克特.' },
        { word: 'Mother-in-law', phonetic: '/ˈmʌðər ɪn lɔː/', homophone: '马泽因劳', meaning: '岳母', sentence: 'My mother-in-law is warm.', translation: '我岳母很热情。', homophoneSentence: '麦马泽因劳is沃姆.' },
        { word: 'Stepfather', phonetic: '/ˈstepfɑːðər/', homophone: '斯泰普法泽', meaning: '继父', sentence: 'My stepfather is good.', translation: '我继父很好。', homophoneSentence: '麦斯泰普法泽is古德.' },
        { word: 'Stepmother', phonetic: '/ˈstepmʌðər/', homophone: '斯泰普马泽', meaning: '继母', sentence: 'My stepmother is caring.', translation: '我继母很关心人。', homophoneSentence: '麦斯泰普马泽is凯瑞英.' },
        { word: 'Stepbrother', phonetic: '/ˈstepbrʌðər/', homophone: '斯泰普布拉泽', meaning: '继兄弟', sentence: 'My stepbrother is cool.', translation: '我继兄弟很酷。', homophoneSentence: '麦斯泰普布拉泽is酷.' },
        { word: 'Stepsister', phonetic: '/ˈstepsɪstər/', homophone: '斯泰普西斯特', meaning: '继姐妹', sentence: 'My stepsister is sweet.', translation: '我继姐妹很甜美。', homophoneSentence: '麦斯泰普西斯特is斯威特.' },
        { word: 'Godfather', phonetic: '/ˈɡɒdfɑːðər/', homophone: '高德法泽', meaning: '教父', sentence: 'My godfather is wise.', translation: '我教父很明智。', homophoneSentence: '麦高德法泽is外斯.' },
        { word: 'Godmother', phonetic: '/ˈɡɒdmʌðər/', homophone: '高德马泽', meaning: '教母', sentence: 'My godmother is kind.', translation: '我教母很善良。', homophoneSentence: '麦高德马泽is凯恩德.' }
    ],
    time: [
        { word: 'Morning', phonetic: '/ˈmɔːnɪŋ/', homophone: '莫宁', meaning: '早晨', sentence: 'Good morning!', translation: '早上好！', homophoneSentence: '古德莫宁!' },
        { word: 'Afternoon', phonetic: '/ˌɑːftəˈnuːn/', homophone: '阿夫特努恩', meaning: '下午', sentence: 'Good afternoon!', translation: '下午好！', homophoneSentence: '古德阿夫特努恩!' },
        { word: 'Evening', phonetic: '/ˈiːvnɪŋ/', homophone: '伊夫宁', meaning: '傍晚', sentence: 'Good evening!', translation: '晚上好！', homophoneSentence: '古德伊夫宁!' },
        { word: 'Night', phonetic: '/naɪt/', homophone: '奈特', meaning: '夜晚', sentence: 'Good night!', translation: '晚安！', homophoneSentence: '古德奈特!' },
        { word: 'Today', phonetic: '/təˈdeɪ/', homophone: '特戴', meaning: '今天', sentence: 'Today is Monday.', translation: '今天是周一。', homophoneSentence: '特戴is曼迪.' },
        { word: 'Tomorrow', phonetic: '/təˈmɒrəʊ/', homophone: '特莫罗', meaning: '明天', sentence: 'See you tomorrow!', translation: '明天见！', homophoneSentence: '希油特莫罗!' },
        { word: 'Yesterday', phonetic: '/ˈjestədeɪ/', homophone: '耶斯特戴', meaning: '昨天', sentence: 'Yesterday was Sunday.', translation: '昨天是周日。', homophoneSentence: '耶斯特戴沃兹桑迪.' },
        { word: 'Week', phonetic: '/wiːk/', homophone: '维克', meaning: '周', sentence: 'A week has seven days.', translation: '一周有七天。', homophoneSentence: '啊维克哈兹赛文戴兹.' },
        { word: 'Month', phonetic: '/mʌnθ/', homophone: '芒斯', meaning: '月', sentence: 'A month has thirty days.', translation: '一个月有三十天。', homophoneSentence: '啊芒斯哈兹色提戴兹.' },
        { word: 'Year', phonetic: '/jɪə(r)/', homophone: '耶', meaning: '年', sentence: 'Happy New Year!', translation: '新年快乐！', homophoneSentence: '嗨皮纽耶!' }
    ],
    food: [
        { word: 'Apple', phonetic: '/ˈæpl/', homophone: '艾坡', meaning: '苹果', sentence: 'An apple a day.', translation: '一天一个苹果。', homophoneSentence: '嗯艾坡啊戴.' },
        { word: 'Banana', phonetic: '/bəˈnɑːnə/', homophone: '巴娜娜', meaning: '香蕉', sentence: 'I like bananas.', translation: '我喜欢香蕉。', homophoneSentence: '爱来克斯巴娜娜z.' },
        { word: 'Bread', phonetic: '/bred/', homophone: '布瑞德', meaning: '面包', sentence: 'I eat bread for breakfast.', translation: '我早餐吃面包。', homophoneSentence: '爱伊特布瑞德佛布瑞克法斯特.' },
        { word: 'Rice', phonetic: '/raɪs/', homophone: '莱斯', meaning: '米饭', sentence: 'Rice is a staple food.', translation: '米饭是主食。', homophoneSentence: '莱斯is啊斯泰普欧福德.' },
        { word: 'Water', phonetic: '/ˈwɔːtə(r)/', homophone: '沃特', meaning: '水', sentence: 'Drink more water!', translation: '多喝水！', homophoneSentence: '准克莫沃特!' },
        { word: 'Milk', phonetic: '/mɪlk/', homophone: '米尔克', meaning: '牛奶', sentence: 'Milk is good for health.', translation: '牛奶对健康有益。', homophoneSentence: '米尔克is古德佛海尔思.' },
        { word: 'Egg', phonetic: '/eɡ/', homophone: '艾格', meaning: '鸡蛋', sentence: 'I eat eggs for breakfast.', translation: '我早餐吃鸡蛋。', homophoneSentence: '爱伊特艾格斯佛布瑞克法斯特.' },
        { word: 'Meat', phonetic: '/miːt/', homophone: '密特', meaning: '肉', sentence: 'Meat gives protein.', translation: '肉类提供蛋白质。', homophoneSentence: '密特吉夫兹普罗廷.' }
    ],
    sentences: [
        { word: 'How are you', phonetic: '/haʊ ɑː juː/', homophone: '好啊 优', meaning: '你好吗', sentence: 'How are you today?', translation: '你今天好吗？', homophoneSentence: '好啊油特戴?' },
        { word: 'I\'m fine', phonetic: '/aɪm faɪn/', homophone: '爱姆 法艾恩', meaning: '我很好', sentence: 'I\'m fine, thank you!', translation: '我很好，谢谢你！', homophoneSentence: '爱姆法艾恩,三克油!' },
        { word: 'Nice to meet you', phonetic: '/naɪs tuː miːt juː/', homophone: '奈斯 图 密特 优', meaning: '很高兴认识你', sentence: 'Nice to meet you too!', translation: '我也很高兴认识你！', homophoneSentence: '奈斯图密特油图!' },
        { word: 'What\'s your name', phonetic: '/wɒts jɔː neɪm/', homophone: '沃茨 尤尔 内姆', meaning: '你叫什么名字', sentence: 'What\'s your name, please?', translation: '请问你叫什么名字？', homophoneSentence: '沃茨尤尔内姆,普利斯?' },
        { word: 'My name is', phonetic: '/maɪ neɪm ɪz/', homophone: '麦 内姆 依兹', meaning: '我的名字是', sentence: 'My name is Tom.', translation: '我叫汤姆。', homophoneSentence: '麦内姆依兹汤姆.' },
        { word: 'I don\'t know', phonetic: '/aɪ dəʊnt nəʊ/', homophone: '爱 东特 偶', meaning: '我不知道', sentence: 'I don\'t know the answer.', translation: '我不知道答案。', homophoneSentence: '爱东特偶则安色.' },
        { word: 'I understand', phonetic: '/aɪ ˌʌndəˈstænd/', homophone: '爱 安德斯坦德', meaning: '我明白了', sentence: 'I understand now!', translation: '我现在明白了！', homophoneSentence: '爱安德斯坦德闹!' },
        { word: 'Please help me', phonetic: '/pliːz help miː/', homophone: '普利斯 海尔普 密', meaning: '请帮帮我', sentence: 'Please help me with this.', translation: '请帮我做这个。', homophoneSentence: '普利斯海尔普密威斯则斯.' }
    ]
};
