const fs = require('fs');

function generateFoodWords() {
    return [
        { word: 'Orange', phonetic: '/ˈɒrɪndʒ/', homophone: '奥林奇', meaning: '橙子', sentence: 'Orange juice is refreshing.', translation: '橙汁很清爽。', homophoneSentence: '奥林奇朱斯is瑞福瑞兴.' },
        { word: 'Grape', phonetic: '/ɡreɪp/', homophone: '格瑞普', meaning: '葡萄', sentence: 'Grapes grow on vines.', translation: '葡萄长在藤上。', homophoneSentence: '格瑞普斯格肉昂外恩z.' },
        { word: 'Strawberry', phonetic: '/ˈstrɔːbəri/', homophone: '斯特罗贝瑞', meaning: '草莓', sentence: 'Strawberries are red and sweet.', translation: '草莓又红又甜。', homophoneSentence: '斯特罗贝瑞斯啊瑞德安德斯威特.' },
        { word: 'Watermelon', phonetic: '/ˈwɔːtəmelən/', homophone: '沃特麦伦', meaning: '西瓜', sentence: 'Watermelon is perfect for summer.', translation: '西瓜是夏天的完美水果。', homophoneSentence: '沃特麦伦is帕费克特佛萨默.' },
        { word: 'Pineapple', phonetic: '/ˈpaɪnæpl/', homophone: '派纳普', meaning: '菠萝', sentence: 'Pineapple tastes sweet and sour.', translation: '菠萝味道酸甜。', homophoneSentence: '派纳普泰斯特斯威特安德萨沃尔.' },
        { word: 'Mango', phonetic: '/ˈmæŋɡəʊ/', homophone: '芒勾', meaning: '芒果', sentence: 'Mango is a tropical fruit.', translation: '芒果是热带水果。', homophoneSentence: '芒勾is啊特罗皮卡尔弗鲁特.' },
        { word: 'Peach', phonetic: '/piːtʃ/', homophone: '皮奇', meaning: '桃子', sentence: 'Peaches are fuzzy outside.', translation: '桃子外面毛茸茸的。', homophoneSentence: '皮奇斯啊法吉奥特赛德.' },
        { word: 'Pear', phonetic: '/peə(r)/', homophone: '佩尔', meaning: '梨', sentence: 'Pears are juicy and sweet.', translation: '梨多汁又甜。', homophoneSentence: '佩尔斯啊朱西安德斯威特.' },
        { word: 'Cherry', phonetic: '/ˈtʃeri/', homophone: '切瑞', meaning: '樱桃', sentence: 'Cherries are small and red.', translation: '樱桃又小又红。', homophoneSentence: '切瑞斯啊斯莫尔安德瑞德.' },
        { word: 'Lemon', phonetic: '/ˈlemən/', homophone: '莱蒙', meaning: '柠檬', sentence: 'Lemon adds flavor to dishes.', translation: '柠檬给菜肴增添风味。', homophoneSentence: '莱蒙艾兹弗雷沃尔图迪希兹.' },
        { word: 'Lime', phonetic: '/laɪm/', homophone: '莱姆', meaning: '青柠', sentence: 'Lime is used in cocktails.', translation: '青柠用于鸡尾酒。', homophoneSentence: '莱姆is优兹德因考克泰尔z.' },
        { word: 'Kiwi', phonetic: '/ˈkiːwi/', homophone: '基维', meaning: '猕猴桃', sentence: 'Kiwi is rich in vitamin C.', translation: '猕猴桃富含维生素C。', homophoneSentence: '基维is瑞奇因维他命C.' },
        { word: 'Plum', phonetic: '/plʌm/', homophone: '普拉姆', meaning: '李子', sentence: 'Plums can be purple or red.', translation: '李子可以是紫色或红色。', homophoneSentence: '普拉姆斯坎比帕普欧尔瑞德.' },
        { word: 'Apricot', phonetic: '/ˈeɪprɪkɒt/', homophone: '艾普瑞科特', meaning: '杏子', sentence: 'Apricots are orange inside.', translation: '杏子里面是橙色的。', homophoneSentence: '艾普瑞科茨啊奥林奇因赛德.' },
        { word: 'Coconut', phonetic: '/ˈkəʊkənʌt/', homophone: '扣扣纳特', meaning: '椰子', sentence: 'Coconut water is healthy.', translation: '椰子水很健康。', homophoneSentence: '扣扣纳特沃特is海尔西.' },
        { word: 'Avocado', phonetic: '/ˌævəˈkɑːdəʊ/', homophone: '阿沃卡多', meaning: '牛油果', sentence: 'Avocado is creamy and nutritious.', translation: '牛油果口感细腻营养丰富。', homophoneSentence: '阿沃卡多is克里米安德纽特里谢斯.' },
        { word: 'Blueberry', phonetic: '/ˈbluːbəri/', homophone: '布鲁贝瑞', meaning: '蓝莓', sentence: 'Blueberries are superfoods.', translation: '蓝莓是超级食物。', homophoneSentence: '布鲁贝瑞斯啊苏帕弗德z.' },
        { word: 'Raspberry', phonetic: '/ˈrɑːzbəri/', homophone: '拉斯贝瑞', meaning: '覆盆子', sentence: 'Raspberries are great in desserts.', translation: '覆盆子很适合做甜点。', homophoneSentence: '拉斯贝瑞斯啊格瑞特因迪泽茨.' },
        { word: 'Blackberry', phonetic: '/ˈblækbəri/', homophone: '布莱克贝瑞', meaning: '黑莓', sentence: 'Blackberries grow wild.', translation: '黑莓野生生长。', homophoneSentence: '布莱克贝瑞斯格肉外尔德.' },
        { word: 'Cantaloupe', phonetic: '/ˈkæntələʊp/', homophone: '坎特洛普', meaning: '哈密瓜', sentence: 'Cantaloupe is sweet and orange.', translation: '哈密瓜又甜又橙。', homophoneSentence: '坎特洛普is斯威特安德奥林奇.' },
        { word: 'Pomegranate', phonetic: '/ˈpɒmɪɡrænɪt/', homophone: '波姆格瑞尼特', meaning: '石榴', sentence: 'Pomegranate seeds are edible.', translation: '石榴籽可以吃。', homophoneSentence: '波姆格瑞尼特西兹啊艾迪布欧.' },
        { word: 'Fig', phonetic: '/fɪɡ/', homophone: '菲格', meaning: '无花果', sentence: 'Figs are naturally sweet.', translation: '无花果天然甜。', homophoneSentence: '菲格斯啊纳彻利斯威特.' },
        { word: 'Date', phonetic: '/deɪt/', homophone: '戴特', meaning: '椰枣', sentence: 'Dates are dried fruits.', translation: '椰枣是干果。', homophoneSentence: '戴茨啊德拉伊德弗鲁茨.' },
        { word: 'Grapefruit', phonetic: '/ˈɡreɪpfruːt/', homophone: '格瑞普弗鲁特', meaning: '西柚', sentence: 'Grapefruit is slightly bitter.', translation: '西柚略带苦味。', homophoneSentence: '格瑞普弗鲁特is斯莱特利比特.' },
        { word: 'Papaya', phonetic: '/pəˈpaɪə/', homophone: '帕帕亚', meaning: '木瓜', sentence: 'Papaya aids digestion.', translation: '木瓜有助于消化。', homophoneSentence: '帕帕亚艾兹达伊杰斯彻恩.' },
        { word: 'Guava', phonetic: '/ˈɡwɑːvə/', homophone: '瓜哇', meaning: '番石榴', sentence: 'Guava has many seeds.', translation: '番石榴有很多籽。', homophoneSentence: '瓜哇哈兹梅尼西兹.' },
        { word: 'Lychee', phonetic: '/ˈlaɪtʃi/', homophone: '莱奇', meaning: '荔枝', sentence: 'Lychee is sweet and fragrant.', translation: '荔枝又甜又香。', homophoneSentence: '莱奇is斯威特安德弗雷格伦特.' },
        { word: 'Dragon fruit', phonetic: '/ˈdræɡən fruːt/', homophone: '德拉根弗鲁特', meaning: '火龙果', sentence: 'Dragon fruit looks exotic.', translation: '火龙果看起来很奇特。', homophoneSentence: '德拉根弗鲁特卢克斯伊格佐蒂克.' },
        { word: 'Passion fruit', phonetic: '/ˈpæʃn fruːt/', homophone: '帕申弗鲁特', meaning: '百香果', sentence: 'Passion fruit is tangy.', translation: '百香果味道浓郁。', homophoneSentence: '帕申弗鲁特is坦吉.' },
        { word: 'Carrot', phonetic: '/ˈkærət/', homophone: '卡罗特', meaning: '胡萝卜', sentence: 'Carrots are good for eyes.', translation: '胡萝卜对眼睛好。', homophoneSentence: '卡罗茨啊古德佛艾兹.' },
        { word: 'Potato', phonetic: '/pəˈteɪtəʊ/', homophone: '珀泰托', meaning: '土豆', sentence: 'Potatoes are versatile.', translation: '土豆用途广泛。', homophoneSentence: '珀泰托兹啊沃萨泰尔.' },
        { word: 'Tomato', phonetic: '/təˈmɑːtəʊ/', homophone: '特玛托', meaning: '番茄', sentence: 'Tomatoes are used in salads.', translation: '番茄用于沙拉。', homophoneSentence: '特玛托兹啊优兹德因萨拉兹.' },
        { word: 'Cucumber', phonetic: '/ˈkjuːkʌmbə(r)/', homophone: '丘卡姆伯', meaning: '黄瓜', sentence: 'Cucumber is refreshing.', translation: '黄瓜很清爽。', homophoneSentence: '丘卡姆伯is瑞福瑞兴.' },
        { word: 'Lettuce', phonetic: '/ˈletɪs/', homophone: '莱蒂斯', meaning: '生菜', sentence: 'Lettuce is used in burgers.', translation: '生菜用于汉堡。', homophoneSentence: '莱蒂斯is优兹德因伯格兹.' },
        { word: 'Spinach', phonetic: '/ˈspɪnɪtʃ/', homophone: '斯皮尼奇', meaning: '菠菜', sentence: 'Spinach is rich in iron.', translation: '菠菜富含铁。', homophoneSentence: '斯皮尼奇is瑞奇因艾恩.' },
        { word: 'Broccoli', phonetic: '/ˈbrɒkəli/', homophone: '布罗克利', meaning: '西兰花', sentence: 'Broccoli is a healthy vegetable.', translation: '西兰花是健康蔬菜。', homophoneSentence: '布罗克利is啊海尔西维吉泰布欧.' },
        { word: 'Cauliflower', phonetic: '/ˈkɒliflaʊə(r)/', homophone: '考利弗劳尔', meaning: '花椰菜', sentence: 'Cauliflower is white.', translation: '花椰菜是白色的。', homophoneSentence: '考利弗劳尔is怀特.' },
        { word: 'Cabbage', phonetic: '/ˈkæbɪdʒ/', homophone: '卡比奇', meaning: '卷心菜', sentence: 'Cabbage is used in coleslaw.', translation: '卷心菜用于凉拌卷心菜。', homophoneSentence: '卡比奇is优兹德因考尔斯劳.' },
        { word: 'Onion', phonetic: '/ˈʌnjən/', homophone: '安尼恩', meaning: '洋葱', sentence: 'Onions add flavor to dishes.', translation: '洋葱给菜肴增添风味。', homophoneSentence: '安尼恩兹艾德弗雷沃尔图迪希兹.' },
        { word: 'Garlic', phonetic: '/ˈɡɑːlɪk/', homophone: '加利克', meaning: '大蒜', sentence: 'Garlic has a strong smell.', translation: '大蒜有强烈的气味。', homophoneSentence: '加利克哈兹啊斯特朗斯麦尔.' },
        { word: 'Ginger', phonetic: '/ˈdʒɪndʒə(r)/', homophone: '金杰', meaning: '姜', sentence: 'Ginger helps with nausea.', translation: '姜有助于缓解恶心。', homophoneSentence: '金杰海尔普斯威斯诺西尔.' },
        { word: 'Pepper', phonetic: '/ˈpepə(r)/', homophone: '佩珀', meaning: '辣椒', sentence: 'Pepper adds spice to food.', translation: '辣椒给食物增添辣味。', homophoneSentence: '佩珀艾兹斯派斯图福德.' },
        { word: 'Bell pepper', phonetic: '/bel ˈpepə(r)/', homophone: '贝尔佩珀', meaning: '甜椒', sentence: 'Bell peppers come in colors.', translation: '甜椒有各种颜色。', homophoneSentence: '贝尔佩珀兹卡姆因卡勒兹.' },
        { word: 'Chili', phonetic: '/ˈtʃɪli/', homophone: '奇利', meaning: '辣椒', sentence: 'Chili is very spicy.', translation: '辣椒很辣。', homophoneSentence: '奇利is歪瑞斯派西.' },
        { word: 'Mushroom', phonetic: '/ˈmʌʃrʊm/', homophone: '马什鲁姆', meaning: '蘑菇', sentence: 'Mushrooms grow in dark places.', translation: '蘑菇在阴暗处生长。', homophoneSentence: '马什鲁姆斯格肉因达克普莱西斯.' },
        { word: 'Corn', phonetic: '/kɔːn/', homophone: '科恩', meaning: '玉米', sentence: 'Corn is a popular snack.', translation: '玉米是受欢迎的零食。', homophoneSentence: '科恩is啊帕皮尤勒斯内克.' },
        { word: 'Pea', phonetic: '/piː/', homophone: '皮', meaning: '豌豆', sentence: 'Peas are small and green.', translation: '豌豆又小又绿。', homophoneSentence: '皮兹啊斯莫尔安德格瑞恩.' },
        { word: 'Bean', phonetic: '/biːn/', homophone: '宾', meaning: '豆子', sentence: 'Beans are high in protein.', translation: '豆类蛋白质含量高。', homophoneSentence: '宾兹啊海因普罗廷.' },
        { word: 'Green bean', phonetic: '/ɡriːn biːn/', homophone: '格瑞恩宾', meaning: '四季豆', sentence: 'Green beans are crunchy.', translation: '四季豆很脆。', homophoneSentence: '格瑞恩宾兹啊克朗奇.' },
        { word: 'Soybean', phonetic: '/ˈsɔɪbiːn/', homophone: '索伊宾', meaning: '大豆', sentence: 'Soybeans make tofu.', translation: '大豆可以做豆腐。', homophoneSentence: '索伊宾兹梅克托夫.' },
        { word: 'Celery', phonetic: '/ˈseləri/', homophone: '塞勒瑞', meaning: '芹菜', sentence: 'Celery is low in calories.', translation: '芹菜热量低。', homophoneSentence: '塞勒瑞is肉因卡路里兹.' },
        { word: 'Eggplant', phonetic: '/ˈeɡplɑːnt/', homophone: '艾格普兰特', meaning: '茄子', sentence: 'Eggplant is purple.', translation: '茄子是紫色的。', homophoneSentence: '艾格普兰特is帕普欧.' },
        { word: 'Zucchini', phonetic: '/zuːˈkiːni/', homophone: '祖基尼', meaning: '西葫芦', sentence: 'Zucchini is a summer squash.', translation: '西葫芦是夏季南瓜。', homophoneSentence: '祖基尼is啊萨默斯夸希.' },
        { word: 'Pumpkin', phonetic: '/ˈpʌmpkɪn/', homophone: '帕姆普金', meaning: '南瓜', sentence: 'Pumpkin pie is delicious.', translation: '南瓜派很好吃。', homophoneSentence: '帕姆普金派is迪里谢斯.' },
        { word: 'Squash', phonetic: '/skwɒʃ/', homophone: '斯夸希', meaning: '南瓜', sentence: 'Squash is nutritious.', translation: '南瓜营养丰富。', homophoneSentence: '斯夸希is纽特里谢斯.' },
        { word: 'Radish', phonetic: '/ˈrædɪʃ/', homophone: '拉迪希', meaning: '萝卜', sentence: 'Radish is crunchy and spicy.', translation: '萝卜又脆又辣。', homophoneSentence: '拉迪希is克朗奇安德斯派西.' },
        { word: 'Turnip', phonetic: '/ˈtɜːnɪp/', homophone: '特尼普', meaning: '芜菁', sentence: 'Turnip is a root vegetable.', translation: '芜菁是根茎蔬菜。', homophoneSentence: '特尼普is啊鲁特维吉泰布欧.' },
        { word: 'Beet', phonetic: '/biːt/', homophone: '比特', meaning: '甜菜', sentence: 'Beets are deep red.', translation: '甜菜是深红色的。', homophoneSentence: '比茨啊迪普瑞德.' },
        { word: 'Asparagus', phonetic: '/əˈspærəɡəs/', homophone: '阿斯帕拉格斯', meaning: '芦笋', sentence: 'Asparagus is a spring vegetable.', translation: '芦笋是春季蔬菜。', homophoneSentence: '阿斯帕拉格斯is啊斯普灵维吉泰布欧.' },
        { word: 'Artichoke', phonetic: '/ˈɑːtɪtʃəʊk/', homophone: '阿蒂乔克', meaning: '洋蓟', sentence: 'Artichoke is unique.', translation: '洋蓟很独特。', homophoneSentence: '阿蒂乔克is尤尼克.' },
        { word: 'Bok choy', phonetic: '/bɒk tʃɔɪ/', homophone: '博克乔伊', meaning: '小白菜', sentence: 'Bok choy is used in stir-fry.', translation: '小白菜用于炒菜。', homophoneSentence: '博克乔伊is优兹德因斯特法瑞.' },
        { word: 'Leek', phonetic: '/liːk/', homophone: '利克', meaning: '韭葱', sentence: 'Leeks are mild onions.', translation: '韭葱是温和的洋葱。', homophoneSentence: '利克斯啊梅尔德安尼恩兹.' },
        { word: 'Okra', phonetic: '/ˈəʊkrə/', homophone: '欧克拉', meaning: '秋葵', sentence: 'Okra is slimy when cooked.', translation: '秋葵煮熟后黏糊糊的。', homophoneSentence: '欧克拉is斯莱米温库克特.' },
        { word: 'Bitter melon', phonetic: '/ˈbɪtə ˈmelən/', homophone: '比特麦伦', meaning: '苦瓜', sentence: 'Bitter melon is healthy.', translation: '苦瓜很健康。', homophoneSentence: '比特麦伦is海尔西.' },
        { word: 'Winter melon', phonetic: '/ˈwɪntə ˈmelən/', homophone: '温特麦伦', meaning: '冬瓜', sentence: 'Winter melon soup is tasty.', translation: '冬瓜汤很好喝。', homophoneSentence: '温特麦伦苏普is泰斯蒂.' },
        { word: 'Bamboo shoot', phonetic: '/bæmˈbuː ʃuːt/', homophone: '班布舒特', meaning: '竹笋', sentence: 'Bamboo shoots are crunchy.', translation: '竹笋很脆。', homophoneSentence: '班布舒茨啊克朗奇.' },
        { word: 'Lotus root', phonetic: '/ˈləʊtəs ruːt/', homophone: '洛特斯鲁特', meaning: '莲藕', sentence: 'Lotus root is crispy.', translation: '莲藕很脆。', homophoneSentence: '洛特斯鲁特is克瑞斯皮.' },
        { word: 'Taro', phonetic: '/ˈtɑːrəʊ/', homophone: '塔罗', meaning: '芋头', sentence: 'Taro is a starchy root.', translation: '芋头是淀粉根茎。', homophoneSentence: '塔罗is啊斯塔奇鲁特.' },
        { word: 'Yam', phonetic: '/jæm/', homophone: '亚姆', meaning: '山药', sentence: 'Yams are similar to sweet potatoes.', translation: '山药类似红薯。', homophoneSentence: '亚姆斯啊西米拉图斯威特珀泰托兹.' },
        { word: 'Sweet potato', phonetic: '/swiːt pəˈteɪtəʊ/', homophone: '斯威特珀泰托', meaning: '红薯', sentence: 'Sweet potatoes are orange inside.', translation: '红薯里面是橙色的。', homophoneSentence: '斯威特珀泰托兹啊奥林奇因赛德.' },
        { word: 'Pork', phonetic: '/pɔːk/', homophone: '波克', meaning: '猪肉', sentence: 'Pork is popular in many cuisines.', translation: '猪肉在许多菜系中很受欢迎。', homophoneSentence: '波克is帕皮尤勒因梅尼奎津z.' },
        { word: 'Beef', phonetic: '/biːf/', homophone: '比夫', meaning: '牛肉', sentence: 'Beef is rich in protein.', translation: '牛肉富含蛋白质。', homophoneSentence: '比夫is瑞奇因普罗廷.' },
        { word: 'Chicken', phonetic: '/ˈtʃɪkɪn/', homophone: '奇肯', meaning: '鸡肉', sentence: 'Chicken is versatile meat.', translation: '鸡肉是多用途的肉类。', homophoneSentence: '奇肯is沃萨泰尔密特.' },
        { word: 'Duck', phonetic: '/dʌk/', homophone: '达克', meaning: '鸭肉', sentence: 'Duck is fatty and flavorful.', translation: '鸭肉肥美多汁。', homophoneSentence: '达克is法蒂安德弗雷沃福欧.' },
        { word: 'Turkey', phonetic: '/ˈtɜːki/', homophone: '特基', meaning: '火鸡肉', sentence: 'Turkey is traditional for Thanksgiving.', translation: '火鸡是感恩节的传统食物。', homophoneSentence: '特基is特拉迪舍纳尔佛森克斯吉文.' },
        { word: 'Lamb', phonetic: '/læm/', homophone: '拉姆', meaning: '羊肉', sentence: 'Lamb has a distinct flavor.', translation: '羊肉有独特的风味。', homophoneSentence: '拉姆哈兹啊迪斯廷克特弗雷沃尔.' },
        { word: 'Mutton', phonetic: '/ˈmʌtn/', homophone: '马特恩', meaning: '成年羊肉', sentence: 'Mutton is stronger than lamb.', translation: '成年羊肉比小羊肉味道更重。', homophoneSentence: '马特恩is斯特朗格赞拉姆.' },
        { word: 'Venison', phonetic: '/ˈvenɪsn/', homophone: '维尼森', meaning: '鹿肉', sentence: 'Venison is lean meat.', translation: '鹿肉是瘦肉。', homophoneSentence: '维尼森is林密特.' },
        { word: 'Rabbit', phonetic: '/ˈræbɪt/', homophone: '拉比特', meaning: '兔肉', sentence: 'Rabbit meat is lean.', translation: '兔肉是瘦肉。', homophoneSentence: '拉比特密特is林.' },
        { word: 'Bacon', phonetic: '/ˈbeɪkən/', homophone: '贝肯', meaning: '培根', sentence: 'Bacon is crispy when fried.', translation: '培根炸过后很脆。', homophoneSentence: '贝肯is克瑞斯皮温弗莱德.' },
        { word: 'Ham', phonetic: '/hæm/', homophone: '哈姆', meaning: '火腿', sentence: 'Ham is cured pork.', translation: '火腿是腌制猪肉。', homophoneSentence: '哈姆is克尤尔德波克.' },
        { word: 'Sausage', phonetic: '/ˈsɒsɪdʒ/', homophone: '索西奇', meaning: '香肠', sentence: 'Sausages come in many flavors.', translation: '香肠有多种口味。', homophoneSentence: '索西奇兹卡姆因梅尼弗雷沃尔z.' },
        { word: 'Hot dog', phonetic: '/hɒt dɒɡ/', homophone: '霍特道格', meaning: '热狗', sentence: 'Hot dogs are popular snacks.', translation: '热狗是受欢迎的零食。', homophoneSentence: '霍特道格兹啊帕皮尤勒斯内克斯.' },
        { word: 'Salami', phonetic: '/səˈlɑːmi/', homophone: '萨拉米', meaning: '萨拉米香肠', sentence: 'Salami is dried sausage.', translation: '萨拉米是干香肠。', homophoneSentence: '萨拉米is德拉伊德索西奇.' },
        { word: 'Prosciutto', phonetic: '/prəˈʃuːtəʊ/', homophone: '普罗舒托', meaning: '意大利火腿', sentence: 'Prosciutto is Italian ham.', translation: '意大利火腿是意大利火腿。', homophoneSentence: '普罗舒托is意大利安哈姆.' },
        { word: 'Fish', phonetic: '/fɪʃ/', homophone: '菲什', meaning: '鱼', sentence: 'Fish is healthy protein.', translation: '鱼是健康的蛋白质。', homophoneSentence: '菲什is海尔西普罗廷.' },
        { word: 'Salmon', phonetic: '/ˈsæmən/', homophone: '萨蒙', meaning: '三文鱼', sentence: 'Salmon is rich in omega-3.', translation: '三文鱼富含欧米伽-3。', homophoneSentence: '萨蒙is瑞奇因欧米伽3.' },
        { word: 'Tuna', phonetic: '/ˈtjuːnə/', homophone: '图纳', meaning: '金枪鱼', sentence: 'Tuna is used in sandwiches.', translation: '金枪鱼用于三明治。', homophoneSentence: '图纳is优兹德因桑维奇兹.' },
        { word: 'Cod', phonetic: '/kɒd/', homophone: '科德', meaning: '鳕鱼', sentence: 'Cod is a white fish.', translation: '鳕鱼是白肉鱼。', homophoneSentence: '科德is啊怀特菲什.' },
        { word: 'Shrimp', phonetic: '/ʃrɪmp/', homophone: '施林普', meaning: '虾', sentence: 'Shrimp is popular in seafood.', translation: '虾在海鲜中很受欢迎。', homophoneSentence: '施林普is帕皮尤勒因西福德.' },
        { word: 'Crab', phonetic: '/kræb/', homophone: '克拉布', meaning: '螃蟹', sentence: 'Crab is delicious steamed.', translation: '螃蟹蒸着吃很美味。', homophoneSentence: '克拉布is迪里谢斯斯蒂姆德.' },
        { word: 'Lobster', phonetic: '/ˈlɒbstə(r)/', homophone: '洛布斯特', meaning: '龙虾', sentence: 'Lobster is a luxury food.', translation: '龙虾是奢侈食物。', homophoneSentence: '洛布斯特is啊拉克舒里福德.' },
        { word: 'Squid', phonetic: '/skwɪd/', homophone: '斯奎德', meaning: '鱿鱼', sentence: 'Squid is chewy when cooked.', translation: '鱿鱼煮熟后有嚼劲。', homophoneSentence: '斯奎德is丘伊温库克特.' },
        { word: 'Octopus', phonetic: '/ˈɒktəpəs/', homophone: '奥克托普斯', meaning: '章鱼', sentence: 'Octopus is popular in sushi.', translation: '章鱼在寿司中很受欢迎。', homophoneSentence: '奥克托普斯is帕皮尤勒因苏希.' },
        { word: 'Oyster', phonetic: '/ˈɔɪstə(r)/', homophone: '奥伊斯特', meaning: '牡蛎', sentence: 'Oysters can be eaten raw.', translation: '牡蛎可以生吃。', homophoneSentence: '奥伊斯特兹坎比伊滕罗.' },
        { word: 'Clam', phonetic: '/klæm/', homophone: '克拉姆', meaning: '蛤蜊', sentence: 'Clams are used in chowder.', translation: '蛤蜊用于杂烩汤。', homophoneSentence: '克拉姆斯啊优兹德因乔德.' },
        { word: 'Mussel', phonetic: '/ˈmʌsl/', homophone: '马索尔', meaning: '贻贝', sentence: 'Mussels are cooked in wine.', translation: '贻贝用酒煮。', homophoneSentence: '马索尔斯啊库克特因外恩.' },
        { word: 'Scallop', phonetic: '/ˈskɒləp/', homophone: '斯卡洛普', meaning: '扇贝', sentence: 'Scallops are tender and sweet.', translation: '扇贝又嫩又甜。', homophoneSentence: '斯卡洛普斯啊坦德尔安德斯威特.' },
        { word: 'Eel', phonetic: '/iːl/', homophone: '伊尔', meaning: '鳗鱼', sentence: 'Eel is used in sushi.', translation: '鳗鱼用于寿司。', homophoneSentence: '伊尔is优兹德因苏希.' },
        { word: 'Trout', phonetic: '/traʊt/', homophone: '特劳特', meaning: '鳟鱼', sentence: 'Trout is a freshwater fish.', translation: '鳟鱼是淡水鱼。', homophoneSentence: '特劳特is啊弗雷什沃特菲什.' },
        { word: 'Mackerel', phonetic: '/ˈmækrəl/', homophone: '麦克瑞尔', meaning: '鲭鱼', sentence: 'Mackerel is an oily fish.', translation: '鲭鱼是油性鱼。', homophoneSentence: '麦克瑞尔is安奥伊利菲什.' },
        { word: 'Sardine', phonetic: '/ˌsɑːˈdiːn/', homophone: '萨丁', meaning: '沙丁鱼', sentence: 'Sardines are small fish.', translation: '沙丁鱼是小鱼。', homophoneSentence: '萨丁兹啊斯莫尔菲什.' },
        { word: 'Anchovy', phonetic: '/ˈæntʃəvi/', homophone: '安乔维', meaning: '凤尾鱼', sentence: 'Anchovies are salty.', translation: '凤尾鱼很咸。', homophoneSentence: '安乔维兹啊索尔蒂.' },
        { word: 'Herring', phonetic: '/ˈherɪŋ/', homophone: '赫林', meaning: '鲱鱼', sentence: 'Herring is often pickled.', translation: '鲱鱼常被腌制。', homophoneSentence: '赫林is奥芬皮克尔德.' },
        { word: 'Flounder', phonetic: '/ˈflaʊndə(r)/', homophone: '弗劳恩德', meaning: '比目鱼', sentence: 'Flounder is a flat fish.', translation: '比目鱼是扁平鱼。', homophoneSentence: '弗劳恩德is啊弗莱特菲什.' },
        { word: 'Sea bass', phonetic: '/siː bæs/', homophone: '西巴斯', meaning: '海鲈鱼', sentence: 'Sea bass is mild and flaky.', translation: '海鲈鱼味道温和肉质松软。', homophoneSentence: '西巴斯is梅尔德安德弗莱基.' },
        { word: 'Tilapia', phonetic: '/tɪˈleɪpiə/', homophone: '蒂拉皮亚', meaning: '罗非鱼', sentence: 'Tilapia is affordable fish.', translation: '罗非鱼是价格实惠的鱼。', homophoneSentence: '蒂拉皮亚is阿福德布欧菲什.' },
        { word: 'Catfish', phonetic: '/ˈkætfɪʃ/', homophone: '卡特菲什', meaning: '鲶鱼', sentence: 'Catfish is popular fried.', translation: '鲶鱼炸着吃很受欢迎。', homophoneSentence: '卡特菲什is帕皮尤勒弗莱德.' },
        { word: 'Wheat', phonetic: '/wiːt/', homophone: '威特', meaning: '小麦', sentence: 'Wheat is used to make flour.', translation: '小麦用于制作面粉。', homophoneSentence: '威特is优兹德图梅克弗劳尔.' },
        { word: 'Oat', phonetic: '/əʊt/', homophone: '欧特', meaning: '燕麦', sentence: 'Oats are eaten for breakfast.', translation: '燕麦作为早餐食用。', homophoneSentence: '欧茨啊伊滕佛布瑞克法斯特.' },
        { word: 'Barley', phonetic: '/ˈbɑːli/', homophone: '巴利', meaning: '大麦', sentence: 'Barley is used in soups.', translation: '大麦用于汤中。', homophoneSentence: '巴利is优兹德因苏普斯.' },
        { word: 'Rye', phonetic: '/raɪ/', homophone: '莱', meaning: '黑麦', sentence: 'Rye bread is dark and dense.', translation: '黑麦面包又黑又密。', homophoneSentence: '莱布瑞德is达克安德登斯.' },
        { word: 'Millet', phonetic: '/ˈmɪlɪt/', homophone: '米利特', meaning: '小米', sentence: 'Millet is a gluten-free grain.', translation: '小米是无麸质谷物。', homophoneSentence: '米利特is啊格鲁滕弗瑞格瑞恩.' },
        { word: 'Quinoa', phonetic: '/ˈkiːnwɑː/', homophone: '基诺瓦', meaning: '藜麦', sentence: 'Quinoa is a superfood.', translation: '藜麦是超级食物。', homophoneSentence: '基诺瓦is啊苏帕福德.' },
        { word: 'Buckwheat', phonetic: '/ˈbʌkwiːt/', homophone: '巴克威特', meaning: '荞麦', sentence: 'Buckwheat is used in noodles.', translation: '荞麦用于面条。', homophoneSentence: '巴克威特is优兹德因努多欧.' },
        { word: 'Noodle', phonetic: '/ˈnuːdl/', homophone: '努多欧', meaning: '面条', sentence: 'Noodles are popular in Asia.', translation: '面条在亚洲很受欢迎。', homophoneSentence: '努多欧兹啊帕皮尤勒因艾希尔.' },
        { word: 'Pasta', phonetic: '/ˈpæstə/', homophone: '帕斯塔', meaning: '意大利面', sentence: 'Pasta comes in many shapes.', translation: '意大利面有多种形状。', homophoneSentence: '帕斯塔卡姆兹因梅尼谢普斯.' },
        { word: 'Spaghetti', phonetic: '/spəˈɡeti/', homophone: '斯帕盖蒂', meaning: '意大利细面', sentence: 'Spaghetti is long and thin.', translation: '意大利细面又长又细。', homophoneSentence: '斯帕盖蒂is朗安德辛.' },
        { word: 'Macaroni', phonetic: '/ˌmækəˈrəʊni/', homophone: '麦卡罗尼', meaning: '通心粉', sentence: 'Macaroni and cheese is popular.', translation: '芝士通心粉很受欢迎。', homophoneSentence: '麦卡罗尼安德奇兹is帕皮尤勒.' },
        { word: 'Lasagna', phonetic: '/ləˈzænjə/', homophone: '拉赞亚', meaning: '千层面', sentence: 'Lasagna has many layers.', translation: '千层面有很多层。', homophoneSentence: '拉赞亚哈兹梅尼莱尔兹.' },
        { word: 'Ravioli', phonetic: '/ˌræviˈɒli/', homophone: '拉维奥利', meaning: '意大利饺子', sentence: 'Ravioli is stuffed pasta.', translation: '意大利饺子是填充面食。', homophoneSentence: '拉维奥利斯is斯塔夫德帕斯塔.' },
        { word: 'Dumpling', phonetic: '/ˈdʌmplɪŋ/', homophone: '当普林', meaning: '饺子', sentence: 'Dumplings are traditional food.', translation: '饺子是传统食物。', homophoneSentence: '当普林兹啊特拉迪舍纳尔福德.' },
        { word: 'Tortilla', phonetic: '/tɔːˈtiːə/', homophone: '托蒂亚', meaning: '玉米饼', sentence: 'Tortillas are used for tacos.', translation: '玉米饼用于墨西哥卷饼。', homophoneSentence: '托蒂亚兹啊优兹德佛塔科斯.' },
        { word: 'Naan', phonetic: '/nɑːn/', homophone: '南', meaning: '印度烤饼', sentence: 'Naan is Indian flatbread.', translation: '印度烤饼是印度扁面包。', homophoneSentence: '南is印迪安弗莱特布瑞德.' },
        { word: 'Pita', phonetic: '/ˈpiːtə/', homophone: '皮塔', meaning: '皮塔饼', sentence: 'Pita bread has a pocket.', translation: '皮塔饼有个口袋。', homophoneSentence: '皮塔布瑞德哈兹啊帕基特.' },
        { word: 'Bagel', phonetic: '/ˈbeɪɡəl/', homophone: '贝果', meaning: '贝果', sentence: 'Bagels are boiled then baked.', translation: '贝果先煮后烤。', homophoneSentence: '贝果兹啊博伊尔德赞贝克特.' },
        { word: 'Croissant', phonetic: '/ˈkrwæsɒ̃/', homophone: '可颂', meaning: '羊角面包', sentence: 'Croissants are flaky and buttery.', translation: '羊角面包又酥又香。', homophoneSentence: '可颂兹啊弗莱基安德巴特瑞.' },
        { word: 'Muffin', phonetic: '/ˈmʌfɪn/', homophone: '马芬', meaning: '马芬', sentence: 'Muffins are quick breads.', translation: '马芬是快速面包。', homophoneSentence: '马芬兹啊奎克布瑞兹.' },
        { word: 'Pancake', phonetic: '/ˈpænkeɪk/', homophone: '潘凯克', meaning: '煎饼', sentence: 'Pancakes are eaten for breakfast.', translation: '煎饼作为早餐食用。', homophoneSentence: '潘凯克斯啊伊滕佛布瑞克法斯特.' },
        { word: 'Waffle', phonetic: '/ˈwɒfl/', homophone: '沃夫欧', meaning: '华夫饼', sentence: 'Waffles have a grid pattern.', translation: '华夫饼有网格图案。', homophoneSentence: '沃夫欧兹哈夫啊格瑞德帕特恩.' },
        { word: 'Toast', phonetic: '/təʊst/', homophone: '托斯特', meaning: '吐司', sentence: 'Toast is browned bread.', translation: '吐司是烤过的面包。', homophoneSentence: '托斯特is布朗德布瑞德.' },
        { word: 'Sandwich', phonetic: '/ˈsænwɪtʃ/', homophone: '桑维奇', meaning: '三明治', sentence: 'Sandwiches are convenient meals.', translation: '三明治是方便的餐点。', homophoneSentence: '桑维奇兹啊肯维尼恩特米尔z.' },
        { word: 'Burger', phonetic: '/ˈbɜːɡə(r)/', homophone: '伯格', meaning: '汉堡', sentence: 'Burgers are fast food.', translation: '汉堡是快餐。', homophoneSentence: '伯格兹啊法斯特福德.' },
        { word: 'Pizza', phonetic: '/ˈpiːtsə/', homophone: '披萨', meaning: '披萨', sentence: 'Pizza is popular worldwide.', translation: '披萨在全球很受欢迎。', homophoneSentence: '披萨is帕皮尤勒沃德瓦伊德.' },
        { word: 'Cheese', phonetic: '/tʃiːz/', homophone: '奇兹', meaning: '奶酪', sentence: 'Cheese comes from milk.', translation: '奶酪来自牛奶。', homophoneSentence: '奇兹卡姆兹弗罗姆米尔克.' },
        { word: 'Butter', phonetic: '/ˈbʌtə(r)/', homophone: '巴特', meaning: '黄油', sentence: 'Butter is made from cream.', translation: '黄油由奶油制成。', homophoneSentence: '巴特is梅德弗罗姆克里姆.' },
        { word: 'Cream', phonetic: '/kriːm/', homophone: '克里姆', meaning: '奶油', sentence: 'Cream is used in desserts.', translation: '奶油用于甜点。', homophoneSentence: '克里姆is优兹德因迪泽茨.' },
        { word: 'Yogurt', phonetic: '/ˈjɒɡət/', homophone: '酸奶', meaning: '酸奶', sentence: 'Yogurt is good for digestion.', translation: '酸奶有助于消化。', homophoneSentence: '酸奶is古德佛达伊杰斯彻恩.' },
        { word: 'Ice cream', phonetic: '/aɪs kriːm/', homophone: '艾斯克里姆', meaning: '冰淇淋', sentence: 'Ice cream is a frozen dessert.', translation: '冰淇淋是冷冻甜点。', homophoneSentence: '艾斯克里姆is啊弗罗森迪泽特.' },
        { word: 'Cake', phonetic: '/keɪk/', homophone: '凯克', meaning: '蛋糕', sentence: 'Cake is served at parties.', translation: '蛋糕在派对上供应。', homophoneSentence: '凯克is瑟夫德阿特帕蒂兹.' },
        { word: 'Cookie', phonetic: '/ˈkʊki/', homophone: '库基', meaning: '曲奇', sentence: 'Cookies are sweet treats.', translation: '曲奇是甜点。', homophoneSentence: '库基兹啊斯威特特里茨.' },
        { word: 'Biscuit', phonetic: '/ˈbɪskɪt/', homophone: '比斯吉特', meaning: '饼干', sentence: 'Biscuits are crunchy snacks.', translation: '饼干是脆的零食。', homophoneSentence: '比斯吉茨啊克朗奇斯内克斯.' },
        { word: 'Chocolate', phonetic: '/ˈtʃɒklət/', homophone: '乔克利特', meaning: '巧克力', sentence: 'Chocolate is loved worldwide.', translation: '巧克力在全球备受喜爱。', homophoneSentence: '乔克利特is拉夫德沃德瓦伊德.' },
        { word: 'Candy', phonetic: '/ˈkændi/', homophone: '坎迪', meaning: '糖果', sentence: 'Candy is sweet and sugary.', translation: '糖果又甜又含糖。', homophoneSentence: '坎迪is斯威特安德舒加瑞.' },
        { word: 'Donut', phonetic: '/ˈdəʊnʌt/', homophone: '多纳特', meaning: '甜甜圈', sentence: 'Donuts are fried pastries.', translation: '甜甜圈是油炸糕点。', homophoneSentence: '多纳茨啊弗莱德佩斯特里兹.' },
        { word: 'Pie', phonetic: '/paɪ/', homophone: '派', meaning: '派', sentence: 'Pie has a crust filling.', translation: '派有酥皮馅料。', homophoneSentence: '派哈兹啊克拉斯特菲林.' },
        { word: 'Tart', phonetic: '/tɑːt/', homophone: '塔特', meaning: '蛋挞', sentence: 'Tarts are small pies.', translation: '蛋挞是小派。', homophoneSentence: '塔茨啊斯莫尔派兹.' },
        { word: 'Pudding', phonetic: '/ˈpʊdɪŋ/', homophone: '普丁', meaning: '布丁', sentence: 'Pudding is a creamy dessert.', translation: '布丁是奶油甜点。', homophoneSentence: '普丁is啊克里米迪泽特.' },
        { word: 'Jelly', phonetic: '/ˈdʒeli/', homophone: '杰利', meaning: '果冻', sentence: 'Jelly is wobbly and sweet.', translation: '果冻又晃又甜。', homophoneSentence: '杰利is沃布利安德斯威特.' },
        { word: 'Jam', phonetic: '/dʒæm/', homophone: '杰姆', meaning: '果酱', sentence: 'Jam is spread on toast.', translation: '果酱涂在吐司上。', homophoneSentence: '杰姆is斯普瑞德昂托斯特.' },
        { word: 'Honey', phonetic: '/ˈhʌni/', homophone: '哈尼', meaning: '蜂蜜', sentence: 'Honey is made by bees.', translation: '蜂蜜由蜜蜂酿造。', homophoneSentence: '哈尼is梅德拜比兹.' },
        { word: 'Sugar', phonetic: '/ˈʃʊɡə(r)/', homophone: '舒格', meaning: '糖', sentence: 'Sugar sweetens food.', translation: '糖给食物增甜。', homophoneSentence: '舒格斯威滕兹福德.' },
        { word: 'Salt', phonetic: '/sɔːlt/', homophone: '索尔特', meaning: '盐', sentence: 'Salt enhances flavor.', translation: '盐增强风味。', homophoneSentence: '索尔特因汉西斯弗雷沃尔.' },
        { word: 'Vinegar', phonetic: '/ˈvɪnɪɡə(r)/', homophone: '维尼格', meaning: '醋', sentence: 'Vinegar is used in pickling.', translation: '醋用于腌制。', homophoneSentence: '维尼格is优兹德因皮克林.' },
        { word: 'Oil', phonetic: '/ɔɪl/', homophone: '奥伊尔', meaning: '油', sentence: 'Oil is used for cooking.', translation: '油用于烹饪。', homophoneSentence: '奥伊尔is优兹德佛库金.' },
        { word: 'Olive oil', phonetic: '/ˈɒlɪv ɔɪl/', homophone: '奥利夫奥伊尔', meaning: '橄榄油', sentence: 'Olive oil is healthy fat.', translation: '橄榄油是健康脂肪。', homophoneSentence: '奥利夫奥伊尔is海尔西法特.' },
        { word: 'Soy sauce', phonetic: '/sɔɪ sɔːs/', homophone: '索伊索斯', meaning: '酱油', sentence: 'Soy sauce adds umami flavor.', translation: '酱油增添鲜味。', homophoneSentence: '索伊索斯艾兹乌玛米弗雷沃尔.' },
        { word: 'Ketchup', phonetic: '/ˈketʃəp/', homophone: '凯查普', meaning: '番茄酱', sentence: 'Ketchup is used on fries.', translation: '番茄酱用于薯条。', homophoneSentence: '凯查普is优兹德昂弗莱兹.' },
        { word: 'Mustard', phonetic: '/ˈmʌstəd/', homophone: '马斯塔德', meaning: '芥末酱', sentence: 'Mustard is spicy and tangy.', translation: '芥末酱又辣又酸。', homophoneSentence: '马斯塔德is斯派西安德坦吉.' },
        { word: 'Mayonnaise', phonetic: '/ˌmeɪəˈneɪz/', homophone: '梅奥内兹', meaning: '蛋黄酱', sentence: 'Mayonnaise is creamy condiment.', translation: '蛋黄酱是奶油调味品。', homophoneSentence: '梅奥内兹is克里米康迪门特.' },
        { word: 'Relish', phonetic: '/ˈrelɪʃ/', homophone: '瑞利希', meaning: '调味酱', sentence: 'Relish adds crunch to hot dogs.', translation: '调味酱给热狗增添脆感。', homophoneSentence: '瑞利希艾兹克朗奇图霍特道格兹.' },
        { word: 'Salsa', phonetic: '/ˈsælsə/', homophone: '萨尔萨', meaning: '莎莎酱', sentence: 'Salsa is spicy tomato sauce.', translation: '莎莎酱是辣番茄酱。', homophoneSentence: '萨尔萨is斯派特玛托索斯.' },
        { word: 'Curry', phonetic: '/ˈkʌri/', homophone: '咖喱', meaning: '咖喱', sentence: 'Curry is a spiced dish.', translation: '咖喱是加香料的菜肴。', homophoneSentence: '咖喱is啊斯派斯特迪希.' },
        { word: 'Cinnamon', phonetic: '/ˈsɪnəmən/', homophone: '辛纳蒙', meaning: '肉桂', sentence: 'Cinnamon is used in baking.', translation: '肉桂用于烘焙。', homophoneSentence: '辛纳蒙is优兹德因贝金.' },
        { word: 'Nutmeg', phonetic: '/ˈnʌtmeɡ/', homophone: '纳特梅格', meaning: '肉豆蔻', sentence: 'Nutmeg adds warmth to dishes.', translation: '肉豆蔻给菜肴增添温暖感。', homophoneSentence: '纳特梅格艾兹沃姆图迪希兹.' },
        { word: 'Clove', phonetic: '/kləʊv/', homophone: '克洛夫', meaning: '丁香', sentence: 'Cloves are aromatic spice.', translation: '丁香是芳香香料。', homophoneSentence: '克洛夫兹啊阿罗麦蒂克斯派斯.' },
        { word: 'Turmeric', phonetic: '/ˈtɜːmərɪk/', homophone: '特梅里克', meaning: '姜黄', sentence: 'Turmeric gives yellow color.', translation: '姜黄赋予黄色。', homophoneSentence: '特梅里克吉夫兹耶洛卡勒.' },
        { word: 'Cumin', phonetic: '/ˈkjuːmɪn/', homophone: '库明', meaning: '孜然', sentence: 'Cumin is used in curry.', translation: '孜然用于咖喱。', homophoneSentence: '库明is优兹德因咖喱.' },
        { word: 'Coriander', phonetic: '/ˌkɒriˈændə(r)/', homophone: '科里安德', meaning: '香菜', sentence: 'Coriander adds fresh flavor.', translation: '香菜增添清新风味。', homophoneSentence: '科里安德艾兹弗雷什弗雷沃尔.' },
        { word: 'Basil', phonetic: '/ˈbæzl/', homophone: '巴兹尔', meaning: '罗勒', sentence: 'Basil is used in pesto.', translation: '罗勒用于青酱。', homophoneSentence: '巴兹尔is优兹德因佩斯托.' },
        { word: 'Oregano', phonetic: '/ˌɒrɪˈɡɑːnəʊ/', homophone: '奥瑞加诺', meaning: '牛至', sentence: 'Oregano is used in pizza.', translation: '牛至用于披萨。', homophoneSentence: '奥瑞加诺is优兹德因披萨.' },
        { word: 'Thyme', phonetic: '/taɪm/', homophone: '泰姆', meaning: '百里香', sentence: 'Thyme is a woody herb.', translation: '百里香是木本草本。', homophoneSentence: '泰姆is啊伍迪赫布.' },
        { word: 'Rosemary', phonetic: '/ˈrəʊzməri/', homophone: '罗斯玛丽', meaning: '迷迭香', sentence: 'Rosemary pairs with lamb.', translation: '迷迭香配羊肉。', homophoneSentence: '罗斯玛丽佩尔斯威斯拉姆.' },
        { word: 'Mint', phonetic: '/mɪnt/', homophone: '明特', meaning: '薄荷', sentence: 'Mint is refreshing.', translation: '薄荷很清爽。', homophoneSentence: '明特is瑞福瑞兴.' },
        { word: 'Parsley', phonetic: '/ˈpɑːsli/', homophone: '帕斯利', meaning: '欧芹', sentence: 'Parsley is used as garnish.', translation: '欧芹用作装饰。', homophoneSentence: '帕斯利is优兹德艾兹加尼希.' },
        { word: 'Dill', phonetic: '/dɪl/', homophone: '迪尔', meaning: '莳萝', sentence: 'Dill is used with fish.', translation: '莳萝配鱼。', homophoneSentence: '迪尔is优兹德威斯菲什.' },
        { word: 'Chive', phonetic: '/tʃaɪv/', homophone: '夏伊夫', meaning: '细香葱', sentence: 'Chives add mild onion flavor.', translation: '细香葱增添温和洋葱味。', homophoneSentence: '夏伊夫兹艾德梅尔德安尼恩弗雷沃尔.' },
        { word: 'Sesame', phonetic: '/ˈsesəmi/', homophone: '塞萨米', meaning: '芝麻', sentence: 'Sesame seeds are used in cooking.', translation: '芝麻用于烹饪。', homophoneSentence: '塞萨米西兹啊优兹德因库金.' },
        { word: 'Poppy seed', phonetic: '/ˈpɒpi siːd/', homophone: '波皮西德', meaning: '罂粟籽', sentence: 'Poppy seeds top bagels.', translation: '罂粟籽撒在贝果上。', homophoneSentence: '波皮西兹托普贝果兹.' },
        { word: 'Sunflower seed', phonetic: '/ˈsʌnflaʊə siːd/', homophone: '桑弗劳尔西德', meaning: '葵花籽', sentence: 'Sunflower seeds are healthy snacks.', translation: '葵花籽是健康零食。', homophoneSentence: '桑弗劳尔西兹啊海尔西斯内克斯.' },
        { word: 'Pumpkin seed', phonetic: '/ˈpʌmpkɪn siːd/', homophone: '帕姆普金西德', meaning: '南瓜籽', sentence: 'Pumpkin seeds are nutritious.', translation: '南瓜籽营养丰富。', homophoneSentence: '帕姆普金西兹啊纽特里谢斯.' },
        { word: 'Almond', phonetic: '/ˈɑːmənd/', homophone: '阿蒙德', meaning: '杏仁', sentence: 'Almonds are healthy nuts.', translation: '杏仁是健康坚果。', homophoneSentence: '阿蒙兹啊海尔西南茨.' },
        { word: 'Walnut', phonetic: '/ˈwɔːlnʌt/', homophone: '沃尔纳特', meaning: '核桃', sentence: 'Walnuts are brain-shaped.', translation: '核桃形状像大脑。', homophoneSentence: '沃尔纳茨啊布雷恩谢普特.' },
        { word: 'Cashew', phonetic: '/ˈkæʃuː/', homophone: '卡舒', meaning: '腰果', sentence: 'Cashews are creamy nuts.', translation: '腰果是奶油味坚果。', homophoneSentence: '卡舒兹啊克里米南茨.' },
        { word: 'Peanut', phonetic: '/ˈpiːnʌt/', homophone: '皮纳特', meaning: '花生', sentence: 'Peanuts are used for butter.', translation: '花生用于制作花生酱。', homophoneSentence: '皮纳茨啊优兹德佛巴特.' },
        { word: 'Pistachio', phonetic: '/pɪˈstɑːʃiəʊ/', homophone: '皮斯塔奇奥', meaning: '开心果', sentence: 'Pistachios are green nuts.', translation: '开心果是绿色坚果。', homophoneSentence: '皮斯塔奇奥兹啊格瑞恩南茨.' },
        { word: 'Hazelnut', phonetic: '/ˈheɪzlnʌt/', homophone: '海泽尔纳特', meaning: '榛子', sentence: 'Hazelnuts are used in chocolate.', translation: '榛子用于巧克力。', homophoneSentence: '海泽尔纳茨啊优兹德因乔克利特.' },
        { word: 'Pecan', phonetic: '/pɪˈkɑːn/', homophone: '皮坎', meaning: '碧根果', sentence: 'Pecans are used in pie.', translation: '碧根果用于派。', homophoneSentence: '皮坎兹啊优兹德因派.' },
        { word: 'Macadamia', phonetic: '/ˌmækəˈdeɪmiə/', homophone: '麦卡迪米亚', meaning: '夏威夷果', sentence: 'Macadamia nuts are buttery.', translation: '夏威夷果有黄油味。', homophoneSentence: '麦卡迪米亚南茨啊巴特瑞.' },
        { word: 'Brazil nut', phonetic: '/brəˈzɪl nʌt/', homophone: '布拉齐尔纳特', meaning: '巴西坚果', sentence: 'Brazil nuts are large.', translation: '巴西坚果很大。', homophoneSentence: '布拉齐尔纳茨啊拉杰.' },
        { word: 'Pine nut', phonetic: '/paɪn nʌt/', homophone: '派恩纳特', meaning: '松子', sentence: 'Pine nuts are used in pesto.', translation: '松子用于青酱。', homophoneSentence: '派恩纳茨啊优兹德因佩斯托.' },
        { word: 'Chestnut', phonetic: '/ˈtʃesnʌt/', homophone: '切斯特纳特', meaning: '栗子', sentence: 'Chestnuts are roasted in winter.', translation: '栗子在冬天烤着吃。', homophoneSentence: '切斯特纳茨啊罗斯特德因温特.' },
        { word: 'Tea', phonetic: '/tiː/', homophone: '提', meaning: '茶', sentence: 'Tea is a popular beverage.', translation: '茶是受欢迎的饮料。', homophoneSentence: '提is啊帕皮尤勒贝沃瑞吉.' },
        { word: 'Coffee', phonetic: '/ˈkɒfi/', homophone: '咖啡', meaning: '咖啡', sentence: 'Coffee gives energy.', translation: '咖啡提供能量。', homophoneSentence: '咖啡吉夫兹恩纳吉.' },
        { word: 'Juice', phonetic: '/dʒuːs/', homophone: '朱斯', meaning: '果汁', sentence: 'Juice is made from fruits.', translation: '果汁由水果制成。', homophoneSentence: '朱斯is梅德弗罗姆弗鲁茨.' },
        { word: 'Soda', phonetic: '/ˈsəʊdə/', homophone: '索达', meaning: '汽水', sentence: 'Soda is carbonated drink.', translation: '汽水是碳酸饮料。', homophoneSentence: '索达is卡博内蒂德德林克.' },
        { word: 'Lemonade', phonetic: '/ˌleməˈneɪd/', homophone: '莱蒙纳德', meaning: '柠檬水', sentence: 'Lemonade is refreshing.', translation: '柠檬水很清爽。', homophoneSentence: '莱蒙纳德is瑞福瑞兴.' },
        { word: 'Smoothie', phonetic: '/ˈsmuːði/', homophone: '斯穆迪', meaning: '冰沙', sentence: 'Smoothies are blended drinks.', translation: '冰沙是混合饮料。', homophoneSentence: '斯穆迪兹啊布伦迪德德林克斯.' },
        { word: 'Milkshake', phonetic: '/ˈmɪlkʃeɪk/', homophone: '米尔克谢克', meaning: '奶昔', sentence: 'Milkshakes are thick and creamy.', translation: '奶昔又浓又滑。', homophoneSentence: '米尔克谢克斯啊西克安德克里米.' },
        { word: 'Hot chocolate', phonetic: '/hɒt ˈtʃɒklət/', homophone: '霍特乔克利特', meaning: '热巧克力', sentence: 'Hot chocolate warms you up.', translation: '热巧克力让你暖和起来。', homophoneSentence: '霍特乔克利特沃姆兹尤阿普.' },
        { word: 'Soup', phonetic: '/suːp/', homophone: '苏普', meaning: '汤', sentence: 'Soup is comforting food.', translation: '汤是令人舒适的食物。', homophoneSentence: '苏普is康弗廷福德.' },
        { word: 'Salad', phonetic: '/ˈsæləd/', homophone: '萨拉德', meaning: '沙拉', sentence: 'Salads are healthy meals.', translation: '沙拉是健康的餐点。', homophoneSentence: '萨拉兹啊海尔西米尔z.' },
        { word: 'Stew', phonetic: '/stjuː/', homophone: '斯图', meaning: '炖菜', sentence: 'Stew is slow-cooked dish.', translation: '炖菜是慢煮菜肴。', homophoneSentence: '斯图is斯洛库克特迪希.' },
        { word: 'Stir-fry', phonetic: '/ˈstɜːfraɪ/', homophone: '斯特法瑞', meaning: '炒菜', sentence: 'Stir-fry is quick cooking.', translation: '炒菜是快速烹饪。', homophoneSentence: '斯特法瑞is奎克库金.' },
        { word: 'Roast', phonetic: '/rəʊst/', homophone: '罗斯特', meaning: '烤肉', sentence: 'Roast is oven-cooked meat.', translation: '烤肉是烤箱烤的肉。', homophoneSentence: '罗斯特is奥文库克特密特.' },
        { word: 'Grill', phonetic: '/ɡrɪl/', homophone: '格里尔', meaning: '烧烤', sentence: 'Grill adds smoky flavor.', translation: '烧烤增添烟熏味。', homophoneSentence: '格里尔艾兹斯莫基弗雷沃尔.' },
        { word: 'Fry', phonetic: '/fraɪ/', homophone: '弗莱', meaning: '油炸', sentence: 'Fry makes food crispy.', translation: '油炸使食物酥脆。', homophoneSentence: '弗莱梅克斯福德克瑞斯皮.' },
        { word: 'Steam', phonetic: '/stiːm/', homophone: '斯蒂姆', meaning: '蒸', sentence: 'Steam keeps nutrients.', translation: '蒸保留营养。', homophoneSentence: '斯蒂姆基普斯纽特里恩茨.' },
        { word: 'Boil', phonetic: '/bɔɪl/', homophone: '博伊尔', meaning: '煮', sentence: 'Boil is simple cooking.', translation: '煮是简单的烹饪。', homophoneSentence: '博伊尔is辛普欧库金.' },
        { word: 'Bake', phonetic: '/beɪk/', homophone: '贝克', meaning: '烘焙', sentence: 'Bake is used for bread.', translation: '烘焙用于面包。', homophoneSentence: '贝克is优兹德佛布瑞德.' },
        { word: 'Appetizer', phonetic: '/ˈæpɪtaɪzə(r)/', homophone: '艾皮泰泽', meaning: '开胃菜', sentence: 'Appetizers start the meal.', translation: '开胃菜开始用餐。', homophoneSentence: '艾皮泰泽兹斯塔特则米尔.' },
        { word: 'Main course', phonetic: '/meɪn kɔːs/', homophone: '梅恩科斯', meaning: '主菜', sentence: 'Main course is the big dish.', translation: '主菜是大菜。', homophoneSentence: '梅恩科斯is则比格迪希.' },
        { word: 'Dessert', phonetic: '/dɪˈzɜːt/', homophone: '迪泽特', meaning: '甜点', sentence: 'Dessert ends the meal.', translation: '甜点结束用餐。', homophoneSentence: '迪泽特恩兹则米尔.' },
        { word: 'Snack', phonetic: '/snæk/', homophone: '斯内克', meaning: '零食', sentence: 'Snacks are small meals.', translation: '零食是小餐。', homophoneSentence: '斯内克斯啊斯莫尔米尔z.' },
        { word: 'Breakfast', phonetic: '/ˈbrekfəst/', homophone: '布瑞克法斯特', meaning: '早餐', sentence: 'Breakfast is morning meal.', translation: '早餐是早晨的餐点。', homophoneSentence: '布瑞克法斯特is莫宁米尔.' },
        { word: 'Lunch', phonetic: '/lʌntʃ/', homophone: '兰奇', meaning: '午餐', sentence: 'Lunch is midday meal.', translation: '午餐是中午的餐点。', homophoneSentence: '兰奇is米德米尔.' },
        { word: 'Dinner', phonetic: '/ˈdɪnə(r)/', homophone: '迪纳', meaning: '晚餐', sentence: 'Dinner is evening meal.', translation: '晚餐是晚上的餐点。', homophoneSentence: '迪纳is伊夫宁米尔.' },
        { word: 'Supper', phonetic: '/ˈsʌpə(r)/', homophone: '萨珀', meaning: '夜宵', sentence: 'Supper is late meal.', translation: '夜宵是晚上的餐点。', homophoneSentence: '萨珀is莱特米尔.' },
        { word: 'Brunch', phonetic: '/brʌntʃ/', homophone: '布兰奇', meaning: '早午餐', sentence: 'Brunch is breakfast and lunch.', translation: '早午餐是早餐和午餐的结合。', homophoneSentence: '布兰奇is布瑞克法斯特安德兰奇.' },
        { word: 'Picnic', phonetic: '/ˈpɪknɪk/', homophone: '皮克尼克', meaning: '野餐', sentence: 'Picnic is outdoor meal.', translation: '野餐是户外用餐。', homophoneSentence: '皮克尼克is奥特多尔米尔.' },
        { word: 'Barbecue', phonetic: '/ˈbɑːbɪkjuː/', homophone: '巴比库', meaning: '烧烤', sentence: 'Barbecue is grilled food.', translation: '烧烤是烤制的食物。', homophoneSentence: '巴比库is格里尔德福德.' },
        { word: 'Buffet', phonetic: '/ˈbʊfeɪ/', homophone: '布菲', meaning: '自助餐', sentence: 'Buffet has many choices.', translation: '自助餐有很多选择。', homophoneSentence: '布菲哈兹梅尼乔伊斯iz.' },
        { word: 'Banquet', phonetic: '/ˈbæŋkwɪt/', homophone: '班奎特', meaning: '宴会', sentence: 'Banquet is formal dinner.', translation: '宴会是正式晚餐。', homophoneSentence: '班奎特is福莫尔迪纳.' },
        { word: 'Feast', phonetic: '/fiːst/', homophone: '菲斯特', meaning: '盛宴', sentence: 'Feast is a large meal.', translation: '盛宴是大餐。', homophoneSentence: '菲斯特is啊拉杰米尔.' },
        { word: 'Recipe', phonetic: '/ˈresɪpi/', homophone: '瑞斯皮', meaning: '食谱', sentence: 'Recipe tells how to cook.', translation: '食谱告诉你怎么烹饪。', homophoneSentence: '瑞斯皮特尔兹豪图库克.' },
        { word: 'Ingredient', phonetic: '/ɪnˈɡriːdiənt/', homophone: '因格瑞迪恩特', meaning: '食材', sentence: 'Ingredients make the dish.', translation: '食材构成菜肴。', homophoneSentence: '因格瑞迪恩茨梅克则迪希.' },
        { word: 'Cuisine', phonetic: '/kwɪˈziːn/', homophone: '奎津', meaning: '烹饪', sentence: 'Cuisine varies by region.', translation: '烹饪因地区而异。', homophoneSentence: '奎津瓦瑞兹拜瑞金.' },
        { word: 'Delicacy', phonetic: '/ˈdelɪkəsi/', homophone: '德利卡西', meaning: '美味', sentence: 'Delicacy is special food.', translation: '美味是特别的食物。', homophoneSentence: '德利卡西is斯佩舍尔福德.' },
        { word: 'Tofu', phonetic: '/ˈtəʊfuː/', homophone: '托夫', meaning: '豆腐', sentence: 'Tofu is made from soybeans.', translation: '豆腐由大豆制成。', homophoneSentence: '托夫is梅德弗罗姆索伊宾z.' },
        { word: 'Tempeh', phonetic: '/ˈtempeɪ/', homophone: '坦佩', meaning: '豆豉', sentence: 'Tempeh is fermented soy.', translation: '豆豉是发酵大豆。', homophoneSentence: '坦佩is弗门特德索伊.' },
        { word: 'Seaweed', phonetic: '/ˈsiːwiːd/', homophone: '西威德', meaning: '海藻', sentence: 'Seaweed is used in sushi.', translation: '海藻用于寿司。', homophoneSentence: '西威德is优兹德因苏希.' },
        { word: 'Nori', phonetic: '/ˈnɔːri/', homophone: '诺里', meaning: '紫菜', sentence: 'Nori wraps sushi rolls.', translation: '紫菜包裹寿司卷。', homophoneSentence: '诺里拉普斯苏希罗尔z.' },
        { word: 'Kimchi', phonetic: '/ˈkɪmtʃi/', homophone: '金奇', meaning: '泡菜', sentence: 'Kimchi is Korean side dish.', translation: '泡菜是韩国配菜。', homophoneSentence: '金奇is科瑞恩赛德迪希.' },
        { word: 'Sauerkraut', phonetic: '/ˈsaʊərkraʊt/', homophone: '萨uer克劳特', meaning: '酸菜', sentence: 'Sauerkraut is fermented cabbage.', translation: '酸菜是发酵卷心菜。', homophoneSentence: '萨uer克劳特is弗门特德卡比奇.' },
        { word: 'Pickle', phonetic: '/ˈpɪkl/', homophone: '皮克欧', meaning: '腌菜', sentence: 'Pickles are preserved vegetables.', translation: '腌菜是腌制蔬菜。', homophoneSentence: '皮克欧兹啊普瑞泽尔维德维吉泰布欧z.' },
        { word: 'Taco', phonetic: '/ˈtɑːkəʊ/', homophone: '塔科', meaning: '墨西哥卷饼', sentence: 'Tacos are Mexican food.', translation: '墨西哥卷饼是墨西哥食物。', homophoneSentence: '塔科兹啊梅克西坎福德.' },
        { word: 'Burrito', phonetic: '/bəˈriːtəʊ/', homophone: '布里托', meaning: '墨西哥卷', sentence: 'Burritos are wrapped tortillas.', translation: '墨西哥卷是包裹的玉米饼。', homophoneSentence: '布里托兹啊拉普特托蒂亚兹.' },
        { word: 'Quesadilla', phonetic: '/ˌkesəˈdiːə/', homophone: '凯萨迪亚', meaning: '墨西哥馅饼', sentence: 'Quesadilla has cheese filling.', translation: '墨西哥馅饼有奶酪馅。', homophoneSentence: '凯萨迪亚哈兹奇兹菲林.' },
        { word: 'Enchilada', phonetic: '/ˌentʃɪˈlɑːdə/', homophone: '恩奇拉达', meaning: '墨西哥卷饼', sentence: 'Enchilada is covered in sauce.', translation: '墨西哥卷饼裹着酱汁。', homophoneSentence: '恩奇拉达is卡弗德因索斯.' },
        { word: 'Sushi', phonetic: '/ˈsuːʃi/', homophone: '苏希', meaning: '寿司', sentence: 'Sushi is Japanese food.', translation: '寿司是日本食物。', homophoneSentence: '苏希is杰帕尼兹福德.' },
        { word: 'Sashimi', phonetic: '/səˈʃiːmi/', homophone: '萨希米', meaning: '生鱼片', sentence: 'Sashimi is raw fish.', translation: '生鱼片是生鱼。', homophoneSentence: '萨希米is罗菲什.' },
        { word: 'Ramen', phonetic: '/ˈrɑːmən/', homophone: '拉面', meaning: '拉面', sentence: 'Ramen is Japanese noodle soup.', translation: '拉面是日本面条汤。', homophoneSentence: '拉面is杰帕尼兹努多欧苏普.' },
        { word: 'Tempura', phonetic: '/ˈtempʊrə/', homophone: '天妇罗', meaning: '天妇罗', sentence: 'Tempura is deep-fried food.', translation: '天妇罗是油炸食物。', homophoneSentence: '天妇罗is迪普弗莱德福德.' },
        { word: 'Pad thai', phonetic: '/pæd taɪ/', homophone: '帕泰', meaning: '泰式炒面', sentence: 'Pad thai is Thai noodle dish.', translation: '泰式炒面是泰国面条菜。', homophoneSentence: '帕泰is泰努多欧迪希.' },
        { word: 'Curry', phonetic: '/ˈkʌri/', homophone: '咖喱', meaning: '咖喱', sentence: 'Curry is popular in India.', translation: '咖喱在印度很受欢迎。', homophoneSentence: '咖喱is帕皮尤勒因印迪尔.' },
        { word: 'Biryani', phonetic: '/bɪˈrjɑːni/', homophone: '比尔亚尼', meaning: '印度香饭', sentence: 'Biryani is spiced rice dish.', translation: '印度香饭是香料米饭。', homophoneSentence: '比尔亚尼is斯派斯特莱斯迪希.' },
        { word: 'Naan', phonetic: '/nɑːn/', homophone: '南', meaning: '印度烤饼', sentence: 'Naan is served with curry.', translation: '印度烤饼配咖喱。', homophoneSentence: '南is瑟夫德威斯咖喱.' },
        { word: 'Falafel', phonetic: '/fəˈlæfl/', homophone: '法拉费', meaning: '炸鹰嘴豆丸子', sentence: 'Falafel is Middle Eastern food.', translation: '炸鹰嘴豆丸子是中东食物。', homophoneSentence: '法拉费is米德尔伊斯特恩福德.' },
        { word: 'Hummus', phonetic: '/ˈhʌməs/', homophone: '胡姆斯', meaning: '鹰嘴豆泥', sentence: 'Hummus is made from chickpeas.', translation: '鹰嘴豆泥由鹰嘴豆制成。', homophoneSentence: '胡姆斯is梅德弗罗姆奇克皮兹.' },
        { word: 'Kebab', phonetic: '/kɪˈbæb/', homophone: '凯巴布', meaning: '烤肉串', sentence: 'Kebab is grilled meat.', translation: '烤肉串是烤肉。', homophoneSentence: '凯巴布is格里尔德密特.' },
        { word: 'Gyro', phonetic: '/ˈjɪərəʊ/', homophone: '吉罗', meaning: '希腊烤肉卷', sentence: 'Gyro is Greek street food.', translation: '希腊烤肉卷是希腊街头食物。', homophoneSentence: '吉罗is格瑞克斯特里特福德.' },
        { word: 'Poutine', phonetic: '/puːˈtiːn/', homophone: '普丁', meaning: '肉汁奶酪薯条', sentence: 'Poutine is Canadian dish.', translation: '肉汁奶酪薯条是加拿大菜。', homophoneSentence: '普丁is卡内迪恩迪希.' },
        { word: 'Pho', phonetic: '/fəʊ/', homophone: '福', meaning: '越南河粉', sentence: 'Pho is Vietnamese soup.', translation: '越南河粉是越南汤。', homophoneSentence: '福is维特纳米兹苏普.' },
        { word: 'Dim sum', phonetic: '/dɪm sʌm/', homophone: '点心', meaning: '点心', sentence: 'Dim sum is Chinese snack.', translation: '点心是中国小吃。', homophoneSentence: '点心is恰伊尼兹斯内克.' },
        { word: 'Spring roll', phonetic: '/sprɪŋ rəʊl/', homophone: '斯普灵罗尔', meaning: '春卷', sentence: 'Spring rolls are crispy.', translation: '春卷很脆。', homophoneSentence: '斯普灵罗尔兹啊克瑞斯皮.' },
        { word: 'Egg roll', phonetic: '/eɡ rəʊl/', homophone: '艾格罗尔', meaning: '蛋卷', sentence: 'Egg rolls are fried snacks.', translation: '蛋卷是油炸零食。', homophoneSentence: '艾格罗尔兹啊弗莱德斯内克斯.' },
        { word: 'Wonton', phonetic: '/ˈwɒntɒn/', homophone: '云吞', meaning: '馄饨', sentence: 'Wontons are filled dumplings.', translation: '馄饨是填充饺子。', homophoneSentence: '云吞兹啊菲尔德当普林z.' },
        { word: 'Fried rice', phonetic: '/fraɪd raɪs/', homophone: '弗莱德莱斯', meaning: '炒饭', sentence: 'Fried rice is popular dish.', translation: '炒饭是受欢迎的菜。', homophoneSentence: '弗莱德莱斯is帕皮尤勒迪希.' },
        { word: 'Chow mein', phonetic: '/tʃaʊ meɪn/', homophone: '炒面', meaning: '炒面', sentence: 'Chow mein is Chinese noodles.', translation: '炒面是中国面条。', homophoneSentence: '炒面is恰伊尼兹努多欧z.' },
        { word: 'Kung pao', phonetic: '/kʌŋ paʊ/', homophone: '宫保', meaning: '宫保', sentence: 'Kung pao chicken is spicy.', translation: '宫保鸡丁很辣。', homophoneSentence: '宫保奇肯is斯派西.' },
        { word: 'Sweet and sour', phonetic: '/swiːt ənd ˈsaʊə(r)/', homophone: '斯威特安德萨沃尔', meaning: '糖醋', sentence: 'Sweet and sour is classic.', translation: '糖醋是经典口味。', homophoneSentence: '斯威特安德萨沃尔is克拉西克.' },
        { word: 'Teriyaki', phonetic: '/ˌteriˈjɑːki/', homophone: '特里亚基', meaning: '照烧', sentence: 'Teriyaki is Japanese sauce.', translation: '照烧是日本酱汁。', homophoneSentence: '特里亚基is杰帕尼兹索斯.' },
        { word: 'Miso', phonetic: '/ˈmiːsəʊ/', homophone: '味噌', meaning: '味噌', sentence: 'Miso is fermented soybean paste.', translation: '味噌是发酵大豆酱。', homophoneSentence: '味噌is弗门特德索伊宾佩斯特.' },
        { word: 'Wasabi', phonetic: '/wəˈsɑːbi/', homophone: '瓦萨比', meaning: '芥末', sentence: 'Wasabi is very spicy.', translation: '芥末很辣。', homophoneSentence: '瓦萨比is歪瑞斯派西.' },
        { word: 'Soy sauce', phonetic: '/sɔɪ sɔːs/', homophone: '索伊索斯', meaning: '酱油', sentence: 'Soy sauce is essential seasoning.', translation: '酱油是必备调味品。', homophoneSentence: '索伊索斯is森歇尔西兹宁.' },
        { word: 'Oyster sauce', phonetic: '/ˈɔɪstə sɔːs/', homophone: '奥伊斯特索斯', meaning: '蚝油', sentence: 'Oyster sauce adds umami.', translation: '蚝油增添鲜味。', homophoneSentence: '奥伊斯特索斯艾兹乌玛米.' },
        { word: 'Hoisin sauce', phonetic: '/ˈhɔɪzɪn sɔːs/', homophone: '海鲜酱', meaning: '海鲜酱', sentence: 'Hoisin sauce is sweet and savory.', translation: '海鲜酱又甜又咸。', homophoneSentence: '海鲜酱is斯威特安德赛沃瑞.' },
        { word: 'Chili oil', phonetic: '/ˈtʃɪli ɔɪl/', homophone: '奇利奥伊尔', meaning: '辣椒油', sentence: 'Chili oil adds heat.', translation: '辣椒油增添辣味。', homophoneSentence: '奇利奥伊尔艾兹希特.' },
        { word: 'Sesame oil', phonetic: '/ˈsesəmi ɔɪl/', homophone: '塞萨米奥伊尔', meaning: '香油', sentence: 'Sesame oil adds aroma.', translation: '香油增添香味。', homophoneSentence: '塞萨米奥伊尔艾兹阿罗玛.' },
        { word: 'Rice vinegar', phonetic: '/raɪs ˈvɪnɪɡə(r)/', homophone: '莱斯维尼格', meaning: '米醋', sentence: 'Rice vinegar is mild.', translation: '米醋味道温和。', homophoneSentence: '莱斯维尼格is梅尔德.' },
        { word: 'Peanut butter', phonetic: '/ˈpiːnʌt ˈbʌtə(r)/', homophone: '皮纳特巴特', meaning: '花生酱', sentence: 'Peanut butter is creamy spread.', translation: '花生酱是奶油涂抹酱。', homophoneSentence: '皮纳特巴特is克里米斯普瑞德.' },
        { word: 'Nutella', phonetic: '/nʊˈtelə/', homophone: '努泰拉', meaning: '能多益', sentence: 'Nutella is chocolate spread.', translation: '能多益是巧克力酱。', homophoneSentence: '努泰拉is乔克利特斯普瑞德.' },
        { word: 'Maple syrup', phonetic: '/ˈmeɪpl ˈsɪrəp/', homophone: '梅普尔西拉普', meaning: '枫糖浆', sentence: 'Maple syrup is used on pancakes.', translation: '枫糖浆用于煎饼。', homophoneSentence: '梅普尔西拉普is优兹德昂潘凯克斯.' },
        { word: 'Agave', phonetic: '/əˈɡeɪvi/', homophone: '阿加维', meaning: '龙舌兰', sentence: 'Agave is natural sweetener.', translation: '龙舌兰是天然甜味剂。', homophoneSentence: '阿加维is纳彻尔斯威特纳.' },
        { word: 'Stevia', phonetic: '/ˈstiːviə/', homophone: '斯蒂维亚', meaning: '甜叶菊', sentence: 'Stevia is zero-calorie sweetener.', translation: '甜叶菊是零卡路里甜味剂。', homophoneSentence: '斯蒂维亚is齐罗卡路里斯威特纳.' },
        { word: 'Vanilla', phonetic: '/vəˈnɪlə/', homophone: '瓦尼拉', meaning: '香草', sentence: 'Vanilla is popular flavor.', translation: '香草是受欢迎的口味。', homophoneSentence: '瓦尼拉is帕皮尤勒弗雷沃尔.' },
        { word: 'Caramel', phonetic: '/ˈkærəml/', homophone: '卡拉梅尔', meaning: '焦糖', sentence: 'Caramel is sweet and rich.', translation: '焦糖又甜又浓郁。', homophoneSentence: '卡拉梅尔is斯威特安德瑞奇.' },
        { word: 'Toffee', phonetic: '/ˈtɒfi/', homophone: '托菲', meaning: '太妃糖', sentence: 'Toffee is chewy candy.', translation: '太妃糖是有嚼劲的糖果。', homophoneSentence: '托菲is丘伊坎迪.' },
        { word: 'Fudge', phonetic: '/fʌdʒ/', homophone: '法吉', meaning: '软糖', sentence: 'Fudge is soft and sweet.', translation: '软糖又软又甜。', homophoneSentence: '法吉is索夫特安德斯威特.' },
        { word: 'Marshmallow', phonetic: '/ˈmɑːʃmæləʊ/', homophone: '马什麦洛', meaning: '棉花糖', sentence: 'Marshmallows are fluffy.', translation: '棉花糖很蓬松。', homophoneSentence: '马什麦洛兹啊弗拉菲.' },
        { word: 'Nougat', phonetic: '/ˈnuːɡə/', homophone: '努加', meaning: '牛轧糖', sentence: 'Nougat is chewy confection.', translation: '牛轧糖是有嚼劲的糖果。', homophoneSentence: '努加is丘伊康费克申.' },
        { word: 'Licorice', phonetic: '/ˈlɪkərɪʃ/', homophone: '利科里希', meaning: '甘草糖', sentence: 'Licorice has distinct flavor.', translation: '甘草糖有独特风味。', homophoneSentence: '利科里希哈兹迪斯廷克特弗雷沃尔.' },
        { word: 'Gummy bear', phonetic: '/ˈɡʌmi beə(r)/', homophone: '古米贝尔', meaning: '小熊软糖', sentence: 'Gummy bears are chewy.', translation: '小熊软糖有嚼劲。', homophoneSentence: '古米贝尔兹啊丘伊.' },
        { word: 'Lollipop', phonetic: '/ˈlɒlipɒp/', homophone: '洛利波普', meaning: '棒棒糖', sentence: 'Lollipops are on sticks.', translation: '棒棒糖在棍子上。', homophoneSentence: '洛利波普兹啊昂斯蒂克斯.' },
        { word: 'Cotton candy', phonetic: '/ˈkɒtn ˈkændi/', homophone: '科顿坎迪', meaning: '棉花糖', sentence: 'Cotton candy is fluffy sugar.', translation: '棉花糖是蓬松的糖。', homophoneSentence: '科顿坎迪is弗拉菲舒格.' },
        { word: 'Popcorn', phonetic: '/ˈpɒpkɔːn/', homophone: '波普科恩', meaning: '爆米花', sentence: 'Popcorn is movie snack.', translation: '爆米花是电影零食。', homophoneSentence: '波普科恩is穆维斯内克.' },
        { word: 'Pretzel', phonetic: '/ˈpretsl/', homophone: '普雷策尔', meaning: '椒盐卷饼', sentence: 'Pretzels are salty snacks.', translation: '椒盐卷饼是咸零食。', homophoneSentence: '普雷策尔兹啊索尔蒂斯内克斯.' },
        { word: 'Chips', phonetic: '/tʃɪps/', homophone: '奇普斯', meaning: '薯片', sentence: 'Chips are crispy snacks.', translation: '薯片是脆零食。', homophoneSentence: '奇普斯啊克瑞斯皮斯内克斯.' },
        { word: 'Crackers', phonetic: '/ˈkrækəz/', homophone: '克拉克斯', meaning: '饼干', sentence: 'Crackers go with cheese.', translation: '饼干配奶酪。', homophoneSentence: '克拉克斯勾威斯奇兹.' },
        { word: 'Nachos', phonetic: '/ˈnɑːtʃəʊz/', homophone: '纳乔斯', meaning: '玉米片', sentence: 'Nachos are served with salsa.', translation: '玉米片配莎莎酱。', homophoneSentence: '纳乔斯啊瑟夫德威斯萨尔萨.' },
        { word: 'Guacamole', phonetic: '/ˌɡwɑːkəˈməʊli/', homophone: '瓜卡莫利', meaning: '牛油果酱', sentence: 'Guacamole is avocado dip.', translation: '牛油果酱是牛油果蘸酱。', homophoneSentence: '瓜卡莫利is阿沃卡多迪普.' },
        { word: 'Sour cream', phonetic: '/ˈsaʊə(r) kriːm/', homophone: '萨沃尔克里姆', meaning: '酸奶油', sentence: 'Sour cream is tangy topping.', translation: '酸奶油是酸味配料。', homophoneSentence: '萨沃尔克里姆is坦吉托平.' },
        { word: 'Whipped cream', phonetic: '/wɪpt kriːm/', homophone: '威普特克里姆', meaning: '打发奶油', sentence: 'Whipped cream is fluffy.', translation: '打发奶油很蓬松。', homophoneSentence: '威普特克里姆is弗拉菲.' },
        { word: 'Condensed milk', phonetic: '/kənˈdenst mɪlk/', homophone: '康登斯特米尔克', meaning: '炼乳', sentence: 'Condensed milk is very sweet.', translation: '炼乳非常甜。', homophoneSentence: '康登斯特米尔克is歪瑞斯威特.' },
        { word: 'Evaporated milk', phonetic: '/ɪˈvæpəreɪtɪd mɪlk/', homophone: '伊瓦帕瑞泰特米尔克', meaning: '淡奶', sentence: 'Evaporated milk is concentrated.', translation: '淡奶是浓缩的。', homophoneSentence: '伊瓦帕瑞泰特米尔克is康森特瑞泰特.' },
        { word: 'Coconut milk', phonetic: '/ˈkəʊkənʌt mɪlk/', homophone: '扣扣纳特米尔克', meaning: '椰奶', sentence: 'Coconut milk is creamy liquid.', translation: '椰奶是奶油状液体。', homophoneSentence: '扣扣纳特米尔克is克里米利奎德.' },
        { word: 'Almond milk', phonetic: '/ˈɑːmənd mɪlk/', homophone: '阿蒙德米尔克', meaning: '杏仁奶', sentence: 'Almond milk is dairy-free.', translation: '杏仁奶不含乳制品。', homophoneSentence: '阿蒙德米尔克is戴尔弗瑞.' },
        { word: 'Oat milk', phonetic: '/əʊt mɪlk/', homophone: '欧特米尔克', meaning: '燕麦奶', sentence: 'Oat milk is plant-based.', translation: '燕麦奶是植物基的。', homophoneSentence: '欧特米尔克is普兰特贝斯特.' },
        { word: 'Soy milk', phonetic: '/sɔɪ mɪlk/', homophone: '索伊米尔克', meaning: '豆浆', sentence: 'Soy milk is made from soybeans.', translation: '豆浆由大豆制成。', homophoneSentence: '索伊米尔克is梅德弗罗姆索伊宾z.' },
        { word: 'Rice milk', phonetic: '/raɪs mɪlk/', homophone: '莱斯米尔克', meaning: '米浆', sentence: 'Rice milk is mild and sweet.', translation: '米浆味道温和又甜。', homophoneSentence: '莱斯米尔克is梅尔德安德斯威特.' }
    ];
}

const newFoodWords = generateFoodWords();
console.log('Generated', newFoodWords.length, 'food words');
module.exports = newFoodWords;